/*
###############################################################
#  Generated by:      Cadence Innovus 23.14-s088_1
#  OS:                Linux x86_64(Host ID lnx-prd-03.ece.vt.edu)
#  Generated on:      Wed Dec 10 22:38:47 2025
#  Design:            elevator_top
#  Command:           write_netlist elevator_top_struct_inn.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 23.14-s090_1
// Generated on: Dec 10 2025 22:13:40 EST (Dec 11 2025 03:13:40 UTC)
// Verification Directory fv/elevator_top 
module elevator_top (
	clks, 
	reset_n, 
	raw_floor_call_buttons, 
	raw_panel_buttons, 
	raw_door_open_btn, 
	raw_door_close_btn, 
	raw_emergency_btn, 
	raw_power_switch, 
	weight_sensor, 
	call_button_lights, 
	panel_button_lights, 
	door_open, 
	elevator_control_output, 
	safety_interlock, 
	floor_indicator_lamps, 
	elevator_upward_indicator_lamp, 
	elevator_downward_indicator_lamp, 
	alarm, 
	weight_overload_lamp);
   input clks;
   input reset_n;
   input [10:0] raw_floor_call_buttons;
   input [10:0] raw_panel_buttons;
   input raw_door_open_btn;
   input raw_door_close_btn;
   input raw_emergency_btn;
   input raw_power_switch;
   input weight_sensor;
   output [10:0] call_button_lights;
   output [10:0] panel_button_lights;
   output door_open;
   output [10:0] elevator_control_output;
   output safety_interlock;
   output [3:0] floor_indicator_lamps;
   output elevator_upward_indicator_lamp;
   output elevator_downward_indicator_lamp;
   output alarm;
   output weight_overload_lamp;

   // Internal wires
   wire FE_PDN15_n_618;
   wire FE_OFN13_n_605;
   wire FE_OFN12_n_513;
   wire CTS_8;
   wire CTS_7;
   wire CTS_6;
   wire CTS_5;
   wire CTS_4;
   wire CTS_3;
   wire CTS_2;
   wire CTS_1;
   wire FE_OFN11_elevator_fsm_inst_counter_state_4__1630;
   wire FE_OFN2_n_25;
   wire [3:0] elevator_floor_selector;
   wire [1:0] emergency_debouncer_key_current_state;
   wire [1:0] floor_call_debouncer0_key_current_state;
   wire [1:0] floor_call_debouncer1_key_current_state;
   wire [1:0] floor_call_debouncer2_key_current_state;
   wire [1:0] floor_call_debouncer3_key_current_state;
   wire [1:0] floor_call_debouncer4_key_current_state;
   wire [1:0] floor_call_debouncer5_key_current_state;
   wire [1:0] floor_call_debouncer6_key_current_state;
   wire [1:0] floor_call_debouncer7_key_current_state;
   wire [1:0] floor_call_debouncer8_key_current_state;
   wire [1:0] floor_call_debouncer9_key_current_state;
   wire [1:0] floor_call_debouncer10_key_current_state;
   wire [1:0] panel_debouncer0_key_current_state;
   wire [1:0] panel_debouncer1_key_current_state;
   wire [1:0] panel_debouncer2_key_current_state;
   wire [1:0] panel_debouncer3_key_current_state;
   wire [1:0] panel_debouncer4_key_current_state;
   wire [1:0] panel_debouncer5_key_current_state;
   wire [1:0] panel_debouncer6_key_current_state;
   wire [1:0] panel_debouncer7_key_current_state;
   wire [1:0] panel_debouncer8_key_current_state;
   wire [1:0] panel_debouncer9_key_current_state;
   wire [1:0] panel_debouncer10_key_current_state;
   wire [10:0] panel_buttons;
   wire [10:0] floor_call_buttons;
   wire [1:0] door_open_debouncer_key_current_state;
   wire [1:0] door_close_debouncer_key_current_state;
   wire FE_OFN0_reset_n;
   wire FE_OFN1_call_button_lights_10;
   wire FE_OFN3_call_button_lights_9;
   wire FE_OFN4_call_button_lights_8;
   wire FE_OFN5_call_button_lights_7;
   wire FE_OFN7_call_button_lights_6;
   wire FE_OFN8_call_button_lights_5;
   wire FE_OFN10_call_button_lights_4;
   wire FE_OFN11_call_button_lights_3;
   wire FE_OFN12_call_button_lights_2;
   wire FE_OFN13_call_button_lights_1;
   wire FE_OFN15_call_button_lights_0;
   wire FE_OFN16_panel_button_lights_10;
   wire FE_OFN17_panel_button_lights_9;
   wire FE_OFN18_panel_button_lights_8;
   wire FE_OFN19_panel_button_lights_7;
   wire FE_OFN21_panel_button_lights_6;
   wire FE_OFN22_panel_button_lights_5;
   wire FE_OFN24_panel_button_lights_4;
   wire FE_OFN25_panel_button_lights_3;
   wire FE_OFN26_panel_button_lights_2;
   wire FE_OFN27_panel_button_lights_1;
   wire FE_OFN29_panel_button_lights_0;
   wire FE_OFN31_elevator_control_output_9;
   wire FE_OFN33_elevator_control_output_7;
   wire FE_OFN34_elevator_control_output_7;
   wire FE_OFN37_elevator_floor_selector_0;
   wire FE_OFN38_elevator_fsm_inst_counter_state_1__1627;
   wire FE_OFN39_elevator_fsm_inst_counter_state_2__1628;
   wire FE_OFN40_floor_logic_inst_n_272;
   wire FE_OFN41_n_140;
   wire FE_OFN42_n_335;
   wire FE_OFN43_n_216;
   wire FE_OFN44_n_470;
   wire FE_OFN45_elevator_control_output_3;
   wire FE_OFN47_alarm;
   wire FE_OFN50_n_574;
   wire FE_OFN51_elevator_control_output_2;
   wire FE_OFN53_n_44;
   wire FE_OFN54_n_599;
   wire FE_OFN55_elevator_control_output_10;
   wire FE_OFN57_elevator_control_output_8;
   wire FE_OFN59_elevator_control_output_0;
   wire FE_OFN60_elevator_control_output_0;
   wire FE_OFN63_elevator_control_output_1;
   wire FE_OFN65_door_open;
   wire FE_OFN66_floor_logic_inst_n_1371;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire UNCONNECTED7;
   wire UNCONNECTED8;
   wire UNCONNECTED9;
   wire UNCONNECTED10;
   wire UNCONNECTED11;
   wire UNCONNECTED12;
   wire UNCONNECTED13;
   wire UNCONNECTED14;
   wire UNCONNECTED15;
   wire UNCONNECTED16;
   wire UNCONNECTED17;
   wire UNCONNECTED18;
   wire UNCONNECTED19;
   wire UNCONNECTED20;
   wire UNCONNECTED21;
   wire UNCONNECTED22;
   wire UNCONNECTED23;
   wire UNCONNECTED24;
   wire UNCONNECTED25;
   wire UNCONNECTED26;
   wire UNCONNECTED27;
   wire UNCONNECTED28;
   wire UNCONNECTED29;
   wire UNCONNECTED30;
   wire UNCONNECTED31;
   wire UNCONNECTED32;
   wire UNCONNECTED33;
   wire UNCONNECTED34;
   wire UNCONNECTED35;
   wire UNCONNECTED36;
   wire UNCONNECTED37;
   wire UNCONNECTED38;
   wire UNCONNECTED39;
   wire UNCONNECTED40;
   wire UNCONNECTED41;
   wire UNCONNECTED42;
   wire UNCONNECTED43;
   wire UNCONNECTED44;
   wire UNCONNECTED45;
   wire UNCONNECTED46;
   wire UNCONNECTED47;
   wire UNCONNECTED48;
   wire UNCONNECTED49;
   wire UNCONNECTED50;
   wire UNCONNECTED51;
   wire UNCONNECTED52;
   wire UNCONNECTED53;
   wire UNCONNECTED54;
   wire UNCONNECTED55;
   wire UNCONNECTED56;
   wire UNCONNECTED57;
   wire UNCONNECTED58;
   wire UNCONNECTED59;
   wire UNCONNECTED60;
   wire UNCONNECTED61;
   wire UNCONNECTED62;
   wire UNCONNECTED63;
   wire UNCONNECTED64;
   wire UNCONNECTED65;
   wire UNCONNECTED66;
   wire UNCONNECTED67;
   wire UNCONNECTED68;
   wire UNCONNECTED69;
   wire UNCONNECTED70;
   wire UNCONNECTED71;
   wire UNCONNECTED72;
   wire UNCONNECTED73;
   wire UNCONNECTED74;
   wire UNCONNECTED75;
   wire UNCONNECTED76;
   wire UNCONNECTED77;
   wire UNCONNECTED78;
   wire UNCONNECTED79;
   wire UNCONNECTED80;
   wire UNCONNECTED81;
   wire UNCONNECTED82;
   wire direction_selector;
   wire door_close_btn;
   wire door_close_logic_check;
   wire door_open_btn;
   wire door_open_logic_check;
   wire \elevator_fsm_inst_counter_state[1]_1627 ;
   wire \elevator_fsm_inst_counter_state[2]_1628 ;
   wire \elevator_fsm_inst_counter_state[3]_1629 ;
   wire \elevator_fsm_inst_counter_state[4]_1630 ;
   wire elevator_fsm_inst_n_3927;
   wire elevator_fsm_inst_n_3955;
   wire elevator_fsm_inst_n_4141;
   wire emergency_btn;
   wire floor_logic_inst_n_246;
   wire floor_logic_inst_n_272;
   wire floor_logic_inst_n_359;
   wire floor_logic_inst_n_385;
   wire floor_logic_inst_n_1371;
   wire floor_logic_inst_n_4785;
   wire floor_logic_inst_n_4842;
   wire floor_logic_inst_n_4880;
   wire n_0;
   wire n_2;
   wire n_25;
   wire n_36;
   wire n_37;
   wire n_44;
   wire n_45;
   wire n_47;
   wire n_52;
   wire n_57;
   wire n_61;
   wire n_70;
   wire n_72;
   wire n_74;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_91;
   wire n_122;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_145;
   wire n_151;
   wire n_156;
   wire n_160;
   wire n_169;
   wire n_176;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_195;
   wire n_196;
   wire n_197;
   wire n_198;
   wire n_199;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_203;
   wire n_204;
   wire n_205;
   wire n_206;
   wire n_207;
   wire n_208;
   wire n_209;
   wire n_210;
   wire n_211;
   wire n_212;
   wire n_213;
   wire n_214;
   wire n_215;
   wire n_216;
   wire n_217;
   wire n_218;
   wire n_219;
   wire n_220;
   wire n_221;
   wire n_222;
   wire n_223;
   wire n_224;
   wire n_225;
   wire n_226;
   wire n_227;
   wire n_228;
   wire n_229;
   wire n_230;
   wire n_231;
   wire n_232;
   wire n_233;
   wire n_234;
   wire n_235;
   wire n_236;
   wire n_237;
   wire n_238;
   wire n_239;
   wire n_240;
   wire n_241;
   wire n_242;
   wire n_243;
   wire n_244;
   wire n_245;
   wire n_246;
   wire n_247;
   wire n_248;
   wire n_249;
   wire n_250;
   wire n_251;
   wire n_252;
   wire n_253;
   wire n_254;
   wire n_255;
   wire n_256;
   wire n_257;
   wire n_258;
   wire n_259;
   wire n_260;
   wire n_261;
   wire n_262;
   wire n_263;
   wire n_264;
   wire n_265;
   wire n_266;
   wire n_267;
   wire n_268;
   wire n_269;
   wire n_270;
   wire n_271;
   wire n_272;
   wire n_273;
   wire n_274;
   wire n_275;
   wire n_276;
   wire n_277;
   wire n_278;
   wire n_279;
   wire n_280;
   wire n_281;
   wire n_282;
   wire n_283;
   wire n_284;
   wire n_285;
   wire n_286;
   wire n_287;
   wire n_288;
   wire n_289;
   wire n_290;
   wire n_291;
   wire n_292;
   wire n_293;
   wire n_294;
   wire n_295;
   wire n_296;
   wire n_297;
   wire n_298;
   wire n_299;
   wire n_300;
   wire n_301;
   wire n_302;
   wire n_303;
   wire n_304;
   wire n_305;
   wire n_306;
   wire n_307;
   wire n_308;
   wire n_309;
   wire n_310;
   wire n_311;
   wire n_312;
   wire n_313;
   wire n_314;
   wire n_315;
   wire n_316;
   wire n_317;
   wire n_318;
   wire n_319;
   wire n_320;
   wire n_321;
   wire n_322;
   wire n_323;
   wire n_324;
   wire n_325;
   wire n_326;
   wire n_327;
   wire n_328;
   wire n_329;
   wire n_330;
   wire n_331;
   wire n_332;
   wire n_333;
   wire n_334;
   wire n_335;
   wire n_336;
   wire n_337;
   wire n_338;
   wire n_339;
   wire n_340;
   wire n_341;
   wire n_342;
   wire n_343;
   wire n_344;
   wire n_345;
   wire n_346;
   wire n_347;
   wire n_348;
   wire n_349;
   wire n_350;
   wire n_351;
   wire n_352;
   wire n_353;
   wire n_354;
   wire n_355;
   wire n_356;
   wire n_357;
   wire n_358;
   wire n_359;
   wire n_360;
   wire n_361;
   wire n_362;
   wire n_363;
   wire n_364;
   wire n_365;
   wire n_366;
   wire n_367;
   wire n_368;
   wire n_369;
   wire n_370;
   wire n_371;
   wire n_372;
   wire n_373;
   wire n_374;
   wire n_375;
   wire n_376;
   wire n_377;
   wire n_378;
   wire n_379;
   wire n_380;
   wire n_381;
   wire n_382;
   wire n_383;
   wire n_384;
   wire n_385;
   wire n_386;
   wire n_387;
   wire n_388;
   wire n_389;
   wire n_390;
   wire n_391;
   wire n_392;
   wire n_393;
   wire n_394;
   wire n_395;
   wire n_396;
   wire n_397;
   wire n_398;
   wire n_399;
   wire n_400;
   wire n_401;
   wire n_402;
   wire n_403;
   wire n_404;
   wire n_405;
   wire n_406;
   wire n_407;
   wire n_408;
   wire n_409;
   wire n_410;
   wire n_411;
   wire n_412;
   wire n_413;
   wire n_414;
   wire n_415;
   wire n_416;
   wire n_417;
   wire n_418;
   wire n_419;
   wire n_420;
   wire n_421;
   wire n_422;
   wire n_423;
   wire n_424;
   wire n_425;
   wire n_426;
   wire n_427;
   wire n_428;
   wire n_429;
   wire n_430;
   wire n_431;
   wire n_432;
   wire n_433;
   wire n_434;
   wire n_435;
   wire n_436;
   wire n_437;
   wire n_438;
   wire n_439;
   wire n_440;
   wire n_441;
   wire n_442;
   wire n_443;
   wire n_444;
   wire n_445;
   wire n_446;
   wire n_447;
   wire n_448;
   wire n_449;
   wire n_450;
   wire n_451;
   wire n_452;
   wire n_453;
   wire n_454;
   wire n_455;
   wire n_456;
   wire n_457;
   wire n_458;
   wire n_459;
   wire n_460;
   wire n_461;
   wire n_462;
   wire n_463;
   wire n_464;
   wire n_465;
   wire n_466;
   wire n_467;
   wire n_468;
   wire n_469;
   wire n_470;
   wire n_471;
   wire n_472;
   wire n_473;
   wire n_474;
   wire n_475;
   wire n_476;
   wire n_477;
   wire n_478;
   wire n_479;
   wire n_480;
   wire n_481;
   wire n_482;
   wire n_483;
   wire n_484;
   wire n_485;
   wire n_486;
   wire n_487;
   wire n_488;
   wire n_489;
   wire n_490;
   wire n_491;
   wire n_492;
   wire n_493;
   wire n_494;
   wire n_495;
   wire n_496;
   wire n_497;
   wire n_498;
   wire n_499;
   wire n_500;
   wire n_501;
   wire n_502;
   wire n_503;
   wire n_504;
   wire n_505;
   wire n_506;
   wire n_507;
   wire n_508;
   wire n_509;
   wire n_510;
   wire n_511;
   wire n_512;
   wire n_513;
   wire n_514;
   wire n_515;
   wire n_516;
   wire n_517;
   wire n_518;
   wire n_519;
   wire n_520;
   wire n_521;
   wire n_522;
   wire n_523;
   wire n_524;
   wire n_525;
   wire n_526;
   wire n_527;
   wire n_528;
   wire n_529;
   wire n_530;
   wire n_531;
   wire n_532;
   wire n_533;
   wire n_534;
   wire n_535;
   wire n_536;
   wire n_537;
   wire n_538;
   wire n_539;
   wire n_540;
   wire n_541;
   wire n_542;
   wire n_543;
   wire n_544;
   wire n_545;
   wire n_546;
   wire n_547;
   wire n_548;
   wire n_549;
   wire n_550;
   wire n_551;
   wire n_552;
   wire n_553;
   wire n_554;
   wire n_555;
   wire n_556;
   wire n_557;
   wire n_558;
   wire n_559;
   wire n_560;
   wire n_561;
   wire n_562;
   wire n_563;
   wire n_564;
   wire n_565;
   wire n_566;
   wire n_567;
   wire n_568;
   wire n_569;
   wire n_570;
   wire n_571;
   wire n_572;
   wire n_573;
   wire n_574;
   wire n_575;
   wire n_576;
   wire n_577;
   wire n_578;
   wire n_579;
   wire n_580;
   wire n_581;
   wire n_582;
   wire n_583;
   wire n_584;
   wire n_585;
   wire n_586;
   wire n_587;
   wire n_588;
   wire n_589;
   wire n_590;
   wire n_591;
   wire n_592;
   wire n_593;
   wire n_594;
   wire n_595;
   wire n_596;
   wire n_597;
   wire n_598;
   wire n_599;
   wire n_600;
   wire n_601;
   wire n_602;
   wire n_603;
   wire n_604;
   wire n_605;
   wire n_606;
   wire n_607;
   wire n_608;
   wire n_609;
   wire n_610;
   wire n_611;
   wire n_612;
   wire n_613;
   wire n_614;
   wire n_615;
   wire n_616;
   wire n_617;
   wire n_618;
   wire n_619;
   wire n_620;
   wire n_621;
   wire n_622;
   wire n_623;
   wire n_624;
   wire n_625;
   wire n_626;
   wire n_627;
   wire n_628;
   wire n_629;
   wire n_630;
   wire n_631;
   wire n_632;
   wire n_633;
   wire n_634;
   wire n_635;
   wire n_636;
   wire n_637;
   wire n_638;
   wire n_639;
   wire n_645;
   wire n_646;
   wire n_647;
   wire n_648;
   wire n_649;
   wire n_650;
   wire n_651;
   wire n_652;
   wire n_653;
   wire n_654;
   wire n_655;
   wire n_656;
   wire n_657;
   wire n_658;
   wire n_659;
   wire n_660;
   wire n_661;
   wire n_662;
   wire n_663;
   wire n_664;
   wire n_665;
   wire n_666;
   wire n_667;
   wire n_668;
   wire n_669;
   wire n_670;
   wire n_671;
   wire n_672;
   wire n_673;
   wire n_674;
   wire n_675;
   wire n_676;
   wire n_677;
   wire n_678;
   wire n_679;
   wire n_680;
   wire n_681;
   wire n_682;
   wire n_683;
   wire n_684;
   wire n_685;
   wire n_686;
   wire n_687;
   wire n_688;
   wire n_689;
   wire n_690;
   wire n_691;
   wire n_692;
   wire n_693;
   wire n_694;
   wire n_695;
   wire n_696;
   wire n_697;
   wire n_698;
   wire n_699;
   wire n_700;
   wire n_701;
   wire n_702;
   wire n_703;
   wire n_704;
   wire n_705;
   wire n_706;
   wire n_707;
   wire n_708;
   wire n_709;
   wire n_710;
   wire n_711;
   wire n_712;
   wire n_713;
   wire n_714;
   wire n_715;
   wire n_716;
   wire n_717;
   wire n_718;
   wire n_719;
   wire n_720;
   wire n_722;
   wire n_724;
   wire n_725;
   wire n_726;
   wire n_728;
   wire n_729;
   wire n_730;
   wire n_731;
   wire n_732;
   wire n_733;
   wire n_734;
   wire n_735;
   wire n_736;
   wire n_737;
   wire n_738;
   wire n_739;
   wire n_740;
   wire n_741;
   wire n_742;
   wire n_743;

   assign weight_overload_lamp = weight_sensor ;

   CLKBUFX4 FE_PDC17_n_618 (.Y(FE_PDN15_n_618),
	.A(n_618));
   BUFX16 FE_OFC16_call_button_lights_1 (.Y(call_button_lights[1]),
	.A(FE_OFN13_call_button_lights_1));
   BUFX2 FE_OFC15_n_605 (.Y(FE_OFN13_n_605),
	.A(n_605));
   BUFX2 FE_OFC14_n_513 (.Y(FE_OFN12_n_513),
	.A(n_513));
   INVX4 CTS_ccl_a_inv_00007 (.Y(CTS_7),
	.A(CTS_8));
   INVX4 CTS_ccl_a_inv_00006 (.Y(CTS_6),
	.A(CTS_8));
   INVX4 CTS_ccl_a_inv_00005 (.Y(CTS_5),
	.A(CTS_8));
   INVX4 CTS_ccl_a_inv_00004 (.Y(CTS_4),
	.A(CTS_8));
   INVX4 CTS_ccl_a_inv_00003 (.Y(CTS_3),
	.A(CTS_8));
   INVX4 CTS_ccl_a_inv_00002 (.Y(CTS_2),
	.A(CTS_8));
   INVX4 CTS_ccl_a_inv_00001 (.Y(CTS_1),
	.A(CTS_8));
   INVX8 CTS_ccl_a_inv_00008 (.Y(CTS_8),
	.A(clks));
   BUFX2 FE_OFC13_elevator_fsm_inst_counter_state_4__1630 (.Y(FE_OFN11_elevator_fsm_inst_counter_state_4__1630),
	.A(\elevator_fsm_inst_counter_state[4]_1630 ));
   CLKINVX2 FE_OFC12_n_25 (.Y(emergency_btn),
	.A(FE_OFN2_n_25));
   CLKINVX2 FE_OFC11_n_25 (.Y(FE_OFN2_n_25),
	.A(n_25));
   BUFX16 FE_OFC10_elevator_control_output_7 (.Y(floor_indicator_lamps[0]),
	.A(FE_OFN34_elevator_control_output_7));
   BUFX16 FE_OFC9_elevator_control_output_7 (.Y(elevator_control_output[7]),
	.A(FE_OFN34_elevator_control_output_7));
   INVX4 FE_OFC8_elevator_control_output_7 (.Y(n_91),
	.A(FE_OFN34_elevator_control_output_7));
   CLKINVX1 FE_OFC7_n_372 (.Y(n_373),
	.A(n_372));
   BUFX16 FE_OFC6_floor_indicator_lamps_3 (.Y(floor_indicator_lamps[3]),
	.A(FE_OFN55_elevator_control_output_10));
   BUFX16 FE_OFC94_alarm (.Y(alarm),
	.A(FE_OFN47_alarm));
   BUFX16 FE_OFC93_elevator_control_output_6 (.Y(elevator_control_output[6]),
	.A(FE_OFN47_alarm));
   BUFX16 FE_OFC92_call_button_lights_10 (.Y(call_button_lights[10]),
	.A(FE_OFN1_call_button_lights_10));
   BUFX16 FE_OFC91_panel_button_lights_10 (.Y(panel_button_lights[10]),
	.A(FE_OFN16_panel_button_lights_10));
   BUFX16 FE_OFC90_panel_button_lights_0 (.Y(panel_button_lights[0]),
	.A(FE_OFN29_panel_button_lights_0));
   BUFX16 FE_OFC89_elevator_control_output_1 (.Y(elevator_control_output[1]),
	.A(FE_OFN60_elevator_control_output_0));
   CLKINVX2 FE_OFC87_floor_logic_inst_n_272 (.Y(FE_OFN40_floor_logic_inst_n_272),
	.A(n_139));
   CLKINVX2 FE_OFC86_floor_logic_inst_n_272 (.Y(n_139),
	.A(floor_logic_inst_n_272));
   CLKINVX1 FE_OFC85_n_285 (.Y(n_284),
	.A(n_285));
   CLKINVX1 FE_OFC84_n_335 (.Y(FE_OFN42_n_335),
	.A(n_334));
   CLKINVX1 FE_OFC83_n_335 (.Y(n_334),
	.A(n_335));
   CLKINVX2 FE_OFC82_n_682 (.Y(n_681),
	.A(n_682));
   CLKINVX2 FE_OFC81_n_216 (.Y(n_215),
	.A(FE_OFN43_n_216));
   CLKINVX2 FE_OFC80_n_216 (.Y(FE_OFN43_n_216),
	.A(n_216));
   CLKINVX2 FE_OFC76_n_398 (.Y(n_399),
	.A(n_398));
   CLKINVX2 FE_OFC75_elevator_control_output_0 (.Y(FE_OFN63_elevator_control_output_1),
	.A(FE_OFN60_elevator_control_output_0));
   BUFX16 FE_OFC74_elevator_control_output_0 (.Y(elevator_control_output[0]),
	.A(FE_OFN59_elevator_control_output_0));
   CLKINVX2 FE_OFC73_elevator_control_output_0 (.Y(FE_OFN60_elevator_control_output_0),
	.A(FE_OFN59_elevator_control_output_0));
   CLKINVX2 FE_OFC72_n_599 (.Y(n_600),
	.A(FE_OFN54_n_599));
   CLKINVX2 FE_OFC71_n_599 (.Y(FE_OFN54_n_599),
	.A(n_599));
   CLKINVX1 FE_OFC70_n_592 (.Y(n_591),
	.A(n_592));
   BUFX2 FE_OFC66_floor_logic_inst_n_1371 (.Y(FE_OFN66_floor_logic_inst_n_1371),
	.A(floor_logic_inst_n_1371));
   BUFX16 FE_OFC65_door_open (.Y(door_open),
	.A(FE_OFN65_door_open));
   BUFX16 FE_OFC64_elevator_control_output_1 (.Y(elevator_control_output[5]),
	.A(FE_OFN60_elevator_control_output_0));
   BUFX16 FE_OFC62_elevator_control_output_0 (.Y(safety_interlock),
	.A(FE_OFN59_elevator_control_output_0));
   BUFX16 FE_OFC61_elevator_control_output_0 (.Y(elevator_control_output[4]),
	.A(FE_OFN59_elevator_control_output_0));
   BUFX16 FE_OFC58_elevator_control_output_8 (.Y(floor_indicator_lamps[1]),
	.A(FE_OFN57_elevator_control_output_8));
   BUFX16 FE_OFC57_elevator_control_output_8 (.Y(elevator_control_output[8]),
	.A(FE_OFN57_elevator_control_output_8));
   BUFX16 FE_OFC56_elevator_control_output_10 (.Y(elevator_control_output[10]),
	.A(FE_OFN55_elevator_control_output_10));
   BUFX2 FE_OFC53_n_44 (.Y(FE_OFN53_n_44),
	.A(n_44));
   BUFX16 FE_OFC52_elevator_control_output_2 (.Y(elevator_upward_indicator_lamp),
	.A(FE_OFN51_elevator_control_output_2));
   BUFX16 FE_OFC51_elevator_control_output_2 (.Y(elevator_control_output[2]),
	.A(FE_OFN51_elevator_control_output_2));
   BUFX2 FE_OFC50_n_574 (.Y(FE_OFN50_n_574),
	.A(n_574));
   BUFX16 FE_OFC46_elevator_control_output_3 (.Y(elevator_control_output[3]),
	.A(FE_OFN45_elevator_control_output_3));
   BUFX16 FE_OFC45_elevator_control_output_3 (.Y(elevator_downward_indicator_lamp),
	.A(FE_OFN45_elevator_control_output_3));
   BUFX2 FE_OFC44_n_470 (.Y(FE_OFN44_n_470),
	.A(n_470));
   BUFX2 FE_OFC41_n_140 (.Y(FE_OFN41_n_140),
	.A(n_140));
   CLKBUFX4 FE_OFC39_elevator_fsm_inst_counter_state_2__1628 (.Y(FE_OFN39_elevator_fsm_inst_counter_state_2__1628),
	.A(\elevator_fsm_inst_counter_state[2]_1628 ));
   CLKBUFX4 FE_OFC38_elevator_fsm_inst_counter_state_1__1627 (.Y(FE_OFN38_elevator_fsm_inst_counter_state_1__1627),
	.A(\elevator_fsm_inst_counter_state[1]_1627 ));
   BUFX2 FE_OFC37_elevator_floor_selector_0 (.Y(FE_OFN37_elevator_floor_selector_0),
	.A(elevator_floor_selector[0]));
   CLKBUFX4 FE_OFC33_elevator_control_output_7 (.Y(FE_OFN34_elevator_control_output_7),
	.A(FE_OFN33_elevator_control_output_7));
   BUFX16 FE_OFC32_elevator_control_output_9 (.Y(floor_indicator_lamps[2]),
	.A(FE_OFN31_elevator_control_output_9));
   BUFX16 FE_OFC31_elevator_control_output_9 (.Y(elevator_control_output[9]),
	.A(FE_OFN31_elevator_control_output_9));
   BUFX16 FE_OFC28_panel_button_lights_1 (.Y(panel_button_lights[1]),
	.A(FE_OFN27_panel_button_lights_1));
   BUFX16 FE_OFC26_panel_button_lights_2 (.Y(panel_button_lights[2]),
	.A(FE_OFN26_panel_button_lights_2));
   BUFX16 FE_OFC25_panel_button_lights_3 (.Y(panel_button_lights[3]),
	.A(FE_OFN25_panel_button_lights_3));
   BUFX16 FE_OFC24_panel_button_lights_4 (.Y(panel_button_lights[4]),
	.A(FE_OFN24_panel_button_lights_4));
   BUFX16 FE_OFC23_panel_button_lights_5 (.Y(panel_button_lights[5]),
	.A(FE_OFN22_panel_button_lights_5));
   BUFX16 FE_OFC21_panel_button_lights_6 (.Y(panel_button_lights[6]),
	.A(FE_OFN21_panel_button_lights_6));
   BUFX16 FE_OFC19_panel_button_lights_7 (.Y(panel_button_lights[7]),
	.A(FE_OFN19_panel_button_lights_7));
   BUFX16 FE_OFC18_panel_button_lights_8 (.Y(panel_button_lights[8]),
	.A(FE_OFN18_panel_button_lights_8));
   BUFX16 FE_OFC17_panel_button_lights_9 (.Y(panel_button_lights[9]),
	.A(FE_OFN17_panel_button_lights_9));
   BUFX16 FE_OFC15_call_button_lights_0 (.Y(call_button_lights[0]),
	.A(FE_OFN15_call_button_lights_0));
   BUFX16 FE_OFC12_call_button_lights_2 (.Y(call_button_lights[2]),
	.A(FE_OFN12_call_button_lights_2));
   BUFX16 FE_OFC11_call_button_lights_3 (.Y(call_button_lights[3]),
	.A(FE_OFN11_call_button_lights_3));
   BUFX16 FE_OFC10_call_button_lights_4 (.Y(call_button_lights[4]),
	.A(FE_OFN10_call_button_lights_4));
   BUFX16 FE_OFC9_call_button_lights_5 (.Y(call_button_lights[5]),
	.A(FE_OFN8_call_button_lights_5));
   BUFX16 FE_OFC7_call_button_lights_6 (.Y(call_button_lights[6]),
	.A(FE_OFN7_call_button_lights_6));
   BUFX16 FE_OFC5_call_button_lights_7 (.Y(call_button_lights[7]),
	.A(FE_OFN5_call_button_lights_7));
   BUFX16 FE_OFC4_call_button_lights_8 (.Y(call_button_lights[8]),
	.A(FE_OFN4_call_button_lights_8));
   BUFX16 FE_OFC3_call_button_lights_9 (.Y(call_button_lights[9]),
	.A(FE_OFN3_call_button_lights_9));
   BUFX2 FE_OFC0_reset_n (.Y(FE_OFN0_reset_n),
	.A(reset_n));
   DFFRX1 \door_close_debouncer_key_current_state_reg[1]  (.Q(door_close_btn),
	.QN(UNCONNECTED),
	.CK(CTS_3),
	.D(n_678),
	.RN(reset_n));
   DFFRX1 \door_open_debouncer_key_current_state_reg[1]  (.Q(door_open_btn),
	.QN(UNCONNECTED0),
	.CK(CTS_3),
	.D(n_671),
	.RN(reset_n));
   DFFRX1 \emergency_debouncer_key_current_state_reg[0]  (.Q(emergency_debouncer_key_current_state[0]),
	.QN(UNCONNECTED1),
	.CK(CTS_1),
	.D(n_701),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer0_key_current_state_reg[0]  (.Q(floor_call_debouncer0_key_current_state[0]),
	.QN(UNCONNECTED2),
	.CK(CTS_2),
	.D(n_670),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer1_key_current_state_reg[0]  (.Q(floor_call_debouncer1_key_current_state[0]),
	.QN(UNCONNECTED3),
	.CK(CTS_1),
	.D(n_677),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer2_key_current_state_reg[0]  (.Q(floor_call_debouncer2_key_current_state[0]),
	.QN(UNCONNECTED4),
	.CK(CTS_2),
	.D(n_689),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer3_key_current_state_reg[0]  (.Q(floor_call_debouncer3_key_current_state[0]),
	.QN(UNCONNECTED5),
	.CK(CTS_5),
	.D(n_697),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer4_key_current_state_reg[0]  (.Q(floor_call_debouncer4_key_current_state[0]),
	.QN(UNCONNECTED6),
	.CK(CTS_3),
	.D(n_692),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer5_key_current_state_reg[0]  (.Q(floor_call_debouncer5_key_current_state[0]),
	.QN(UNCONNECTED7),
	.CK(CTS_4),
	.D(n_695),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer6_key_current_state_reg[0]  (.Q(floor_call_debouncer6_key_current_state[0]),
	.QN(UNCONNECTED8),
	.CK(CTS_4),
	.D(n_700),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer7_key_current_state_reg[0]  (.Q(floor_call_debouncer7_key_current_state[0]),
	.QN(UNCONNECTED9),
	.CK(CTS_6),
	.D(n_702),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer8_key_current_state_reg[0]  (.Q(floor_call_debouncer8_key_current_state[0]),
	.QN(UNCONNECTED10),
	.CK(CTS_4),
	.D(n_693),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer9_key_current_state_reg[0]  (.Q(floor_call_debouncer9_key_current_state[0]),
	.QN(UNCONNECTED11),
	.CK(CTS_2),
	.D(n_690),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer10_key_current_state_reg[0]  (.Q(floor_call_debouncer10_key_current_state[0]),
	.QN(UNCONNECTED12),
	.CK(CTS_2),
	.D(n_675),
	.RN(reset_n));
   TLATX1 floor_logic_inst_direction_selector_reg (.Q(UNCONNECTED13),
	.QN(n_140),
	.D(n_742),
	.G(n_743));
   TLATX1 floor_logic_inst_door_close_allowed_reg (.Q(UNCONNECTED14),
	.QN(door_close_logic_check),
	.D(n_725),
	.G(n_735));
   TLATX1 floor_logic_inst_door_open_allowed_reg (.Q(UNCONNECTED15),
	.QN(door_open_logic_check),
	.D(n_726),
	.G(n_735));
   DFFRX1 \panel_debouncer0_key_current_state_reg[0]  (.Q(panel_debouncer0_key_current_state[0]),
	.QN(UNCONNECTED16),
	.CK(CTS_1),
	.D(n_703),
	.RN(reset_n));
   DFFRX1 \panel_debouncer1_key_current_state_reg[0]  (.Q(panel_debouncer1_key_current_state[0]),
	.QN(UNCONNECTED17),
	.CK(CTS_1),
	.D(n_696),
	.RN(reset_n));
   DFFRX1 \panel_debouncer2_key_current_state_reg[0]  (.Q(panel_debouncer2_key_current_state[0]),
	.QN(UNCONNECTED18),
	.CK(CTS_2),
	.D(n_688),
	.RN(reset_n));
   DFFRX1 \panel_debouncer3_key_current_state_reg[0]  (.Q(panel_debouncer3_key_current_state[0]),
	.QN(UNCONNECTED19),
	.CK(CTS_3),
	.D(n_691),
	.RN(reset_n));
   DFFRX1 \panel_debouncer4_key_current_state_reg[0]  (.Q(panel_debouncer4_key_current_state[0]),
	.QN(UNCONNECTED20),
	.CK(CTS_3),
	.D(n_676),
	.RN(reset_n));
   DFFRX1 \panel_debouncer5_key_current_state_reg[0]  (.Q(panel_debouncer5_key_current_state[0]),
	.QN(UNCONNECTED21),
	.CK(CTS_5),
	.D(n_699),
	.RN(reset_n));
   DFFRX1 \panel_debouncer6_key_current_state_reg[0]  (.Q(panel_debouncer6_key_current_state[0]),
	.QN(UNCONNECTED22),
	.CK(CTS_5),
	.D(n_673),
	.RN(reset_n));
   DFFRX1 \panel_debouncer7_key_current_state_reg[0]  (.Q(panel_debouncer7_key_current_state[0]),
	.QN(UNCONNECTED23),
	.CK(CTS_4),
	.D(n_672),
	.RN(reset_n));
   DFFRX1 \panel_debouncer8_key_current_state_reg[0]  (.Q(panel_debouncer8_key_current_state[0]),
	.QN(UNCONNECTED24),
	.CK(CTS_3),
	.D(n_694),
	.RN(reset_n));
   DFFRX1 \panel_debouncer9_key_current_state_reg[0]  (.Q(panel_debouncer9_key_current_state[0]),
	.QN(UNCONNECTED25),
	.CK(CTS_2),
	.D(n_674),
	.RN(reset_n));
   DFFRX1 \panel_debouncer10_key_current_state_reg[0]  (.Q(panel_debouncer10_key_current_state[0]),
	.QN(UNCONNECTED26),
	.CK(CTS_3),
	.D(n_698),
	.RN(reset_n));
   CLKINVX2 g11843 (.Y(direction_selector),
	.A(FE_OFN41_n_140));
   NAND2X2 g11844__2398 (.Y(n_743),
	.A(FE_OFN0_reset_n),
	.B(floor_logic_inst_n_4880));
   OR2X1 g11845__5107 (.Y(floor_logic_inst_n_4880),
	.A(floor_logic_inst_n_272),
	.B(floor_logic_inst_n_359));
   OAI211X1 g11846__6260 (.Y(n_742),
	.A0(n_728),
	.A1(n_741),
	.B0(FE_OFN0_reset_n),
	.C0(n_732));
   OAI21X1 g11847__4319 (.Y(floor_logic_inst_n_1371),
	.A0(FE_OFN60_elevator_control_output_0),
	.A1(floor_logic_inst_n_246),
	.B0(FE_OFN0_reset_n));
   NAND2X1 g11848__8428 (.Y(floor_logic_inst_n_359),
	.A(FE_OFN63_elevator_control_output_1),
	.B(floor_logic_inst_n_246));
   NAND2X1 g11849__5526 (.Y(floor_logic_inst_n_246),
	.A(n_730),
	.B(n_739));
   CLKINVX2 g11850 (.Y(n_741),
	.A(n_740));
   OAI21X1 g11851__6783 (.Y(n_740),
	.A0(n_731),
	.A1(n_738),
	.B0(n_730));
   NOR4X1 g11852__3680 (.Y(n_739),
	.A(elevator_fsm_inst_n_4141),
	.B(n_731),
	.C(n_733),
	.D(n_737));
   OAI221X1 g11853__1617 (.Y(n_738),
	.A0(elevator_floor_selector[1]),
	.A1(n_734),
	.B0(FE_OFN37_elevator_floor_selector_0),
	.B1(n_733),
	.C0(floor_logic_inst_n_4785));
   OAI211X1 g11854__2802 (.Y(n_737),
	.A0(elevator_floor_selector[1]),
	.A1(n_143),
	.B0(n_729),
	.C0(n_732));
   NAND2X1 g11855__1705 (.Y(FE_OFN65_door_open),
	.A(door_open_logic_check),
	.B(n_736));
   NAND2X1 g11856__5122 (.Y(n_736),
	.A(door_close_logic_check),
	.B(FE_OFN63_elevator_control_output_1));
   CLKINVX2 g11859 (.Y(floor_logic_inst_n_4842),
	.A(n_734));
   NOR2X1 g11860__8246 (.Y(n_734),
	.A(FE_OFN34_elevator_control_output_7),
	.B(FE_OFN57_elevator_control_output_8));
   NAND2X1 g11861__7098 (.Y(floor_logic_inst_n_4785),
	.A(FE_OFN34_elevator_control_output_7),
	.B(FE_OFN57_elevator_control_output_8));
   AND2X1 g11862__6131 (.Y(n_733),
	.A(n_143),
	.B(elevator_floor_selector[1]));
   INVX2 g11863 (.Y(n_729),
	.A(n_728));
   NAND2X1 g11864__1881 (.Y(n_732),
	.A(elevator_floor_selector[3]),
	.B(FE_OFN53_n_44));
   NOR2X1 g11865__5115 (.Y(n_731),
	.A(elevator_floor_selector[2]),
	.B(n_724));
   NAND2X1 g11866__7482 (.Y(n_730),
	.A(elevator_floor_selector[2]),
	.B(n_724));
   NOR2X1 g11867__4733 (.Y(n_728),
	.A(elevator_floor_selector[3]),
	.B(FE_OFN53_n_44));
   CLKINVX2 g11868 (.Y(FE_OFN57_elevator_control_output_8),
	.A(n_143));
   NOR2X1 g11869__6161 (.Y(n_726),
	.A(n_708),
	.B(floor_logic_inst_n_385));
   NOR2X1 g11870__9315 (.Y(n_725),
	.A(n_709),
	.B(floor_logic_inst_n_385));
   NAND2X2 g11871__9945 (.Y(n_735),
	.A(reset_n),
	.B(floor_logic_inst_n_385));
   NOR2X2 g11872__2883 (.Y(n_143),
	.A(n_717),
	.B(n_722));
   CLKINVX2 g11873 (.Y(FE_OFN31_elevator_control_output_9),
	.A(n_724));
   NOR2X1 g11874__2346 (.Y(n_724),
	.A(n_706),
	.B(n_720));
   NAND2X1 g11875__1666 (.Y(floor_logic_inst_n_385),
	.A(raw_power_switch),
	.B(FE_OFN63_elevator_control_output_1));
   CLKINVX2 g11876 (.Y(FE_OFN55_elevator_control_output_10),
	.A(FE_OFN53_n_44));
   OAI221X1 g11877__7410 (.Y(n_722),
	.A0(FE_OFN38_elevator_fsm_inst_counter_state_1__1627),
	.A1(n_713),
	.B0(n_683),
	.B1(n_680),
	.C0(n_718));
   AOI211X1 g11878__6417 (.Y(n_44),
	.A0(n_682),
	.A1(n_712),
	.B0(n_716),
	.C0(FE_OFN47_alarm));
   NAND2X2 g11880__5477 (.Y(FE_OFN59_elevator_control_output_0),
	.A(elevator_fsm_inst_n_3955),
	.B(n_719));
   MX2X1 g11881__2398 (.Y(n_720),
	.A(n_710),
	.B(n_704),
	.S0(FE_OFN39_elevator_fsm_inst_counter_state_2__1628));
   NOR2X1 g11882__5107 (.Y(n_719),
	.A(n_715),
	.B(FE_OFN47_alarm));
   OAI21X1 g11883__6260 (.Y(n_718),
	.A0(n_685),
	.A1(n_705),
	.B0(FE_OFN38_elevator_fsm_inst_counter_state_1__1627));
   NAND2X1 g11884__4319 (.Y(FE_OFN51_elevator_control_output_2),
	.A(n_713),
	.B(n_711));
   OAI21X2 g11885__8428 (.Y(FE_OFN45_elevator_control_output_3),
	.A0(n_683),
	.A1(n_706),
	.B0(n_714));
   OAI22X1 g11886__5526 (.Y(n_717),
	.A0(\elevator_fsm_inst_counter_state[3]_1629 ),
	.A1(n_707),
	.B0(n_45),
	.B1(n_687));
   NOR3X1 g11887__6783 (.Y(n_716),
	.A(elevator_fsm_inst_n_3927),
	.B(FE_OFN39_elevator_fsm_inst_counter_state_2__1628),
	.C(n_679));
   AND3X2 g11888__3680 (.Y(n_715),
	.A(n_45),
	.B(n_2),
	.C(n_680));
   NAND3X1 g11889__1617 (.Y(n_714),
	.A(n_687),
	.B(FE_OFN39_elevator_fsm_inst_counter_state_2__1628),
	.C(n_682));
   NOR2X2 g11890__2802 (.Y(FE_OFN47_alarm),
	.A(n_683),
	.B(n_707));
   MX2X1 g11891__1705 (.Y(n_712),
	.A(n_680),
	.B(FE_OFN38_elevator_fsm_inst_counter_state_1__1627),
	.S0(n_2));
   AOI22X1 g11892__5122 (.Y(n_711),
	.A0(n_682),
	.A1(n_686),
	.B0(n_679),
	.B1(n_684));
   OAI22X1 g11893__8246 (.Y(n_710),
	.A0(FE_OFN34_elevator_control_output_7),
	.A1(n_683),
	.B0(FE_OFN38_elevator_fsm_inst_counter_state_1__1627),
	.B1(n_45));
   MX2X1 g11894__7098 (.Y(n_713),
	.A(elevator_fsm_inst_n_3927),
	.B(n_681),
	.S0(n_2));
   CLKINVX1 g11895 (.Y(n_709),
	.A(door_close_btn));
   CLKINVX1 g11896 (.Y(n_708),
	.A(door_open_btn));
   CLKINVX2 g11911 (.Y(n_706),
	.A(n_707));
   NOR3X1 g11923__6131 (.Y(n_705),
	.A(FE_OFN11_elevator_fsm_inst_counter_state_4__1630),
	.B(FE_OFN34_elevator_control_output_7),
	.C(FE_OFN39_elevator_fsm_inst_counter_state_2__1628));
   OAI21X1 g11924__1881 (.Y(n_704),
	.A0(FE_OFN11_elevator_fsm_inst_counter_state_4__1630),
	.A1(n_122),
	.B0(elevator_fsm_inst_n_3955));
   CLKXOR2X1 g11925__5115 (.Y(elevator_fsm_inst_n_4141),
	.A(FE_OFN37_elevator_floor_selector_0),
	.B(FE_OFN34_elevator_control_output_7));
   NAND2X1 g11926__7482 (.Y(n_707),
	.A(FE_OFN39_elevator_fsm_inst_counter_state_2__1628),
	.B(n_679));
   NOR2X1 g11927__4733 (.Y(n_703),
	.A(n_650),
	.B(panel_buttons[0]));
   NOR2X1 g11928__6161 (.Y(n_702),
	.A(n_667),
	.B(floor_call_buttons[7]));
   NOR2X1 g11929__9315 (.Y(n_701),
	.A(n_656),
	.B(FE_OFN2_n_25));
   NOR2X1 g11930__9945 (.Y(n_700),
	.A(n_665),
	.B(floor_call_buttons[6]));
   NOR2X1 g11931__2883 (.Y(n_699),
	.A(n_651),
	.B(panel_buttons[5]));
   NOR2X1 g11932__2346 (.Y(n_698),
	.A(n_655),
	.B(panel_buttons[10]));
   NOR2X1 g11933__1666 (.Y(n_697),
	.A(n_666),
	.B(floor_call_buttons[3]));
   NOR2X1 g11934__7410 (.Y(n_696),
	.A(n_658),
	.B(panel_buttons[1]));
   NOR2X1 g11935__6417 (.Y(n_695),
	.A(n_654),
	.B(floor_call_buttons[5]));
   NOR2X1 g11936__5477 (.Y(n_694),
	.A(n_663),
	.B(panel_buttons[8]));
   NOR2X1 g11937__2398 (.Y(n_693),
	.A(n_669),
	.B(floor_call_buttons[8]));
   NOR2X1 g11938__5107 (.Y(n_692),
	.A(n_657),
	.B(floor_call_buttons[4]));
   NOR2X1 g11939__6260 (.Y(n_691),
	.A(n_652),
	.B(panel_buttons[3]));
   NOR2X1 g11940__4319 (.Y(n_690),
	.A(n_653),
	.B(floor_call_buttons[9]));
   NOR2X1 g11941__8428 (.Y(n_689),
	.A(n_647),
	.B(floor_call_buttons[2]));
   NOR2X1 g11942__5526 (.Y(n_688),
	.A(n_662),
	.B(panel_buttons[2]));
   INVX2 g11943 (.Y(n_687),
	.A(n_686));
   CLKINVX2 g11944 (.Y(elevator_fsm_inst_n_3955),
	.A(n_685));
   CLKINVX1 g11945 (.Y(n_684),
	.A(elevator_fsm_inst_n_3927));
   CLKINVX2 g11947 (.Y(n_679),
	.A(n_680));
   NOR2X1 g11948__6783 (.Y(n_678),
	.A(raw_door_close_btn),
	.B(n_649));
   NOR2X1 g11949__3680 (.Y(n_677),
	.A(n_648),
	.B(floor_call_buttons[1]));
   NOR2X1 g11950__1617 (.Y(n_676),
	.A(n_659),
	.B(panel_buttons[4]));
   NOR2X1 g11951__2802 (.Y(n_675),
	.A(n_668),
	.B(floor_call_buttons[10]));
   NOR2X1 g11952__1705 (.Y(n_674),
	.A(n_661),
	.B(panel_buttons[9]));
   NOR2X1 g11953__5122 (.Y(n_673),
	.A(n_664),
	.B(panel_buttons[6]));
   NOR2X1 g11954__8246 (.Y(n_672),
	.A(n_645),
	.B(panel_buttons[7]));
   NOR2X1 g11955__7098 (.Y(n_671),
	.A(raw_door_open_btn),
	.B(n_660));
   NOR2X1 g11956__6131 (.Y(n_670),
	.A(n_646),
	.B(floor_call_buttons[0]));
   NAND2X2 g11957__1881 (.Y(floor_logic_inst_n_272),
	.A(raw_power_switch),
	.B(n_25));
   NOR2X1 g11958__5115 (.Y(n_686),
	.A(FE_OFN38_elevator_fsm_inst_counter_state_1__1627),
	.B(FE_OFN34_elevator_control_output_7));
   NOR2X1 g11959__7482 (.Y(n_685),
	.A(FE_OFN11_elevator_fsm_inst_counter_state_4__1630),
	.B(\elevator_fsm_inst_counter_state[3]_1629 ));
   NAND2X1 g11960__4733 (.Y(elevator_fsm_inst_n_3927),
	.A(\elevator_fsm_inst_counter_state[3]_1629 ),
	.B(n_45));
   NAND2X1 g11961__6161 (.Y(n_683),
	.A(FE_OFN11_elevator_fsm_inst_counter_state_4__1630),
	.B(\elevator_fsm_inst_counter_state[3]_1629 ));
   NOR2X1 g11962__9315 (.Y(n_682),
	.A(\elevator_fsm_inst_counter_state[3]_1629 ),
	.B(n_45));
   NAND2X1 g11963__9945 (.Y(n_680),
	.A(FE_OFN38_elevator_fsm_inst_counter_state_1__1627),
	.B(FE_OFN34_elevator_control_output_7));
   CLKINVX2 g11964 (.Y(n_669),
	.A(raw_floor_call_buttons[8]));
   CLKINVX2 g11965 (.Y(n_668),
	.A(raw_floor_call_buttons[10]));
   CLKINVX2 g11966 (.Y(n_667),
	.A(raw_floor_call_buttons[7]));
   CLKINVX2 g11967 (.Y(n_666),
	.A(raw_floor_call_buttons[3]));
   CLKINVX2 g11968 (.Y(n_665),
	.A(raw_floor_call_buttons[6]));
   CLKINVX2 g11969 (.Y(n_664),
	.A(raw_panel_buttons[6]));
   CLKINVX2 g11970 (.Y(n_663),
	.A(raw_panel_buttons[8]));
   CLKINVX2 g11971 (.Y(n_662),
	.A(raw_panel_buttons[2]));
   CLKINVX2 g11972 (.Y(n_661),
	.A(raw_panel_buttons[9]));
   CLKINVX1 g11973 (.Y(n_660),
	.A(door_open_debouncer_key_current_state[0]));
   CLKINVX2 g11974 (.Y(n_659),
	.A(raw_panel_buttons[4]));
   CLKINVX2 g11975 (.Y(n_658),
	.A(raw_panel_buttons[1]));
   CLKINVX2 g11976 (.Y(n_657),
	.A(raw_floor_call_buttons[4]));
   CLKINVX2 g11977 (.Y(n_656),
	.A(raw_emergency_btn));
   CLKINVX2 g11978 (.Y(n_655),
	.A(raw_panel_buttons[10]));
   CLKINVX2 g11979 (.Y(n_654),
	.A(raw_floor_call_buttons[5]));
   CLKINVX2 g11980 (.Y(n_653),
	.A(raw_floor_call_buttons[9]));
   CLKINVX2 g11981 (.Y(n_652),
	.A(raw_panel_buttons[3]));
   CLKINVX2 g11982 (.Y(n_651),
	.A(raw_panel_buttons[5]));
   CLKINVX2 g11983 (.Y(n_650),
	.A(raw_panel_buttons[0]));
   CLKINVX1 g11984 (.Y(n_649),
	.A(door_close_debouncer_key_current_state[0]));
   CLKINVX2 g11985 (.Y(n_648),
	.A(raw_floor_call_buttons[1]));
   CLKINVX2 g11986 (.Y(n_647),
	.A(raw_floor_call_buttons[2]));
   CLKINVX2 g11987 (.Y(n_646),
	.A(raw_floor_call_buttons[0]));
   CLKINVX2 g11988 (.Y(n_645),
	.A(raw_panel_buttons[7]));
   DFFRX1 \door_close_debouncer_key_current_state_reg[0]  (.Q(door_close_debouncer_key_current_state[0]),
	.QN(UNCONNECTED27),
	.CK(CTS_3),
	.D(n_274),
	.RN(reset_n));
   DFFRX1 \door_open_debouncer_key_current_state_reg[0]  (.Q(door_open_debouncer_key_current_state[0]),
	.QN(UNCONNECTED28),
	.CK(CTS_3),
	.D(n_271),
	.RN(reset_n));
   DFFRX1 \elevator_fsm_inst_counter_state_reg[0]  (.Q(FE_OFN33_elevator_control_output_7),
	.QN(UNCONNECTED29),
	.CK(CTS_7),
	.D(n_633),
	.RN(FE_OFN0_reset_n));
   DFFRX1 \elevator_fsm_inst_counter_state_reg[1]  (.Q(\elevator_fsm_inst_counter_state[1]_1627 ),
	.QN(UNCONNECTED30),
	.CK(CTS_7),
	.D(n_623),
	.RN(FE_OFN0_reset_n));
   DFFRX1 \elevator_fsm_inst_counter_state_reg[2]  (.Q(\elevator_fsm_inst_counter_state[2]_1628 ),
	.QN(UNCONNECTED31),
	.CK(CTS_7),
	.D(n_638),
	.RN(FE_OFN0_reset_n));
   DFFRX4 \elevator_fsm_inst_counter_state_reg[3]  (.Q(\elevator_fsm_inst_counter_state[3]_1629 ),
	.QN(UNCONNECTED32),
	.CK(CTS_7),
	.D(n_636),
	.RN(FE_OFN0_reset_n));
   DFFRX1 \elevator_fsm_inst_counter_state_reg[4]  (.Q(\elevator_fsm_inst_counter_state[4]_1630 ),
	.QN(UNCONNECTED33),
	.CK(CTS_7),
	.D(n_627),
	.RN(FE_OFN0_reset_n));
   DFFRX1 \emergency_debouncer_key_current_state_reg[1]  (.Q(UNCONNECTED34),
	.QN(n_25),
	.CK(CTS_1),
	.D(n_263),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer0_key_current_state_reg[1]  (.Q(floor_call_buttons[0]),
	.QN(UNCONNECTED35),
	.CK(CTS_1),
	.D(n_260),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer1_key_current_state_reg[1]  (.Q(floor_call_buttons[1]),
	.QN(UNCONNECTED36),
	.CK(CTS_1),
	.D(n_254),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer2_key_current_state_reg[1]  (.Q(floor_call_buttons[2]),
	.QN(UNCONNECTED37),
	.CK(CTS_3),
	.D(n_272),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer3_key_current_state_reg[1]  (.Q(floor_call_buttons[3]),
	.QN(UNCONNECTED38),
	.CK(CTS_5),
	.D(n_265),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer4_key_current_state_reg[1]  (.Q(floor_call_buttons[4]),
	.QN(UNCONNECTED39),
	.CK(CTS_5),
	.D(n_268),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer5_key_current_state_reg[1]  (.Q(floor_call_buttons[5]),
	.QN(UNCONNECTED40),
	.CK(CTS_4),
	.D(n_281),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer6_key_current_state_reg[1]  (.Q(floor_call_buttons[6]),
	.QN(UNCONNECTED41),
	.CK(CTS_4),
	.D(n_266),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer7_key_current_state_reg[1]  (.Q(floor_call_buttons[7]),
	.QN(UNCONNECTED42),
	.CK(CTS_6),
	.D(n_279),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer8_key_current_state_reg[1]  (.Q(floor_call_buttons[8]),
	.QN(UNCONNECTED43),
	.CK(CTS_4),
	.D(n_278),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer9_key_current_state_reg[1]  (.Q(floor_call_buttons[9]),
	.QN(UNCONNECTED44),
	.CK(CTS_1),
	.D(n_277),
	.RN(reset_n));
   DFFRX1 \floor_call_debouncer10_key_current_state_reg[1]  (.Q(floor_call_buttons[10]),
	.QN(UNCONNECTED45),
	.CK(CTS_2),
	.D(n_280),
	.RN(reset_n));
   DFFRX1 \floor_logic_inst_call_button_lights_reg[0]  (.Q(FE_OFN15_call_button_lights_0),
	.QN(UNCONNECTED46),
	.CK(CTS_7),
	.D(n_463),
	.RN(reset_n));
   DFFRX1 \floor_logic_inst_call_button_lights_reg[1]  (.Q(FE_OFN13_call_button_lights_1),
	.QN(UNCONNECTED47),
	.CK(CTS_7),
	.D(n_547),
	.RN(FE_OFN0_reset_n));
   DFFRX1 \floor_logic_inst_call_button_lights_reg[2]  (.Q(FE_OFN12_call_button_lights_2),
	.QN(UNCONNECTED48),
	.CK(CTS_5),
	.D(n_572),
	.RN(reset_n));
   DFFRX1 \floor_logic_inst_call_button_lights_reg[3]  (.Q(FE_OFN11_call_button_lights_3),
	.QN(UNCONNECTED49),
	.CK(CTS_7),
	.D(n_550),
	.RN(reset_n));
   DFFRX1 \floor_logic_inst_call_button_lights_reg[4]  (.Q(FE_OFN10_call_button_lights_4),
	.QN(UNCONNECTED50),
	.CK(CTS_5),
	.D(n_584),
	.RN(reset_n));
   DFFRX1 \floor_logic_inst_call_button_lights_reg[5]  (.Q(FE_OFN8_call_button_lights_5),
	.QN(UNCONNECTED51),
	.CK(CTS_4),
	.D(n_603),
	.RN(reset_n));
   DFFRX1 \floor_logic_inst_call_button_lights_reg[6]  (.Q(FE_OFN7_call_button_lights_6),
	.QN(UNCONNECTED52),
	.CK(CTS_6),
	.D(n_612),
	.RN(reset_n));
   DFFRX1 \floor_logic_inst_call_button_lights_reg[7]  (.Q(FE_OFN5_call_button_lights_7),
	.QN(UNCONNECTED53),
	.CK(CTS_6),
	.D(n_614),
	.RN(reset_n));
   DFFRX1 \floor_logic_inst_call_button_lights_reg[8]  (.Q(FE_OFN4_call_button_lights_8),
	.QN(UNCONNECTED54),
	.CK(CTS_6),
	.D(n_630),
	.RN(reset_n));
   DFFRX1 \floor_logic_inst_call_button_lights_reg[9]  (.Q(FE_OFN3_call_button_lights_9),
	.QN(UNCONNECTED55),
	.CK(CTS_6),
	.D(n_634),
	.RN(reset_n));
   DFFRX1 \floor_logic_inst_call_button_lights_reg[10]  (.Q(FE_OFN1_call_button_lights_10),
	.QN(UNCONNECTED56),
	.CK(CTS_6),
	.D(n_635),
	.RN(reset_n));
   TLATX1 \floor_logic_inst_elevator_floor_selector_reg[0]  (.Q(elevator_floor_selector[0]),
	.QN(UNCONNECTED57),
	.D(n_639),
	.G(FE_OFN66_floor_logic_inst_n_1371));
   TLATX1 \floor_logic_inst_elevator_floor_selector_reg[1]  (.Q(elevator_floor_selector[1]),
	.QN(UNCONNECTED58),
	.D(n_637),
	.G(FE_OFN66_floor_logic_inst_n_1371));
   TLATX1 \floor_logic_inst_elevator_floor_selector_reg[2]  (.Q(elevator_floor_selector[2]),
	.QN(UNCONNECTED59),
	.D(n_628),
	.G(FE_OFN66_floor_logic_inst_n_1371));
   TLATX1 \floor_logic_inst_elevator_floor_selector_reg[3]  (.Q(elevator_floor_selector[3]),
	.QN(UNCONNECTED60),
	.D(n_622),
	.G(FE_OFN66_floor_logic_inst_n_1371));
   DFFRX1 \floor_logic_inst_panel_button_lights_reg[0]  (.Q(FE_OFN29_panel_button_lights_0),
	.QN(UNCONNECTED61),
	.CK(CTS_7),
	.D(n_464),
	.RN(reset_n));
   DFFRX1 \floor_logic_inst_panel_button_lights_reg[1]  (.Q(FE_OFN27_panel_button_lights_1),
	.QN(UNCONNECTED62),
	.CK(CTS_7),
	.D(n_546),
	.RN(reset_n));
   DFFRX1 \floor_logic_inst_panel_button_lights_reg[2]  (.Q(FE_OFN26_panel_button_lights_2),
	.QN(UNCONNECTED63),
	.CK(CTS_2),
	.D(n_571),
	.RN(reset_n));
   DFFRX1 \floor_logic_inst_panel_button_lights_reg[3]  (.Q(FE_OFN25_panel_button_lights_3),
	.QN(UNCONNECTED64),
	.CK(CTS_7),
	.D(n_555),
	.RN(reset_n));
   DFFRX1 \floor_logic_inst_panel_button_lights_reg[4]  (.Q(FE_OFN24_panel_button_lights_4),
	.QN(UNCONNECTED65),
	.CK(CTS_5),
	.D(n_583),
	.RN(reset_n));
   DFFRX1 \floor_logic_inst_panel_button_lights_reg[5]  (.Q(FE_OFN22_panel_button_lights_5),
	.QN(UNCONNECTED66),
	.CK(CTS_4),
	.D(n_602),
	.RN(reset_n));
   DFFRX1 \floor_logic_inst_panel_button_lights_reg[6]  (.Q(FE_OFN21_panel_button_lights_6),
	.QN(UNCONNECTED67),
	.CK(CTS_6),
	.D(n_611),
	.RN(reset_n));
   DFFRX1 \floor_logic_inst_panel_button_lights_reg[7]  (.Q(FE_OFN19_panel_button_lights_7),
	.QN(UNCONNECTED68),
	.CK(CTS_6),
	.D(n_615),
	.RN(reset_n));
   DFFRX1 \floor_logic_inst_panel_button_lights_reg[8]  (.Q(FE_OFN18_panel_button_lights_8),
	.QN(UNCONNECTED69),
	.CK(CTS_6),
	.D(n_621),
	.RN(reset_n));
   DFFRX1 \floor_logic_inst_panel_button_lights_reg[9]  (.Q(FE_OFN17_panel_button_lights_9),
	.QN(UNCONNECTED70),
	.CK(CTS_6),
	.D(n_625),
	.RN(reset_n));
   DFFRX1 \floor_logic_inst_panel_button_lights_reg[10]  (.Q(FE_OFN16_panel_button_lights_10),
	.QN(UNCONNECTED71),
	.CK(CTS_6),
	.D(n_620),
	.RN(reset_n));
   DFFRX1 \panel_debouncer0_key_current_state_reg[1]  (.Q(panel_buttons[0]),
	.QN(UNCONNECTED72),
	.CK(CTS_1),
	.D(n_257),
	.RN(reset_n));
   DFFRX1 \panel_debouncer1_key_current_state_reg[1]  (.Q(panel_buttons[1]),
	.QN(UNCONNECTED73),
	.CK(CTS_1),
	.D(n_261),
	.RN(reset_n));
   DFFRX1 \panel_debouncer2_key_current_state_reg[1]  (.Q(panel_buttons[2]),
	.QN(UNCONNECTED74),
	.CK(CTS_2),
	.D(n_275),
	.RN(reset_n));
   DFFRX1 \panel_debouncer3_key_current_state_reg[1]  (.Q(panel_buttons[3]),
	.QN(UNCONNECTED75),
	.CK(CTS_3),
	.D(n_255),
	.RN(reset_n));
   DFFRX1 \panel_debouncer4_key_current_state_reg[1]  (.Q(panel_buttons[4]),
	.QN(UNCONNECTED76),
	.CK(CTS_2),
	.D(n_270),
	.RN(reset_n));
   DFFRX1 \panel_debouncer5_key_current_state_reg[1]  (.Q(panel_buttons[5]),
	.QN(UNCONNECTED77),
	.CK(CTS_5),
	.D(n_256),
	.RN(reset_n));
   DFFRX1 \panel_debouncer6_key_current_state_reg[1]  (.Q(panel_buttons[6]),
	.QN(UNCONNECTED78),
	.CK(CTS_5),
	.D(n_273),
	.RN(reset_n));
   DFFRX1 \panel_debouncer7_key_current_state_reg[1]  (.Q(panel_buttons[7]),
	.QN(UNCONNECTED79),
	.CK(CTS_4),
	.D(n_262),
	.RN(reset_n));
   DFFRX1 \panel_debouncer8_key_current_state_reg[1]  (.Q(panel_buttons[8]),
	.QN(UNCONNECTED80),
	.CK(CTS_3),
	.D(n_259),
	.RN(reset_n));
   DFFRX1 \panel_debouncer9_key_current_state_reg[1]  (.Q(panel_buttons[9]),
	.QN(UNCONNECTED81),
	.CK(CTS_2),
	.D(n_264),
	.RN(reset_n));
   DFFRX1 \panel_debouncer10_key_current_state_reg[1]  (.Q(panel_buttons[10]),
	.QN(UNCONNECTED82),
	.CK(CTS_1),
	.D(n_269),
	.RN(reset_n));
   OAI222X1 g16314__2883 (.Y(n_639),
	.A0(n_556),
	.A1(n_598),
	.B0(n_251),
	.B1(n_629),
	.C0(n_91),
	.C1(n_567));
   OAI221X1 g16316__2346 (.Y(n_638),
	.A0(elevator_fsm_inst_n_3955),
	.A1(n_471),
	.B0(FE_OFN38_elevator_fsm_inst_counter_state_1__1627),
	.B1(n_561),
	.C0(n_632));
   OAI221X1 g16318__1666 (.Y(n_637),
	.A0(n_560),
	.A1(n_598),
	.B0(n_143),
	.B1(n_567),
	.C0(n_631));
   OAI222X1 g16319__7410 (.Y(n_636),
	.A0(n_45),
	.A1(n_619),
	.B0(elevator_fsm_inst_n_3927),
	.B1(n_551),
	.C0(elevator_fsm_inst_n_3955),
	.C1(n_509));
   MX2X1 g16322__6417 (.Y(n_635),
	.A(n_294),
	.B(FE_OFN1_call_button_lights_10),
	.S0(n_626));
   MX2X1 g16331__5477 (.Y(n_634),
	.A(n_360),
	.B(FE_OFN3_call_button_lights_9),
	.S0(n_616));
   OAI221X1 g16332__2398 (.Y(n_633),
	.A0(n_45),
	.A1(FE_OFN13_n_605),
	.B0(FE_OFN38_elevator_fsm_inst_counter_state_1__1627),
	.B1(n_537),
	.C0(n_581));
   AOI211X1 g16333__5107 (.Y(n_632),
	.A0(FE_OFN11_elevator_fsm_inst_counter_state_4__1630),
	.A1(n_558),
	.B0(FE_PDN15_n_618),
	.C0(n_590));
   OAI211X1 g16334__6260 (.Y(n_631),
	.A0(FE_OFN42_n_335),
	.A1(n_468),
	.B0(n_343),
	.C0(n_613));
   MX2X1 g16335__4319 (.Y(n_630),
	.A(FE_OFN4_call_button_lights_8),
	.B(n_404),
	.S0(n_617));
   OAI222X1 g16336__8428 (.Y(n_629),
	.A0(n_237),
	.A1(n_344),
	.B0(n_606),
	.B1(n_610),
	.C0(n_420),
	.C1(n_468));
   OAI21X1 g16337__5526 (.Y(n_628),
	.A0(n_521),
	.A1(n_598),
	.B0(n_624));
   OAI222X1 g16338__6783 (.Y(n_627),
	.A0(\elevator_fsm_inst_counter_state[3]_1629 ),
	.A1(n_596),
	.B0(FE_OFN11_elevator_fsm_inst_counter_state_4__1630),
	.B1(FE_OFN50_n_574),
	.C0(n_248),
	.C1(n_600));
   OAI21X1 g16339__3680 (.Y(n_626),
	.A0(n_295),
	.A1(n_604),
	.B0(n_400));
   MX2X1 g16344__1617 (.Y(n_625),
	.A(n_360),
	.B(FE_OFN17_panel_button_lights_9),
	.S0(n_608));
   AOI22X1 g16345__2802 (.Y(n_624),
	.A0(n_467),
	.A1(n_610),
	.B0(FE_OFN31_elevator_control_output_9),
	.B1(n_566));
   OAI222X1 g16346__1705 (.Y(n_623),
	.A0(n_45),
	.A1(n_586),
	.B0(FE_OFN11_elevator_fsm_inst_counter_state_4__1630),
	.B1(n_585),
	.C0(n_248),
	.C1(n_588));
   OAI222X1 g16347__5122 (.Y(n_622),
	.A0(n_489),
	.A1(n_591),
	.B0(n_499),
	.B1(n_598),
	.C0(FE_OFN53_n_44),
	.C1(n_567));
   MX2X1 g16348__8246 (.Y(n_621),
	.A(n_404),
	.B(FE_OFN18_panel_button_lights_8),
	.S0(n_607));
   MX2X1 g16349__7098 (.Y(n_620),
	.A(n_294),
	.B(FE_OFN16_panel_button_lights_10),
	.S0(n_601));
   AOI222X1 g16350__6131 (.Y(n_619),
	.A0(n_234),
	.A1(n_565),
	.B0(\elevator_fsm_inst_counter_state[3]_1629 ),
	.B1(FE_OFN54_n_599),
	.C0(n_229),
	.C1(n_536));
   AOI211X2 g16351__1881 (.Y(n_618),
	.A0(n_423),
	.A1(n_575),
	.B0(n_45),
	.C0(\elevator_fsm_inst_counter_state[3]_1629 ));
   AOI21X1 g16352__5115 (.Y(n_617),
	.A0(n_404),
	.A1(n_597),
	.B0(FE_OFN40_floor_logic_inst_n_272));
   OAI21X1 g16353__7482 (.Y(n_616),
	.A0(n_361),
	.A1(n_587),
	.B0(n_433));
   MX2X1 g16356__4733 (.Y(n_615),
	.A(n_363),
	.B(FE_OFN19_panel_button_lights_7),
	.S0(n_582));
   MX2X1 g16357__6161 (.Y(n_614),
	.A(n_363),
	.B(FE_OFN5_call_button_lights_7),
	.S0(n_595));
   OAI21X1 g16358__9315 (.Y(n_613),
	.A0(n_340),
	.A1(n_591),
	.B0(n_609));
   MX2X1 g16359__9945 (.Y(n_612),
	.A(FE_OFN7_call_button_lights_6),
	.B(n_368),
	.S0(n_594));
   MX2X1 g16360__2883 (.Y(n_611),
	.A(FE_OFN21_panel_button_lights_6),
	.B(n_368),
	.S0(n_593));
   CLKINVX2 g16361 (.Y(n_610),
	.A(n_609));
   OAI21X1 g16362__2346 (.Y(n_608),
	.A0(n_361),
	.A1(n_576),
	.B0(n_433));
   NAND2X1 g16363__1666 (.Y(n_607),
	.A(n_139),
	.B(n_589));
   NAND2X1 g16364__7410 (.Y(n_609),
	.A(n_489),
	.B(n_592));
   AND3X2 g16367__6417 (.Y(n_606),
	.A(n_235),
	.B(n_340),
	.C(n_592));
   AOI222X1 g16368__5477 (.Y(n_605),
	.A0(n_234),
	.A1(n_503),
	.B0(\elevator_fsm_inst_counter_state[3]_1629 ),
	.B1(n_548),
	.C0(n_229),
	.C1(n_531));
   AND4X1 g16369__2398 (.Y(n_604),
	.A(floor_call_buttons[10]),
	.B(n_381),
	.C(n_452),
	.D(n_578));
   MX2X1 g16370__5107 (.Y(n_603),
	.A(n_332),
	.B(FE_OFN8_call_button_lights_5),
	.S0(n_580));
   MX2X1 g16371__6260 (.Y(n_602),
	.A(n_332),
	.B(FE_OFN22_panel_button_lights_5),
	.S0(n_579));
   OAI21X1 g16372__4319 (.Y(n_601),
	.A0(n_295),
	.A1(n_573),
	.B0(n_400));
   NAND2X1 g16374__8428 (.Y(n_597),
	.A(n_451),
	.B(n_578));
   OAI21X1 g16375__5526 (.Y(n_596),
	.A0(n_212),
	.A1(n_549),
	.B0(FE_OFN11_elevator_fsm_inst_counter_state_4__1630));
   OAI21X1 g16376__6783 (.Y(n_595),
	.A0(n_362),
	.A1(n_554),
	.B0(n_435));
   AOI221X1 g16377__3680 (.Y(n_599),
	.A0(n_241),
	.A1(n_394),
	.B0(n_36),
	.B1(n_222),
	.C0(n_577));
   AOI21X1 g16378__1617 (.Y(n_594),
	.A0(n_368),
	.A1(n_564),
	.B0(FE_OFN40_floor_logic_inst_n_272));
   AOI21X1 g16379__2802 (.Y(n_593),
	.A0(n_368),
	.A1(n_563),
	.B0(FE_OFN40_floor_logic_inst_n_272));
   OAI21X2 g16380__1705 (.Y(n_598),
	.A0(n_495),
	.A1(n_570),
	.B0(FE_OFN0_reset_n));
   NOR4X1 g16384__5122 (.Y(n_590),
	.A(elevator_fsm_inst_n_3927),
	.B(n_430),
	.C(FE_OFN44_n_470),
	.D(n_529));
   OAI21X1 g16385__8246 (.Y(n_589),
	.A0(n_453),
	.A1(n_569),
	.B0(n_404));
   AOI221X1 g16386__7098 (.Y(n_588),
	.A0(n_122),
	.A1(n_494),
	.B0(n_241),
	.B1(n_454),
	.C0(n_545));
   AND3X2 g16387__6131 (.Y(n_587),
	.A(floor_call_buttons[9]),
	.B(n_452),
	.C(n_578));
   AOI22X1 g16388__1881 (.Y(n_586),
	.A0(n_229),
	.A1(n_562),
	.B0(n_234),
	.B1(n_492));
   AOI211X1 g16389__5115 (.Y(n_585),
	.A0(\elevator_fsm_inst_counter_state[3]_1629 ),
	.A1(n_507),
	.B0(n_510),
	.C0(n_552));
   MX2X1 g16390__7482 (.Y(n_584),
	.A(FE_OFN10_call_button_lights_4),
	.B(n_369),
	.S0(n_557));
   MX2X1 g16391__4733 (.Y(n_583),
	.A(FE_OFN24_panel_button_lights_4),
	.B(n_369),
	.S0(n_544));
   OAI21X1 g16392__6161 (.Y(n_582),
	.A0(n_362),
	.A1(n_553),
	.B0(n_435));
   NOR3X1 g16393__9315 (.Y(n_592),
	.A(n_0),
	.B(n_533),
	.C(n_570));
   AOI21X1 g16394__9945 (.Y(n_581),
	.A0(n_45),
	.A1(n_538),
	.B0(n_559));
   OAI21X1 g16395__2883 (.Y(n_580),
	.A0(n_333),
	.A1(n_540),
	.B0(n_456));
   OAI21X1 g16396__2346 (.Y(n_579),
	.A0(n_333),
	.A1(n_539),
	.B0(n_456));
   OAI221X1 g16401__1666 (.Y(n_577),
	.A0(n_122),
	.A1(n_528),
	.B0(FE_OFN38_elevator_fsm_inst_counter_state_1__1627),
	.B1(n_442),
	.C0(n_329));
   AND3X2 g16402__7410 (.Y(n_576),
	.A(panel_buttons[9]),
	.B(n_453),
	.C(n_568));
   AOI221X1 g16403__6417 (.Y(n_575),
	.A0(n_236),
	.A1(n_215),
	.B0(FE_OFN38_elevator_fsm_inst_counter_state_1__1627),
	.B1(n_508),
	.C0(n_497));
   AOI222X1 g16404__5477 (.Y(n_574),
	.A0(n_229),
	.A1(n_496),
	.B0(n_234),
	.B1(n_419),
	.C0(\elevator_fsm_inst_counter_state[3]_1629 ),
	.C1(n_530));
   NOR2X1 g16405__2398 (.Y(n_573),
	.A(n_472),
	.B(n_569));
   MX2X1 g16406__5107 (.Y(n_572),
	.A(n_365),
	.B(FE_OFN12_call_button_lights_2),
	.S0(n_534));
   MX2X1 g16407__6260 (.Y(n_571),
	.A(n_365),
	.B(FE_OFN26_panel_button_lights_2),
	.S0(n_525));
   NOR3X1 g16408__4319 (.Y(n_578),
	.A(n_330),
	.B(n_406),
	.C(n_542));
   INVX2 g16409 (.Y(n_568),
	.A(n_569));
   CLKINVX2 g16410 (.Y(n_566),
	.A(n_567));
   OR3X1 g16411__8428 (.Y(n_565),
	.A(n_313),
	.B(n_382),
	.C(n_504));
   NAND2X1 g16412__5526 (.Y(n_564),
	.A(n_406),
	.B(n_541));
   NAND2X1 g16413__6783 (.Y(n_563),
	.A(n_409),
	.B(n_543));
   OR2X1 g16414__3680 (.Y(n_562),
	.A(n_307),
	.B(n_526));
   OR2X1 g16415__1617 (.Y(n_561),
	.A(n_248),
	.B(n_535));
   OAI221X1 g16416__2802 (.Y(n_560),
	.A0(n_458),
	.A1(n_499),
	.B0(n_428),
	.B1(n_477),
	.C0(n_405));
   AOI21X1 g16417__1705 (.Y(n_559),
	.A0(emergency_btn),
	.A1(n_506),
	.B0(elevator_fsm_inst_n_3955));
   AOI21X1 g16418__5122 (.Y(n_558),
	.A0(n_231),
	.A1(n_518),
	.B0(n_239));
   AOI21X1 g16419__8246 (.Y(n_557),
	.A0(n_369),
	.A1(n_517),
	.B0(floor_logic_inst_n_272));
   AOI21X1 g16420__7098 (.Y(n_570),
	.A0(n_428),
	.A1(n_519),
	.B0(FE_OFN51_elevator_control_output_2));
   OAI211X1 g16421__6131 (.Y(n_569),
	.A0(FE_OFN19_panel_button_lights_7),
	.A1(n_357),
	.B0(n_410),
	.C0(n_543));
   NAND2X1 g16422__1881 (.Y(n_567),
	.A(FE_OFN0_reset_n),
	.B(n_533));
   OAI221X1 g16423__5115 (.Y(n_556),
	.A0(n_440),
	.A1(n_499),
	.B0(n_480),
	.B1(n_477),
	.C0(n_441));
   OAI22X1 g16424__7482 (.Y(n_555),
	.A0(floor_logic_inst_n_272),
	.A1(n_520),
	.B0(n_145),
	.B1(n_397));
   NOR3X1 g16425__4733 (.Y(n_554),
	.A(n_176),
	.B(n_406),
	.C(n_542));
   AND3X2 g16426__6161 (.Y(n_553),
	.A(panel_buttons[7]),
	.B(n_410),
	.C(n_543));
   AOI221X1 g16427__9315 (.Y(n_552),
	.A0(n_437),
	.A1(n_485),
	.B0(FE_OFN38_elevator_fsm_inst_counter_state_1__1627),
	.B1(n_326),
	.C0(\elevator_fsm_inst_counter_state[3]_1629 ));
   OR2X1 g16428__9945 (.Y(n_551),
	.A(n_430),
	.B(n_532));
   OAI22X1 g16429__2883 (.Y(n_550),
	.A0(floor_logic_inst_n_272),
	.A1(n_516),
	.B0(n_61),
	.B1(n_397));
   OAI21X1 g16430__2346 (.Y(n_549),
	.A0(n_122),
	.A1(n_398),
	.B0(n_527));
   OAI222X1 g16431__1666 (.Y(n_548),
	.A0(FE_OFN38_elevator_fsm_inst_counter_state_1__1627),
	.A1(n_481),
	.B0(n_122),
	.B1(n_505),
	.C0(n_459),
	.C1(n_316));
   MX2X1 g16432__7410 (.Y(n_547),
	.A(FE_OFN13_call_button_lights_1),
	.B(n_403),
	.S0(n_515));
   MX2X1 g16433__6417 (.Y(n_546),
	.A(FE_OFN27_panel_button_lights_1),
	.B(n_403),
	.S0(n_514));
   OAI22X1 g16434__5477 (.Y(n_545),
	.A0(n_122),
	.A1(n_523),
	.B0(n_460),
	.B1(n_316));
   AOI21X1 g16435__2398 (.Y(n_544),
	.A0(n_369),
	.A1(n_522),
	.B0(floor_logic_inst_n_272));
   CLKINVX1 g16436 (.Y(n_541),
	.A(n_542));
   CLKAND2X2 g16437__5107 (.Y(n_540),
	.A(floor_call_buttons[5]),
	.B(n_511));
   CLKAND2X2 g16438__6260 (.Y(n_539),
	.A(panel_buttons[5]),
	.B(n_512));
   NOR3X1 g16439__4319 (.Y(n_538),
	.A(n_239),
	.B(n_417),
	.C(n_483));
   OR3X1 g16440__8428 (.Y(n_537),
	.A(elevator_fsm_inst_n_3927),
	.B(n_383),
	.C(n_479));
   OAI21X1 g16441__5526 (.Y(n_536),
	.A0(n_91),
	.A1(n_401),
	.B0(FE_OFN12_n_513));
   AND3X2 g16442__6783 (.Y(n_535),
	.A(n_231),
	.B(n_214),
	.C(n_488));
   OAI21X1 g16443__3680 (.Y(n_534),
	.A0(n_486),
	.A1(n_364),
	.B0(n_432));
   CLKAND2X2 g16444__1617 (.Y(n_543),
	.A(n_387),
	.B(n_512));
   OAI21X1 g16445__2802 (.Y(n_542),
	.A0(n_253),
	.A1(n_333),
	.B0(n_511));
   OAI22X1 g16446__1705 (.Y(n_532),
	.A0(n_122),
	.A1(n_493),
	.B0(n_221),
	.B1(n_292));
   OAI221X1 g16447__5122 (.Y(n_531),
	.A0(FE_OFN41_n_140),
	.A1(n_424),
	.B0(n_224),
	.B1(n_476),
	.C0(n_302));
   OR4X1 g16448__8246 (.Y(n_530),
	.A(n_232),
	.B(FE_OFN44_n_470),
	.C(n_354),
	.D(n_425));
   OAI22X1 g16449__7098 (.Y(n_529),
	.A0(n_122),
	.A1(n_487),
	.B0(n_366),
	.B1(n_450));
   AOI21X1 g16450__6131 (.Y(n_528),
	.A0(n_339),
	.A1(n_230),
	.B0(n_524));
   NOR4X1 g16451__1881 (.Y(n_527),
	.A(n_238),
	.B(elevator_fsm_inst_n_4141),
	.C(n_331),
	.D(n_466));
   OAI221X1 g16452__5115 (.Y(n_526),
	.A0(n_407),
	.A1(FE_OFN43_n_216),
	.B0(n_341),
	.B1(n_217),
	.C0(FE_OFN12_n_513));
   OAI21X1 g16453__7482 (.Y(n_525),
	.A0(n_484),
	.A1(n_364),
	.B0(n_432));
   NOR3X1 g16454__4733 (.Y(n_533),
	.A(n_252),
	.B(n_340),
	.C(n_489));
   CLKINVX2 g16455 (.Y(n_524),
	.A(n_523));
   NAND3X1 g16456__6161 (.Y(n_522),
	.A(n_414),
	.B(n_393),
	.C(n_490));
   NAND2X1 g16457__9315 (.Y(n_521),
	.A(n_478),
	.B(n_499));
   OR2X1 g16458__9945 (.Y(n_520),
	.A(n_393),
	.B(n_491));
   AND2X2 g16459__2883 (.Y(n_519),
	.A(n_372),
	.B(n_498));
   AOI221X1 g16460__2346 (.Y(n_518),
	.A0(n_338),
	.A1(n_314),
	.B0(n_212),
	.B1(n_394),
	.C0(n_502));
   NAND3X1 g16461__1666 (.Y(n_517),
	.A(n_412),
	.B(n_391),
	.C(n_500));
   OR2X1 g16462__7410 (.Y(n_516),
	.A(n_391),
	.B(n_501));
   AOI21X1 g16463__6417 (.Y(n_515),
	.A0(n_474),
	.A1(n_403),
	.B0(floor_logic_inst_n_272));
   AOI21X1 g16464__5477 (.Y(n_514),
	.A0(n_473),
	.A1(n_403),
	.B0(floor_logic_inst_n_272));
   NOR2X1 g16465__2398 (.Y(n_523),
	.A(n_218),
	.B(n_502));
   NOR3X1 g16466__5107 (.Y(n_510),
	.A(n_239),
	.B(n_307),
	.C(n_469));
   OAI222X1 g16467__6260 (.Y(n_509),
	.A0(n_122),
	.A1(n_385),
	.B0(n_396),
	.B1(n_450),
	.C0(n_233),
	.C1(n_445));
   OAI221X1 g16468__4319 (.Y(n_508),
	.A0(n_2),
	.A1(n_429),
	.B0(FE_OFN41_n_140),
	.B1(n_407),
	.C0(n_312));
   OAI22X1 g16469__8428 (.Y(n_507),
	.A0(n_221),
	.A1(n_444),
	.B0(n_233),
	.B1(n_475));
   AOI211X1 g16470__5526 (.Y(n_506),
	.A0(n_221),
	.A1(n_434),
	.B0(n_353),
	.C0(n_396));
   AOI221X1 g16471__6783 (.Y(n_505),
	.A0(FE_OFN39_elevator_fsm_inst_counter_state_2__1628),
	.A1(n_443),
	.B0(n_227),
	.B1(n_213),
	.C0(n_482));
   OAI22X1 g16472__3680 (.Y(n_504),
	.A0(direction_selector),
	.A1(n_465),
	.B0(n_2),
	.B1(n_231));
   OAI222X1 g16473__1617 (.Y(n_503),
	.A0(n_429),
	.A1(FE_OFN43_n_216),
	.B0(n_224),
	.B1(n_311),
	.C0(n_217),
	.C1(n_386));
   AOI221X1 g16474__2802 (.Y(n_513),
	.A0(n_426),
	.A1(n_213),
	.B0(n_227),
	.B1(n_216),
	.C0(n_313));
   NOR3X1 g16475__1705 (.Y(n_512),
	.A(n_414),
	.B(n_392),
	.C(n_491));
   NOR3X1 g16476__5122 (.Y(n_511),
	.A(n_412),
	.B(n_390),
	.C(n_501));
   CLKINVX1 g16477 (.Y(n_500),
	.A(n_501));
   AOI211X1 g16478__8246 (.Y(n_498),
	.A0(n_252),
	.A1(n_323),
	.B0(n_346),
	.C0(n_457));
   OAI22X1 g16479__7098 (.Y(n_497),
	.A0(n_221),
	.A1(n_439),
	.B0(n_233),
	.B1(n_226));
   OAI221X1 g16480__6131 (.Y(n_496),
	.A0(n_230),
	.A1(n_367),
	.B0(n_2),
	.B1(n_395),
	.C0(emergency_btn));
   AOI21X1 g16481__1881 (.Y(n_495),
	.A0(n_380),
	.A1(n_462),
	.B0(FE_OFN51_elevator_control_output_2));
   OAI21X1 g16482__5115 (.Y(n_494),
	.A0(n_211),
	.A1(n_431),
	.B0(n_231));
   AOI21X1 g16483__7482 (.Y(n_493),
	.A0(n_352),
	.A1(n_307),
	.B0(n_469));
   OAI21X1 g16484__4733 (.Y(n_492),
	.A0(n_429),
	.A1(n_225),
	.B0(n_311));
   AOI21X1 g16485__6161 (.Y(n_502),
	.A0(n_427),
	.A1(n_322),
	.B0(n_2));
   OAI211X1 g16486__9315 (.Y(n_501),
	.A0(n_276),
	.A1(n_305),
	.B0(n_388),
	.C0(n_449));
   NAND4X1 g16488__9945 (.Y(n_499),
	.A(n_380),
	.B(n_372),
	.C(n_428),
	.D(n_478));
   CLKINVX1 g16490 (.Y(n_490),
	.A(n_491));
   AOI222X1 g16491__2883 (.Y(n_488),
	.A0(FE_OFN34_elevator_control_output_7),
	.A1(n_436),
	.B0(n_342),
	.B1(n_314),
	.C0(FE_OFN39_elevator_fsm_inst_counter_state_2__1628),
	.C1(n_328));
   AOI22X1 g16492__2346 (.Y(n_487),
	.A0(n_218),
	.A1(n_438),
	.B0(n_212),
	.B1(n_416));
   AND3X2 g16493__1666 (.Y(n_486),
	.A(floor_call_buttons[2]),
	.B(n_388),
	.C(n_449));
   OAI22X1 g16494__7410 (.Y(n_485),
	.A0(FE_OFN38_elevator_fsm_inst_counter_state_1__1627),
	.A1(n_445),
	.B0(n_221),
	.B1(n_218));
   AND3X2 g16495__6417 (.Y(n_484),
	.A(panel_buttons[2]),
	.B(n_389),
	.C(n_447));
   OAI221X1 g16496__5477 (.Y(n_483),
	.A0(n_408),
	.A1(n_217),
	.B0(n_319),
	.B1(n_302),
	.C0(n_421));
   OAI22X1 g16497__2398 (.Y(n_482),
	.A0(n_211),
	.A1(n_455),
	.B0(n_224),
	.B1(n_217));
   AOI22X1 g16498__5107 (.Y(n_481),
	.A0(n_212),
	.A1(n_431),
	.B0(direction_selector),
	.B1(n_223));
   AOI22X1 g16499__6260 (.Y(n_480),
	.A0(n_428),
	.A1(n_373),
	.B0(n_247),
	.B1(n_220));
   OAI22X1 g16500__4319 (.Y(n_479),
	.A0(FE_OFN39_elevator_fsm_inst_counter_state_2__1628),
	.A1(n_434),
	.B0(n_371),
	.B1(n_214));
   OAI211X1 g16501__8428 (.Y(n_491),
	.A0(n_267),
	.A1(n_305),
	.B0(n_389),
	.C0(n_447));
   NAND4X1 g16502__5526 (.Y(n_489),
	.A(n_249),
	.B(n_245),
	.C(FE_OFN42_n_335),
	.D(n_467));
   INVX2 g16503 (.Y(n_477),
	.A(n_478));
   AOI21X1 g16504__6783 (.Y(n_476),
	.A0(n_407),
	.A1(n_216),
	.B0(n_212));
   AOI21X1 g16505__3680 (.Y(n_475),
	.A0(n_402),
	.A1(FE_OFN43_n_216),
	.B0(n_232));
   NAND2X1 g16506__1617 (.Y(n_474),
	.A(n_388),
	.B(n_448));
   NAND2X1 g16507__2802 (.Y(n_473),
	.A(n_389),
	.B(n_446));
   OAI211X1 g16508__1705 (.Y(n_472),
	.A0(n_258),
	.A1(n_361),
	.B0(panel_buttons[10]),
	.C0(n_453));
   NAND2X1 g16509__5122 (.Y(n_471),
	.A(n_450),
	.B(n_422));
   NOR2X1 g16510__8246 (.Y(n_478),
	.A(n_346),
	.B(n_461));
   CLKINVX2 g16511 (.Y(n_467),
	.A(n_468));
   OAI222X1 g16512__7098 (.Y(n_466),
	.A0(n_287),
	.A1(n_214),
	.B0(FE_OFN38_elevator_fsm_inst_counter_state_1__1627),
	.B1(n_399),
	.C0(n_210),
	.C1(FE_OFN34_elevator_control_output_7));
   AOI22X1 g16513__6131 (.Y(n_465),
	.A0(FE_OFN39_elevator_fsm_inst_counter_state_2__1628),
	.A1(n_415),
	.B0(n_296),
	.B1(n_242));
   OAI22X1 g16514__1881 (.Y(n_464),
	.A0(floor_logic_inst_n_272),
	.A1(n_389),
	.B0(n_70),
	.B1(n_411));
   OAI22X1 g16515__5115 (.Y(n_463),
	.A0(floor_logic_inst_n_272),
	.A1(n_388),
	.B0(n_74),
	.B1(n_411));
   NOR4X1 g16516__7482 (.Y(n_470),
	.A(n_374),
	.B(n_122),
	.C(n_91),
	.D(n_214));
   OR3X1 g16517__4733 (.Y(n_469),
	.A(n_417),
	.B(n_301),
	.C(n_354));
   NAND4X1 g16518__6161 (.Y(n_468),
	.A(n_61),
	.B(n_145),
	.C(n_237),
	.D(n_343));
   CLKINVX2 g16519 (.Y(n_462),
	.A(n_461));
   CLKINVX1 g16520 (.Y(n_460),
	.A(n_459));
   CLKINVX2 g16521 (.Y(n_458),
	.A(n_457));
   INVX2 g16522 (.Y(n_455),
	.A(n_454));
   INVX2 g16523 (.Y(n_452),
	.A(n_451));
   CLKINVX1 g16524 (.Y(n_448),
	.A(n_449));
   CLKINVX1 g16525 (.Y(n_446),
	.A(n_447));
   CLKINVX1 g16526 (.Y(n_444),
	.A(n_445));
   OAI21X1 g16527__9315 (.Y(n_443),
	.A0(n_349),
	.A1(emergency_btn),
	.B0(n_322));
   AOI221X1 g16528__9945 (.Y(n_442),
	.A0(n_310),
	.A1(FE_OFN34_elevator_control_output_7),
	.B0(elevator_floor_selector[2]),
	.B1(FE_OFN39_elevator_fsm_inst_counter_state_2__1628),
	.C0(direction_selector));
   NAND2X1 g16529__2883 (.Y(n_441),
	.A(n_346),
	.B(n_405));
   NOR2X1 g16530__2346 (.Y(n_440),
	.A(n_324),
	.B(n_413));
   AOI21X1 g16531__1666 (.Y(n_439),
	.A0(direction_selector),
	.A1(n_356),
	.B0(n_232));
   AND2X1 g16532__7410 (.Y(n_438),
	.A(n_228),
	.B(n_408));
   OR2X1 g16533__6417 (.Y(n_437),
	.A(n_211),
	.B(n_395));
   NAND2X1 g16534__5477 (.Y(n_461),
	.A(n_327),
	.B(n_405));
   NAND2X1 g16535__2398 (.Y(n_459),
	.A(n_371),
	.B(n_408));
   NAND2X1 g16536__5107 (.Y(n_457),
	.A(n_325),
	.B(n_413));
   AOI21X1 g16537__6260 (.Y(n_456),
	.A0(n_333),
	.A1(floor_logic_inst_n_359),
	.B0(FE_OFN40_floor_logic_inst_n_272));
   NOR2X2 g16538__4319 (.Y(n_454),
	.A(n_338),
	.B(n_394));
   OR3X1 g16539__8428 (.Y(n_453),
	.A(FE_OFN18_panel_button_lights_8),
	.B(n_88),
	.C(n_377));
   NOR3X1 g16540__5526 (.Y(n_451),
	.A(FE_OFN4_call_button_lights_8),
	.B(n_86),
	.C(n_377));
   NAND2X1 g16541__6783 (.Y(n_450),
	.A(n_222),
	.B(n_395));
   NAND3X1 g16542__3680 (.Y(n_449),
	.A(floor_call_buttons[1]),
	.B(n_57),
	.C(n_345));
   NAND3X1 g16543__1617 (.Y(n_447),
	.A(panel_buttons[1]),
	.B(n_156),
	.C(n_345));
   NAND2X1 g16544__2802 (.Y(n_445),
	.A(n_367),
	.B(n_416));
   CLKINVX1 g16545 (.Y(n_436),
	.A(n_418));
   OAI21X1 g16546__1705 (.Y(n_427),
	.A0(direction_selector),
	.A1(n_348),
	.B0(n_91));
   MX2X1 g16547__5122 (.Y(n_426),
	.A(FE_OFN2_n_25),
	.B(n_351),
	.S0(n_91));
   OAI22X1 g16548__8246 (.Y(n_425),
	.A0(n_221),
	.A1(n_376),
	.B0(FE_OFN39_elevator_fsm_inst_counter_state_2__1628),
	.B1(n_228));
   AOI22X1 g16549__7098 (.Y(n_424),
	.A0(n_379),
	.A1(n_2),
	.B0(n_298),
	.B1(n_230));
   AOI22X1 g16550__6131 (.Y(n_423),
	.A0(n_370),
	.A1(n_315),
	.B0(n_350),
	.B1(n_213));
   AOI21X1 g16551__1881 (.Y(n_422),
	.A0(n_241),
	.A1(n_376),
	.B0(n_384));
   AOI22X1 g16552__5115 (.Y(n_421),
	.A0(n_230),
	.A1(n_376),
	.B0(n_224),
	.B1(n_311));
   AOI21X1 g16553__7482 (.Y(n_420),
	.A0(n_246),
	.A1(FE_OFN42_n_335),
	.B0(n_247));
   NAND3X1 g16554__4733 (.Y(n_419),
	.A(emergency_btn),
	.B(n_367),
	.C(n_378));
   AOI21X1 g16555__6161 (.Y(n_418),
	.A0(n_374),
	.A1(n_212),
	.B0(n_242));
   AOI21X1 g16556__9315 (.Y(n_435),
	.A0(n_304),
	.A1(n_363),
	.B0(FE_OFN40_floor_logic_inst_n_272));
   OR3X1 g16557__9945 (.Y(n_434),
	.A(n_227),
	.B(n_347),
	.C(n_353));
   AOI21X1 g16558__2883 (.Y(n_433),
	.A0(n_361),
	.A1(floor_logic_inst_n_359),
	.B0(FE_OFN40_floor_logic_inst_n_272));
   AOI21X1 g16559__2346 (.Y(n_432),
	.A0(n_305),
	.A1(n_365),
	.B0(floor_logic_inst_n_272));
   AOI21X1 g16560__1666 (.Y(n_431),
	.A0(n_375),
	.A1(FE_OFN34_elevator_control_output_7),
	.B0(n_342));
   NOR4X2 g16561__7410 (.Y(n_430),
	.A(FE_OFN41_n_140),
	.B(n_300),
	.C(elevator_fsm_inst_n_4141),
	.D(n_233));
   OR2X2 g16562__6417 (.Y(n_429),
	.A(n_355),
	.B(n_415));
   AOI22X2 g16563__5477 (.Y(n_428),
	.A0(n_334),
	.A1(n_220),
	.B0(FE_OFN53_n_44),
	.B1(n_290));
   INVX2 g16564 (.Y(n_410),
	.A(n_409));
   NAND2X1 g16565__2398 (.Y(n_402),
	.A(n_371),
	.B(n_91));
   OR2X1 g16566__5107 (.Y(n_401),
	.A(n_370),
	.B(FE_OFN43_n_216));
   NOR2X1 g16567__6260 (.Y(n_417),
	.A(n_339),
	.B(n_214));
   NOR2X1 g16568__4319 (.Y(n_416),
	.A(FE_OFN2_n_25),
	.B(n_347));
   NOR2X1 g16569__8428 (.Y(n_415),
	.A(n_379),
	.B(n_91));
   NOR3X1 g16570__5526 (.Y(n_414),
	.A(FE_OFN24_panel_button_lights_4),
	.B(n_87),
	.C(n_306));
   OAI211X1 g16571__6783 (.Y(n_413),
	.A0(FE_OFN3_call_button_lights_9),
	.A1(FE_OFN17_panel_button_lights_9),
	.B0(n_323),
	.C0(n_360));
   NOR3X1 g16572__3680 (.Y(n_412),
	.A(FE_OFN10_call_button_lights_4),
	.B(n_182),
	.C(n_306));
   NOR2X1 g16573__1617 (.Y(n_411),
	.A(n_337),
	.B(floor_logic_inst_n_4880));
   NOR3X1 g16574__2802 (.Y(n_409),
	.A(FE_OFN21_panel_button_lights_6),
	.B(n_181),
	.C(n_309));
   OR2X1 g16575__1705 (.Y(n_408),
	.A(n_352),
	.B(n_91));
   NAND2X1 g16576__5122 (.Y(n_407),
	.A(n_370),
	.B(FE_OFN34_elevator_control_output_7));
   NOR2X1 g16577__8246 (.Y(n_406),
	.A(FE_OFN7_call_button_lights_6),
	.B(n_359));
   OAI21X1 g16578__7098 (.Y(n_405),
	.A0(FE_OFN13_call_button_lights_1),
	.A1(FE_OFN27_panel_button_lights_1),
	.B0(n_336));
   NAND2X1 g16579__6131 (.Y(n_404),
	.A(n_377),
	.B(n_142));
   OR2X1 g16580__1881 (.Y(n_403),
	.A(n_345),
	.B(floor_logic_inst_n_359));
   CLKINVX2 g16582 (.Y(n_392),
	.A(n_393));
   CLKINVX2 g16583 (.Y(n_390),
	.A(n_391));
   NAND3X1 g16584__5115 (.Y(n_387),
	.A(panel_buttons[5]),
	.B(n_160),
	.C(n_332));
   CLKAND2X2 g16585__7482 (.Y(n_386),
	.A(n_370),
	.B(n_358));
   OAI21X1 g16586__4733 (.Y(n_385),
	.A0(n_213),
	.A1(n_292),
	.B0(emergency_btn));
   AOI21X1 g16587__6161 (.Y(n_384),
	.A0(n_236),
	.A1(n_213),
	.B0(n_378));
   OAI22X1 g16588__9315 (.Y(n_383),
	.A0(n_299),
	.A1(n_302),
	.B0(FE_OFN43_n_216),
	.B1(n_223));
   NOR3X1 g16589__9945 (.Y(n_382),
	.A(n_297),
	.B(elevator_fsm_inst_n_4141),
	.C(n_217));
   NAND3X1 g16590__2883 (.Y(n_381),
	.A(floor_call_buttons[9]),
	.B(n_151),
	.C(n_360));
   AOI21X1 g16591__2346 (.Y(n_400),
	.A0(n_295),
	.A1(floor_logic_inst_n_359),
	.B0(FE_OFN40_floor_logic_inst_n_272));
   AOI211X1 g16592__1666 (.Y(n_398),
	.A0(elevator_floor_selector[2]),
	.A1(n_2),
	.B0(n_289),
	.C0(n_213));
   AND3X2 g16593__7410 (.Y(n_397),
	.A(n_139),
	.B(n_317),
	.C(n_288));
   NOR3X1 g16594__6417 (.Y(n_396),
	.A(FE_OFN41_n_140),
	.B(FE_OFN33_elevator_control_output_7),
	.C(n_292));
   AOI21X1 g16595__5477 (.Y(n_395),
	.A0(FE_OFN33_elevator_control_output_7),
	.A1(n_293),
	.B0(FE_OFN2_n_25));
   AOI21X1 g16596__2398 (.Y(n_394),
	.A0(FE_OFN37_elevator_floor_selector_0),
	.A1(n_299),
	.B0(n_91));
   NAND3X1 g16597__5107 (.Y(n_393),
	.A(panel_buttons[3]),
	.B(n_145),
	.C(n_318));
   NAND3X1 g16598__6260 (.Y(n_391),
	.A(floor_call_buttons[3]),
	.B(n_61),
	.C(n_318));
   NAND3X1 g16599__4319 (.Y(n_389),
	.A(panel_buttons[0]),
	.B(n_70),
	.C(n_337));
   NAND3X1 g16600__8428 (.Y(n_388),
	.A(floor_call_buttons[0]),
	.B(n_74),
	.C(n_337));
   CLKINVX2 g16601 (.Y(n_375),
	.A(n_374));
   CLKINVX1 g16603 (.Y(n_366),
	.A(n_367));
   CLKINVX2 g16604 (.Y(n_364),
	.A(n_365));
   CLKINVX2 g16605 (.Y(n_362),
	.A(n_363));
   CLKINVX2 g16606 (.Y(n_360),
	.A(n_361));
   NAND2X1 g16607__5526 (.Y(n_359),
	.A(floor_call_buttons[6]),
	.B(n_308));
   NAND2X1 g16608__6783 (.Y(n_358),
	.A(n_297),
	.B(n_91));
   NAND2X1 g16609__3680 (.Y(n_357),
	.A(panel_buttons[7]),
	.B(n_303));
   NOR2X1 g16610__1617 (.Y(n_356),
	.A(n_298),
	.B(elevator_fsm_inst_n_4141));
   NOR2X1 g16611__2802 (.Y(n_355),
	.A(FE_OFN37_elevator_floor_selector_0),
	.B(n_297));
   OR2X2 g16612__1705 (.Y(n_380),
	.A(n_249),
	.B(n_291));
   NOR2X1 g16613__5122 (.Y(n_379),
	.A(n_37),
	.B(n_298));
   NAND2X1 g16614__8246 (.Y(n_378),
	.A(FE_OFN39_elevator_fsm_inst_counter_state_2__1628),
	.B(n_293));
   NOR2X1 g16615__7098 (.Y(n_377),
	.A(FE_OFN34_elevator_control_output_7),
	.B(n_321));
   NOR2X1 g16616__6131 (.Y(n_376),
	.A(FE_OFN2_n_25),
	.B(n_293));
   NOR2X1 g16617__1881 (.Y(n_374),
	.A(n_36),
	.B(n_310));
   OAI21X1 g16618__5115 (.Y(n_372),
	.A0(n_209),
	.A1(n_220),
	.B0(n_246));
   OR2X2 g16619__7482 (.Y(n_371),
	.A(FE_OFN37_elevator_floor_selector_0),
	.B(n_300));
   NAND2X1 g16620__4733 (.Y(n_370),
	.A(FE_OFN37_elevator_floor_selector_0),
	.B(n_296));
   NAND2X1 g16621__6161 (.Y(n_369),
	.A(n_306),
	.B(n_288));
   NAND2X1 g16622__9315 (.Y(n_368),
	.A(n_309),
	.B(n_142));
   NAND2X1 g16623__9945 (.Y(n_367),
	.A(FE_OFN41_n_140),
	.B(n_293));
   NAND2X1 g16624__2883 (.Y(n_365),
	.A(n_305),
	.B(n_180));
   NAND2X1 g16625__2346 (.Y(n_363),
	.A(n_304),
	.B(n_142));
   NOR2X2 g16626__1666 (.Y(n_361),
	.A(n_91),
	.B(n_321));
   CLKINVX1 g16627 (.Y(n_351),
	.A(n_350));
   CLKINVX2 g16628 (.Y(n_349),
	.A(n_348));
   CLKINVX2 g16629 (.Y(n_344),
	.A(n_343));
   CLKINVX1 g16630 (.Y(n_341),
	.A(n_342));
   CLKINVX2 g16631 (.Y(n_338),
	.A(n_339));
   CLKINVX1 g16632 (.Y(n_336),
	.A(n_337));
   CLKINVX2 g16634 (.Y(n_332),
	.A(n_333));
   OAI22X1 g16635__7410 (.Y(n_331),
	.A0(n_286),
	.A1(n_242),
	.B0(n_36),
	.B1(n_285));
   NOR3X1 g16636__6417 (.Y(n_330),
	.A(FE_OFN5_call_button_lights_7),
	.B(n_176),
	.C(n_304));
   OAI21X1 g16637__5477 (.Y(n_329),
	.A0(FE_OFN37_elevator_floor_selector_0),
	.A1(n_284),
	.B0(n_236));
   OAI221X1 g16638__2398 (.Y(n_328),
	.A0(elevator_floor_selector[1]),
	.A1(FE_OFN34_elevator_control_output_7),
	.B0(n_141),
	.B1(n_37),
	.C0(n_238));
   OAI211X1 g16639__5107 (.Y(n_327),
	.A0(FE_OFN11_call_button_lights_3),
	.A1(FE_OFN25_panel_button_lights_3),
	.B0(floor_logic_inst_n_4785),
	.C0(n_220));
   NOR2X1 g16640__6260 (.Y(n_326),
	.A(n_225),
	.B(n_292));
   AND2X1 g16641__4319 (.Y(n_354),
	.A(n_293),
	.B(n_314));
   NOR2X1 g16642__8428 (.Y(n_353),
	.A(n_91),
	.B(n_293));
   NOR2X1 g16643__5526 (.Y(n_352),
	.A(elevator_floor_selector[2]),
	.B(n_310));
   NAND3X1 g16644__6783 (.Y(n_350),
	.A(elevator_floor_selector[3]),
	.B(n_37),
	.C(n_287));
   NAND3X1 g16645__3680 (.Y(n_348),
	.A(n_141),
	.B(n_37),
	.C(n_238));
   NOR2X1 g16646__1617 (.Y(n_347),
	.A(FE_OFN33_elevator_control_output_7),
	.B(n_292));
   NOR3X2 g16647__2802 (.Y(n_346),
	.A(n_237),
	.B(FE_OFN57_elevator_control_output_8),
	.C(n_219));
   NAND2X1 g16648__1705 (.Y(n_345),
	.A(FE_OFN34_elevator_control_output_7),
	.B(n_320));
   NOR3X2 g16649__5122 (.Y(n_343),
	.A(FE_OFN27_panel_button_lights_1),
	.B(FE_OFN13_call_button_lights_1),
	.C(n_251));
   NOR2X1 g16650__8246 (.Y(n_342),
	.A(FE_OFN37_elevator_floor_selector_0),
	.B(n_298));
   NAND3X1 g16651__7098 (.Y(n_340),
	.A(n_151),
	.B(n_52),
	.C(n_235));
   NAND2X1 g16652__6131 (.Y(n_339),
	.A(n_37),
	.B(n_319));
   NAND2X1 g16653__1881 (.Y(n_337),
	.A(n_91),
	.B(n_320));
   NOR3X1 g16654__5115 (.Y(n_335),
	.A(FE_OFN8_call_button_lights_5),
	.B(FE_OFN22_panel_button_lights_5),
	.C(n_247));
   AND3X2 g16655__7482 (.Y(n_333),
	.A(FE_OFN34_elevator_control_output_7),
	.B(n_143),
	.C(n_282));
   CLKINVX2 g16681 (.Y(n_325),
	.A(n_324));
   CLKINVX2 g16682 (.Y(n_318),
	.A(n_317));
   INVX2 g16683 (.Y(n_316),
	.A(n_315));
   CLKINVX2 g16684 (.Y(n_313),
	.A(n_312));
   CLKINVX2 g16685 (.Y(n_309),
	.A(n_308));
   CLKINVX1 g16686 (.Y(n_303),
	.A(n_304));
   CLKINVX2 g16687 (.Y(n_302),
	.A(n_301));
   CLKINVX2 g16688 (.Y(n_299),
	.A(n_300));
   INVX2 g16689 (.Y(n_296),
	.A(n_297));
   CLKINVX1 g16690 (.Y(n_294),
	.A(n_295));
   CLKINVX2 g16691 (.Y(n_292),
	.A(n_293));
   AOI21X1 g16692__4733 (.Y(n_291),
	.A0(floor_logic_inst_n_4785),
	.A1(FE_OFN53_n_44),
	.B0(n_220));
   AOI21X1 g16693__6161 (.Y(n_290),
	.A0(n_47),
	.A1(n_160),
	.B0(floor_logic_inst_n_4842));
   NOR3X1 g16694__9315 (.Y(n_289),
	.A(elevator_floor_selector[2]),
	.B(n_2),
	.C(n_91));
   NOR2X1 g16695__9945 (.Y(n_324),
	.A(n_235),
	.B(FE_OFN55_elevator_control_output_10));
   OR2X2 g16696__2883 (.Y(n_323),
	.A(FE_OFN53_n_44),
	.B(n_240));
   OAI21X1 g16697__2346 (.Y(n_322),
	.A0(raw_power_switch),
	.A1(FE_OFN2_n_25),
	.B0(FE_OFN34_elevator_control_output_7));
   NAND2X1 g16698__1666 (.Y(n_321),
	.A(FE_OFN55_elevator_control_output_10),
	.B(n_240));
   CLKAND2X2 g16699__7410 (.Y(n_320),
	.A(FE_OFN53_n_44),
	.B(n_240));
   AND2X2 g16700__6417 (.Y(n_319),
	.A(elevator_floor_selector[2]),
	.B(n_250));
   NOR2X1 g16701__5477 (.Y(n_317),
	.A(floor_logic_inst_n_4785),
	.B(n_219));
   NOR2X1 g16702__2398 (.Y(n_315),
	.A(FE_OFN38_elevator_fsm_inst_counter_state_1__1627),
	.B(FE_OFN43_n_216));
   NOR2X1 g16703__5107 (.Y(n_314),
	.A(FE_OFN33_elevator_control_output_7),
	.B(n_211));
   NAND2X1 g16704__6260 (.Y(n_312),
	.A(n_212),
	.B(n_232));
   NAND2X1 g16705__4319 (.Y(n_311),
	.A(FE_OFN43_n_216),
	.B(n_217));
   NAND2X1 g16706__8428 (.Y(n_310),
	.A(FE_OFN37_elevator_floor_selector_0),
	.B(n_250));
   NAND2X1 g16707__5526 (.Y(n_308),
	.A(n_243),
	.B(n_282));
   NOR2X1 g16708__6783 (.Y(n_307),
	.A(FE_OFN39_elevator_fsm_inst_counter_state_2__1628),
	.B(n_226));
   NOR2X1 g16709__3680 (.Y(n_306),
	.A(floor_logic_inst_n_4842),
	.B(n_283));
   NOR2X2 g16710__1617 (.Y(n_305),
	.A(n_244),
	.B(n_219));
   NOR2X1 g16711__2802 (.Y(n_304),
	.A(floor_logic_inst_n_4785),
	.B(n_283));
   NOR2X1 g16712__1705 (.Y(n_301),
	.A(n_2),
	.B(n_226));
   NAND2X1 g16713__5122 (.Y(n_300),
	.A(n_36),
	.B(n_285));
   NAND2X1 g16714__8246 (.Y(n_298),
	.A(elevator_floor_selector[2]),
	.B(n_285));
   NAND3X1 g16715__7098 (.Y(n_297),
	.A(elevator_floor_selector[3]),
	.B(n_141),
	.C(n_36));
   NOR2X1 g16716__6131 (.Y(n_295),
	.A(FE_OFN53_n_44),
	.B(n_244));
   AND3X2 g16717__1881 (.Y(n_293),
	.A(reset_n),
	.B(n_183),
	.C(n_180));
   INVX2 g16718 (.Y(n_287),
	.A(n_286));
   CLKINVX2 g16720 (.Y(n_282),
	.A(n_283));
   NOR2X1 g16721__5115 (.Y(n_281),
	.A(n_205),
	.B(raw_floor_call_buttons[5]));
   NOR2X1 g16722__7482 (.Y(n_280),
	.A(n_188),
	.B(raw_floor_call_buttons[10]));
   NOR2X1 g16723__4733 (.Y(n_279),
	.A(n_190),
	.B(raw_floor_call_buttons[7]));
   NOR2X1 g16724__6161 (.Y(n_278),
	.A(n_197),
	.B(raw_floor_call_buttons[8]));
   NOR2X1 g16725__9315 (.Y(n_277),
	.A(n_195),
	.B(raw_floor_call_buttons[9]));
   NAND2X1 g16726__9945 (.Y(n_276),
	.A(floor_call_buttons[2]),
	.B(n_169));
   NOR2X1 g16727__2883 (.Y(n_275),
	.A(n_185),
	.B(raw_panel_buttons[2]));
   NOR2X1 g16728__2346 (.Y(n_274),
	.A(door_close_btn),
	.B(n_184));
   NOR2X1 g16729__1666 (.Y(n_273),
	.A(n_193),
	.B(raw_panel_buttons[6]));
   NOR2X1 g16730__7410 (.Y(n_272),
	.A(n_204),
	.B(raw_floor_call_buttons[2]));
   NOR2X1 g16731__6417 (.Y(n_271),
	.A(door_open_btn),
	.B(n_186));
   NOR2X1 g16732__5477 (.Y(n_270),
	.A(n_196),
	.B(raw_panel_buttons[4]));
   NOR2X1 g16733__2398 (.Y(n_269),
	.A(n_208),
	.B(raw_panel_buttons[10]));
   NOR2X1 g16734__5107 (.Y(n_268),
	.A(n_189),
	.B(raw_floor_call_buttons[4]));
   NAND2X1 g16735__6260 (.Y(n_267),
	.A(panel_buttons[2]),
	.B(n_72));
   NOR2X1 g16736__4319 (.Y(n_266),
	.A(n_202),
	.B(raw_floor_call_buttons[6]));
   NOR2X1 g16737__8428 (.Y(n_265),
	.A(n_201),
	.B(raw_floor_call_buttons[3]));
   NOR2X1 g16738__5526 (.Y(n_264),
	.A(n_187),
	.B(raw_panel_buttons[9]));
   NOR2X1 g16739__6783 (.Y(n_263),
	.A(n_206),
	.B(raw_emergency_btn));
   NOR2X1 g16740__3680 (.Y(n_262),
	.A(n_199),
	.B(raw_panel_buttons[7]));
   NOR2X1 g16741__1617 (.Y(n_261),
	.A(n_191),
	.B(raw_panel_buttons[1]));
   NOR2X1 g16742__2802 (.Y(n_260),
	.A(n_207),
	.B(raw_floor_call_buttons[0]));
   NOR2X1 g16743__1705 (.Y(n_259),
	.A(n_194),
	.B(raw_panel_buttons[8]));
   NAND2X1 g16744__5122 (.Y(n_258),
	.A(panel_buttons[9]),
	.B(n_52));
   NOR2X1 g16745__8246 (.Y(n_257),
	.A(n_192),
	.B(raw_panel_buttons[0]));
   NOR2X1 g16746__7098 (.Y(n_256),
	.A(n_203),
	.B(raw_panel_buttons[5]));
   NOR2X1 g16747__6131 (.Y(n_255),
	.A(n_200),
	.B(raw_panel_buttons[3]));
   NOR2X1 g16748__1881 (.Y(n_254),
	.A(n_198),
	.B(raw_floor_call_buttons[1]));
   NAND2X1 g16749__5115 (.Y(n_253),
	.A(floor_call_buttons[5]),
	.B(n_47));
   NOR2X1 g16750__7482 (.Y(n_288),
	.A(floor_logic_inst_n_385),
	.B(n_89));
   NAND2X1 g16751__4733 (.Y(n_286),
	.A(elevator_floor_selector[1]),
	.B(n_36));
   NOR2X1 g16752__6161 (.Y(n_285),
	.A(elevator_floor_selector[3]),
	.B(n_141));
   NAND2X1 g16753__9315 (.Y(n_283),
	.A(FE_OFN31_elevator_control_output_9),
	.B(FE_OFN53_n_44));
   CLKINVX2 g16754 (.Y(n_246),
	.A(n_245));
   CLKINVX1 g16755 (.Y(n_243),
	.A(n_244));
   CLKINVX2 g16756 (.Y(n_227),
	.A(n_228));
   CLKINVX2 g16757 (.Y(n_225),
	.A(n_226));
   CLKINVX2 g16758 (.Y(n_223),
	.A(n_224));
   CLKINVX2 g16759 (.Y(n_221),
	.A(n_222));
   CLKINVX2 g16760 (.Y(n_219),
	.A(n_220));
   CLKINVX2 g16761 (.Y(n_217),
	.A(n_218));
   CLKINVX2 g16763 (.Y(n_213),
	.A(n_214));
   CLKINVX2 g16764 (.Y(n_211),
	.A(n_212));
   NAND2X1 g16765__9945 (.Y(n_210),
	.A(elevator_floor_selector[1]),
	.B(FE_OFN41_n_140));
   NOR2X1 g16766__2883 (.Y(n_209),
	.A(FE_OFN57_elevator_control_output_8),
	.B(FE_OFN55_elevator_control_output_10));
   OR2X2 g16767__2346 (.Y(n_252),
	.A(FE_OFN16_panel_button_lights_10),
	.B(FE_OFN1_call_button_lights_10));
   NAND2X1 g16768__1666 (.Y(n_251),
	.A(n_74),
	.B(n_70));
   NOR2X1 g16769__7410 (.Y(n_250),
	.A(elevator_floor_selector[3]),
	.B(elevator_floor_selector[1]));
   NOR2X1 g16770__6417 (.Y(n_249),
	.A(FE_OFN5_call_button_lights_7),
	.B(FE_OFN19_panel_button_lights_7));
   NAND2X1 g16771__5477 (.Y(n_248),
	.A(FE_OFN11_elevator_fsm_inst_counter_state_4__1630),
	.B(\elevator_fsm_inst_counter_state[3]_1629 ));
   OR2X2 g16772__2398 (.Y(n_247),
	.A(FE_OFN24_panel_button_lights_4),
	.B(FE_OFN10_call_button_lights_4));
   NOR2X1 g16773__5107 (.Y(n_245),
	.A(FE_OFN7_call_button_lights_6),
	.B(FE_OFN21_panel_button_lights_6));
   NAND2X1 g16774__6260 (.Y(n_244),
	.A(n_91),
	.B(FE_OFN57_elevator_control_output_8));
   NOR2X1 g16775__4319 (.Y(n_242),
	.A(FE_OFN37_elevator_floor_selector_0),
	.B(n_2));
   NOR2X1 g16776__8428 (.Y(n_241),
	.A(n_122),
	.B(FE_OFN39_elevator_fsm_inst_counter_state_2__1628));
   NOR2X1 g16777__5526 (.Y(n_240),
	.A(FE_OFN31_elevator_control_output_9),
	.B(FE_OFN57_elevator_control_output_8));
   NAND2X1 g16778__6783 (.Y(n_239),
	.A(\elevator_fsm_inst_counter_state[3]_1629 ),
	.B(FE_OFN38_elevator_fsm_inst_counter_state_1__1627));
   NOR2X1 g16779__3680 (.Y(n_238),
	.A(elevator_floor_selector[3]),
	.B(elevator_floor_selector[2]));
   NOR2X2 g16780__1617 (.Y(n_237),
	.A(FE_OFN12_call_button_lights_2),
	.B(FE_OFN26_panel_button_lights_2));
   NOR2X2 g16781__2802 (.Y(n_236),
	.A(FE_OFN38_elevator_fsm_inst_counter_state_1__1627),
	.B(FE_OFN34_elevator_control_output_7));
   NOR2X1 g16782__1705 (.Y(n_235),
	.A(FE_OFN4_call_button_lights_8),
	.B(FE_OFN18_panel_button_lights_8));
   NOR2X1 g16783__5122 (.Y(n_234),
	.A(\elevator_fsm_inst_counter_state[3]_1629 ),
	.B(n_122));
   NAND2X1 g16784__8246 (.Y(n_233),
	.A(n_122),
	.B(FE_OFN39_elevator_fsm_inst_counter_state_2__1628));
   NOR2X2 g16785__7098 (.Y(n_232),
	.A(direction_selector),
	.B(emergency_btn));
   NAND2X1 g16786__6131 (.Y(n_231),
	.A(direction_selector),
	.B(FE_OFN2_n_25));
   NOR2X2 g16787__1881 (.Y(n_230),
	.A(FE_OFN39_elevator_fsm_inst_counter_state_2__1628),
	.B(FE_OFN34_elevator_control_output_7));
   NOR2X1 g16788__5115 (.Y(n_229),
	.A(\elevator_fsm_inst_counter_state[3]_1629 ),
	.B(FE_OFN38_elevator_fsm_inst_counter_state_1__1627));
   NAND2X1 g16789__7482 (.Y(n_228),
	.A(FE_OFN2_n_25),
	.B(n_91));
   NAND2X1 g16790__4733 (.Y(n_226),
	.A(direction_selector),
	.B(FE_OFN33_elevator_control_output_7));
   CLKAND2X2 g16791__6161 (.Y(n_224),
	.A(emergency_btn),
	.B(n_91));
   NOR2X2 g16792__9315 (.Y(n_222),
	.A(FE_OFN38_elevator_fsm_inst_counter_state_1__1627),
	.B(FE_OFN39_elevator_fsm_inst_counter_state_2__1628));
   NOR2X2 g16793__9945 (.Y(n_220),
	.A(FE_OFN31_elevator_control_output_9),
	.B(FE_OFN55_elevator_control_output_10));
   NOR2X2 g16794__2883 (.Y(n_218),
	.A(FE_OFN41_n_140),
	.B(FE_OFN39_elevator_fsm_inst_counter_state_2__1628));
   NOR2X1 g16795__2346 (.Y(n_216),
	.A(direction_selector),
	.B(n_2));
   NAND2X1 g16796__1666 (.Y(n_214),
	.A(direction_selector),
	.B(FE_OFN39_elevator_fsm_inst_counter_state_2__1628));
   CLKAND2X2 g16797__7410 (.Y(n_212),
	.A(FE_OFN41_n_140),
	.B(n_2));
   CLKINVX1 g16798 (.Y(n_208),
	.A(panel_debouncer10_key_current_state[0]));
   CLKINVX1 g16799 (.Y(n_207),
	.A(floor_call_debouncer0_key_current_state[0]));
   CLKINVX1 g16800 (.Y(n_206),
	.A(emergency_debouncer_key_current_state[0]));
   CLKINVX1 g16801 (.Y(n_205),
	.A(floor_call_debouncer5_key_current_state[0]));
   CLKINVX1 g16802 (.Y(n_204),
	.A(floor_call_debouncer2_key_current_state[0]));
   CLKINVX1 g16803 (.Y(n_203),
	.A(panel_debouncer5_key_current_state[0]));
   CLKINVX1 g16804 (.Y(n_202),
	.A(floor_call_debouncer6_key_current_state[0]));
   CLKINVX1 g16805 (.Y(n_201),
	.A(floor_call_debouncer3_key_current_state[0]));
   CLKINVX1 g16806 (.Y(n_200),
	.A(panel_debouncer3_key_current_state[0]));
   CLKINVX1 g16807 (.Y(n_199),
	.A(panel_debouncer7_key_current_state[0]));
   CLKINVX1 g16808 (.Y(n_198),
	.A(floor_call_debouncer1_key_current_state[0]));
   CLKINVX1 g16809 (.Y(n_197),
	.A(floor_call_debouncer8_key_current_state[0]));
   CLKINVX1 g16810 (.Y(n_196),
	.A(panel_debouncer4_key_current_state[0]));
   CLKINVX1 g16811 (.Y(n_195),
	.A(floor_call_debouncer9_key_current_state[0]));
   CLKINVX1 g16812 (.Y(n_194),
	.A(panel_debouncer8_key_current_state[0]));
   CLKINVX1 g16813 (.Y(n_193),
	.A(panel_debouncer6_key_current_state[0]));
   CLKINVX1 g16814 (.Y(n_192),
	.A(panel_debouncer0_key_current_state[0]));
   CLKINVX1 g16815 (.Y(n_191),
	.A(panel_debouncer1_key_current_state[0]));
   CLKINVX1 g16816 (.Y(n_190),
	.A(floor_call_debouncer7_key_current_state[0]));
   CLKINVX1 g16817 (.Y(n_189),
	.A(floor_call_debouncer4_key_current_state[0]));
   CLKINVX1 g16818 (.Y(n_188),
	.A(floor_call_debouncer10_key_current_state[0]));
   CLKINVX1 g16819 (.Y(n_187),
	.A(panel_debouncer9_key_current_state[0]));
   CLKINVX2 g16820 (.Y(n_186),
	.A(raw_door_open_btn));
   CLKINVX1 g16821 (.Y(n_185),
	.A(panel_debouncer2_key_current_state[0]));
   CLKINVX2 g16822 (.Y(n_184),
	.A(raw_door_close_btn));
   INVX2 g16823 (.Y(n_183),
	.A(weight_sensor));
   CLKINVX1 g16824 (.Y(n_182),
	.A(floor_call_buttons[4]));
   CLKINVX1 g16825 (.Y(n_181),
	.A(panel_buttons[6]));
   CLKINVX2 g16826 (.Y(n_180),
	.A(floor_logic_inst_n_4880));
   INVX2 g16830 (.Y(n_176),
	.A(floor_call_buttons[7]));
   CLKINVX2 g16837 (.Y(n_169),
	.A(FE_OFN12_call_button_lights_2));
   CLKINVX2 g16843 (.Y(n_160),
	.A(FE_OFN22_panel_button_lights_5));
   CLKINVX2 g16850 (.Y(n_156),
	.A(FE_OFN27_panel_button_lights_1));
   CLKINVX2 g16852 (.Y(n_151),
	.A(FE_OFN3_call_button_lights_9));
   CLKINVX2 g16857 (.Y(n_145),
	.A(FE_OFN25_panel_button_lights_3));
   CLKINVX2 g16864 (.Y(n_142),
	.A(floor_logic_inst_n_359));
   CLKINVX2 g16865 (.Y(n_141),
	.A(elevator_floor_selector[1]));
   CLKINVX2 g16874 (.Y(n_122),
	.A(FE_OFN38_elevator_fsm_inst_counter_state_1__1627));
   CLKINVX2 g16917 (.Y(n_89),
	.A(floor_logic_inst_n_246));
   CLKINVX1 g16918 (.Y(n_88),
	.A(panel_buttons[8]));
   CLKINVX1 g16919 (.Y(n_87),
	.A(panel_buttons[4]));
   CLKINVX1 g16920 (.Y(n_86),
	.A(floor_call_buttons[8]));
   CLKINVX2 g16932 (.Y(n_74),
	.A(FE_OFN15_call_button_lights_0));
   CLKINVX2 g16934 (.Y(n_72),
	.A(FE_OFN26_panel_button_lights_2));
   CLKINVX2 g16936 (.Y(n_70),
	.A(FE_OFN29_panel_button_lights_0));
   CLKINVX2 g16941 (.Y(n_61),
	.A(FE_OFN11_call_button_lights_3));
   CLKINVX2 g16949 (.Y(n_57),
	.A(FE_OFN13_call_button_lights_1));
   CLKINVX2 g16951 (.Y(n_52),
	.A(FE_OFN17_panel_button_lights_9));
   CLKINVX2 g16956 (.Y(n_47),
	.A(FE_OFN8_call_button_lights_5));
   INVX2 g16961 (.Y(n_45),
	.A(FE_OFN11_elevator_fsm_inst_counter_state_4__1630));
   INVX1 g16967 (.Y(n_37),
	.A(FE_OFN37_elevator_floor_selector_0));
   CLKINVX2 g16970 (.Y(n_36),
	.A(elevator_floor_selector[2]));
   CLKINVX2 g17005 (.Y(n_2),
	.A(FE_OFN39_elevator_fsm_inst_counter_state_2__1628));
   CLKINVX1 g17007 (.Y(n_0),
	.A(FE_OFN0_reset_n));
endmodule

