
// Generated by Cadence Genus(TM) Synthesis Solution 23.14-s090_1
// Generated on: Sep 28 2025 23:44:58 EDT (Sep 29 2025 03:44:58 UTC)

// Verification Directory fv/elevator_top 

module button_debouncer_434(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED, UNCONNECTED0, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED));
  AND2X1 g73__2398(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED0));
  NOR2X1 g74__5107(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer_435(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED1, UNCONNECTED2, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED1));
  AND2X1 g73__6260(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED2));
  NOR2X1 g74__4319(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module elevator_fsm(clock, reset_n, elevator_floor_selector,
     emergency_stop, activate_elevator, weight_sensor, power_switch,
     direction_selector, counter_state, control_output);
  input clock, reset_n, emergency_stop, activate_elevator,
       weight_sensor, power_switch, direction_selector;
  input [3:0] elevator_floor_selector;
  output [4:0] counter_state;
  output [10:0] control_output;
  wire clock, reset_n, emergency_stop, activate_elevator,
       weight_sensor, power_switch, direction_selector;
  wire [3:0] elevator_floor_selector;
  wire [4:0] counter_state;
  wire [10:0] control_output;
  wire \counter_state[1]_1627 , \counter_state[2]_1628 ,
       \counter_state[3]_1629 , \counter_state[4]_1630 , n_0, n_1, n_2,
       n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_133, n_134, n_136, n_138, n_139, n_140, n_141, n_142;
  wire n_143, n_144, n_145, n_146, n_147, n_148, n_149, n_150;
  wire n_151, n_152, n_153, n_154, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_213, n_214, n_215, n_216, n_217, n_218;
  wire n_220, n_221, n_222, n_223, n_224, n_225, n_226, n_227;
  wire n_228, n_229, n_230, n_231, n_232, n_233, n_234, n_235;
  wire n_236, n_237, n_239, n_240, n_241, n_260, n_261;
  CLKINVX1 g8395(.A (weight_sensor), .Y (n_237));
  OAI221X1 g8727__8428(.A0 (n_4), .A1 (n_240), .B0 (control_output[7]),
       .B1 (n_232), .C0 (n_236), .Y (control_output[8]));
  OAI221X1 g8728__5526(.A0 (\counter_state[2]_1628 ), .A1 (n_233), .B0
       (n_0), .B1 (n_222), .C0 (n_225), .Y (control_output[9]));
  INVX2 g8729(.A (n_235), .Y (n_236));
  OAI221X1 g8730__6783(.A0 (n_241), .A1 (n_230), .B0
       (\counter_state[2]_1628 ), .B1 (n_223), .C0 (n_234), .Y
       (control_output[10]));
  OAI222X1 g8731__3680(.A0 (\counter_state[3]_1629 ), .A1 (n_225), .B0
       (\counter_state[1]_1627 ), .B1 (n_231), .C0 (n_216), .C1
       (n_214), .Y (n_235));
  OAI211X1 g8732__1617(.A0 (\counter_state[2]_1628 ), .A1 (n_228), .B0
       (n_240), .C0 (n_234), .Y (control_output[4]));
  OAI221X1 g8733__2802(.A0 (n_241), .A1 (n_217), .B0 (n_214), .B1
       (n_220), .C0 (n_231), .Y (control_output[2]));
  OAI21X1 g8734__1705(.A0 (n_216), .A1 (n_224), .B0 (n_229), .Y
       (control_output[3]));
  CLKINVX1 g8735(.A (control_output[6]), .Y (n_234));
  NOR2X1 g8736__5122(.A (n_221), .B (n_226), .Y (n_233));
  NOR2X1 g8737__8246(.A (n_221), .B (n_227), .Y (n_232));
  NOR2X1 g8738__7098(.A (n_216), .B (n_225), .Y (control_output[6]));
  AOI21X1 g8739__6131(.A0 (\counter_state[2]_1628 ), .A1 (n_214), .B0
       (n_8), .Y (n_230));
  NAND3X1 g8740__1881(.A (\counter_state[2]_1628 ), .B (n_217), .C
       (n_218), .Y (n_229));
  MX2X1 g8741__5115(.A (n_241), .B (n_220), .S0 (\counter_state[2]_1628
       ), .Y (n_231));
  NAND2X1 g8742__7482(.A (n_5), .B (n_214), .Y (n_228));
  NOR2X1 g8743__4733(.A (\counter_state[4]_1630 ), .B (n_239), .Y
       (n_227));
  NOR2X1 g8744__6161(.A (control_output[7]), .B (n_216), .Y (n_226));
  CLKINVX2 g8745(.A (n_224), .Y (n_225));
  OR2X1 g8746__9315(.A (n_220), .B (n_213), .Y (n_223));
  AOI21X1 g8747__9945(.A0 (\counter_state[1]_1627 ), .A1 (n_5), .B0
       (n_215), .Y (n_222));
  NOR2X1 g8748__2883(.A (n_0), .B (n_214), .Y (n_224));
  INVX1 g8749(.A (n_239), .Y (n_8));
  CLKINVX2 g8750(.A (n_218), .Y (n_241));
  NOR2X1 g8751__2346(.A (\counter_state[1]_1627 ), .B (n_5), .Y
       (n_221));
  NAND2X1 g8752__1666(.A (\counter_state[3]_1629 ), .B (n_5), .Y
       (n_220));
  NAND2X1 g8753__7410(.A (\counter_state[1]_1627 ), .B (n_0), .Y
       (n_239));
  NOR2X1 g8754__6417(.A (\counter_state[3]_1629 ), .B (n_5), .Y
       (n_218));
  CLKINVX2 g8755(.A (n_215), .Y (n_240));
  INVX1 g8756(.A (n_214), .Y (n_213));
  OR2X2 g8757__5477(.A (control_output[7]), .B (\counter_state[1]_1627
       ), .Y (n_217));
  NAND2X1 g8758__2398(.A (\counter_state[3]_1629 ), .B
       (\counter_state[4]_1630 ), .Y (n_216));
  NOR2X1 g8759__5107(.A (\counter_state[3]_1629 ), .B
       (\counter_state[4]_1630 ), .Y (n_215));
  NAND2X1 g8760__6260(.A (control_output[7]), .B
       (\counter_state[1]_1627 ), .Y (n_214));
  DFFRX4 \counter_state_reg[0] (.RN (reset_n), .CK (clock), .D (n_207),
       .Q (control_output[7]), .QN (n_2));
  DFFRX1 \counter_state_reg[1] (.RN (reset_n), .CK (clock), .D (n_208),
       .Q (\counter_state[1]_1627 ), .QN (n_4));
  DFFRX1 \counter_state_reg[2] (.RN (reset_n), .CK (clock), .D (n_209),
       .Q (\counter_state[2]_1628 ), .QN (n_0));
  DFFRX1 \counter_state_reg[3] (.RN (reset_n), .CK (clock), .D (n_206),
       .Q (\counter_state[3]_1629 ), .QN (n_1));
  DFFRX1 \counter_state_reg[4] (.RN (reset_n), .CK (clock), .D (n_203),
       .Q (\counter_state[4]_1630 ), .QN (n_5));
  OAI221X1 g11208__4319(.A0 (n_5), .A1 (n_201), .B0 (n_240), .B1
       (n_185), .C0 (n_196), .Y (n_209));
  OR2X1 g11210__8428(.A (n_191), .B (n_204), .Y (n_208));
  INVX1 g11212(.A (n_205), .Y (n_207));
  OR4X1 g11213__5526(.A (n_200), .B (n_198), .C (n_183), .D (n_194), .Y
       (n_206));
  AOI221X1 g11214__6783(.A0 (\counter_state[4]_1630 ), .A1 (n_202), .B0
       (n_5), .B1 (n_182), .C0 (n_184), .Y (n_205));
  OAI221X1 g11215__3680(.A0 (n_241), .A1 (n_193), .B0
       (\counter_state[4]_1630 ), .B1 (n_178), .C0 (n_199), .Y (n_204));
  OAI221X1 g11216__1617(.A0 (\counter_state[4]_1630 ), .A1 (n_192), .B0
       (n_241), .B1 (n_168), .C0 (n_197), .Y (n_203));
  OAI222X1 g11217__2802(.A0 (n_36), .A1 (n_161), .B0
       (\counter_state[3]_1629 ), .B1 (n_186), .C0 (n_25), .C1 (n_152),
       .Y (n_202));
  AOI222X1 g11218__1705(.A0 (n_26), .A1 (n_181), .B0 (n_35), .B1
       (n_173), .C0 (n_1), .C1 (n_195), .Y (n_201));
  AOI21X1 g11219__5122(.A0 (n_102), .A1 (n_189), .B0 (n_241), .Y
       (n_200));
  OAI211X1 g11220__8246(.A0 (n_180), .A1 (n_170), .B0
       (\counter_state[4]_1630 ), .C0 (\counter_state[3]_1629 ), .Y
       (n_199));
  CLKINVX2 g11221(.A (n_197), .Y (n_198));
  NAND4X1 g11222__7098(.A (n_5), .B (\counter_state[3]_1629 ), .C
       (n_121), .D (n_177), .Y (n_196));
  NAND3X1 g11223__6131(.A (\counter_state[4]_1630 ), .B
       (\counter_state[3]_1629 ), .C (n_190), .Y (n_197));
  OAI221X1 g11224__1881(.A0 (n_63), .A1 (n_31), .B0 (n_21), .B1 (n_19),
       .C0 (n_188), .Y (n_195));
  NOR3X1 g11225__5115(.A (\counter_state[4]_1630 ), .B (n_1), .C
       (n_175), .Y (n_194));
  AOI221X1 g11226__7482(.A0 (n_95), .A1 (n_53), .B0 (n_15), .B1 (n_18),
       .C0 (n_187), .Y (n_193));
  AOI222X1 g11227__4733(.A0 (n_35), .A1 (n_146), .B0 (n_1), .B1
       (n_172), .C0 (\counter_state[3]_1629 ), .C1 (n_112), .Y (n_192));
  AOI221X1 g11228__6161(.A0 (n_4), .A1 (n_159), .B0
       (\counter_state[1]_1627 ), .B1 (n_87), .C0 (n_240), .Y (n_191));
  OAI221X1 g11229__9315(.A0 (n_239), .A1 (n_115), .B0 (n_9), .B1
       (n_21), .C0 (n_176), .Y (n_190));
  OAI21X1 g11230__9945(.A0 (\counter_state[1]_1627 ), .A1 (n_167), .B0
       (n_179), .Y (n_189));
  AOI222X1 g11231__2883(.A0 (n_89), .A1 (n_53), .B0
       (\counter_state[1]_1627 ), .B1 (n_160), .C0 (n_15), .C1 (n_103),
       .Y (n_188));
  OAI22X1 g11232__2346(.A0 (\counter_state[1]_1627 ), .A1 (n_171), .B0
       (n_4), .B1 (n_142), .Y (n_187));
  AOI22X1 g11233__1666(.A0 (\counter_state[1]_1627 ), .A1 (n_144), .B0
       (n_4), .B1 (n_169), .Y (n_186));
  OAI211X1 g11234__7410(.A0 (n_239), .A1 (n_70), .B0 (n_109), .C0
       (n_166), .Y (n_185));
  AOI21X1 g11235__6417(.A0 (n_11), .A1 (n_153), .B0 (n_240), .Y
       (n_184));
  AOI211X1 g11236__5477(.A0 (\counter_state[1]_1627 ), .A1 (n_114), .B0
       (n_240), .C0 (n_158), .Y (n_183));
  OAI22X1 g11237__2398(.A0 (n_36), .A1 (n_165), .B0 (n_25), .B1
       (n_156), .Y (n_182));
  NAND3X1 g11238__5107(.A (n_40), .B (n_31), .C (n_162), .Y (n_181));
  INVX1 g11239(.A (n_174), .Y (n_180));
  NAND3X1 g11240__6260(.A (\counter_state[1]_1627 ), .B (n_49), .C
       (n_154), .Y (n_179));
  AOI22X1 g11241__4319(.A0 (n_26), .A1 (n_261), .B0 (n_19), .B1
       (n_148), .Y (n_178));
  AOI222X1 g11242__8428(.A0 (\counter_state[1]_1627 ), .A1 (n_131), .B0
       (\counter_state[1]_1627 ), .B1 (n_149), .C0 (n_93), .C1 (n_133),
       .Y (n_177));
  AOI211X1 g11243__5526(.A0 (n_9), .A1 (n_15), .B0 (n_127), .C0
       (n_170), .Y (n_176));
  OAI221X1 g11244__6783(.A0 (n_4), .A1 (n_147), .B0 (n_14), .B1 (n_67),
       .C0 (n_121), .Y (n_175));
  AOI222X1 g11245__3680(.A0 (n_4), .A1 (n_150), .B0 (n_123), .B1
       (n_53), .C0 (n_8), .C1 (n_122), .Y (n_174));
  NAND2X1 g11246__1617(.A (n_40), .B (n_164), .Y (n_173));
  OR2X1 g11247__2802(.A (emergency_stop), .B (n_163), .Y (n_172));
  AOI21X1 g11248__1705(.A0 (n_69), .A1 (n_16), .B0 (n_167), .Y (n_171));
  OAI221X1 g11249__5122(.A0 (\counter_state[2]_1628 ), .A1 (n_126), .B0
       (n_33), .B1 (n_128), .C0 (n_54), .Y (n_169));
  AOI221X1 g11250__8246(.A0 (\counter_state[1]_1627 ), .A1 (n_84), .B0
       (n_4), .B1 (n_83), .C0 (n_141), .Y (n_168));
  AOI21X1 g11251__7098(.A0 (n_17), .A1 (n_145), .B0 (n_4), .Y (n_170));
  OAI22X1 g11252__6131(.A0 (n_80), .A1 (n_133), .B0
       (control_output[7]), .B1 (n_31), .Y (n_166));
  NAND3X1 g11253__1881(.A (n_98), .B (n_86), .C (n_129), .Y (n_165));
  AOI222X1 g11254__5115(.A0 (n_72), .A1 (n_48), .B0 (n_30), .B1 (n_81),
       .C0 (\counter_state[2]_1628 ), .C1 (n_136), .Y (n_164));
  OAI211X1 g11255__7482(.A0 (n_21), .A1 (n_120), .B0 (n_109), .C0
       (n_99), .Y (n_163));
  AOI222X1 g11256__4733(.A0 (control_output[7]), .A1 (n_91), .B0
       (\counter_state[2]_1628 ), .B1 (n_116), .C0 (n_69), .C1 (n_48),
       .Y (n_162));
  AOI221X1 g11257__6161(.A0 (n_30), .A1 (n_122), .B0
       (\counter_state[2]_1628 ), .B1 (n_51), .C0 (n_140), .Y (n_161));
  NAND2X1 g11258__9315(.A (n_49), .B (n_138), .Y (n_167));
  INVX1 g11259(.A (n_157), .Y (n_160));
  CLKINVX2 g11260(.A (n_151), .Y (n_159));
  OAI22X1 g11261__9945(.A0 (n_21), .A1 (n_134), .B0 (n_65), .B1
       (n_132), .Y (n_158));
  AOI222X1 g11262__2883(.A0 (n_24), .A1 (n_30), .B0
       (\counter_state[2]_1628 ), .B1 (n_106), .C0
       (direction_selector), .C1 (n_95), .Y (n_157));
  OAI221X1 g11263__2346(.A0 (n_61), .A1 (n_31), .B0 (n_55), .B1 (n_54),
       .C0 (n_139), .Y (n_156));
  AOI211X1 g11265__7410(.A0 (n_13), .A1 (n_105), .B0 (n_59), .C0
       (n_76), .Y (n_154));
  AOI221X1 g11266__6417(.A0 (control_output[7]), .A1 (n_45), .B0
       (n_14), .B1 (n_111), .C0 (n_65), .Y (n_153));
  AOI222X1 g11267__5477(.A0 (direction_selector), .A1 (n_34), .B0
       (n_13), .B1 (n_124), .C0 (n_30), .C1 (n_125), .Y (n_152));
  OAI222X1 g11268__2398(.A0 (n_30), .A1 (n_107), .B0 (n_29), .B1
       (n_120), .C0 (n_0), .C1 (n_93), .Y (n_151));
  OAI21X1 g11269__5107(.A0 (n_29), .A1 (n_125), .B0 (n_40), .Y (n_150));
  OAI21X1 g11270__6260(.A0 (n_17), .A1 (n_117), .B0 (n_108), .Y
       (n_149));
  NOR2X1 g11271__4319(.A (n_36), .B (n_130), .Y (n_148));
  AOI21X1 g11272__8428(.A0 (n_74), .A1 (n_18), .B0 (n_130), .Y (n_147));
  OAI211X1 g11273__5526(.A0 (\counter_state[2]_1628 ), .A1 (n_22), .B0
       (n_108), .C0 (n_85), .Y (n_146));
  NAND2X1 g11274__6783(.A (\counter_state[2]_1628 ), .B (n_136), .Y
       (n_145));
  INVX1 g11275(.A (n_143), .Y (n_144));
  AOI222X1 g11276__3680(.A0 (n_13), .A1 (n_106), .B0 (n_90), .B1
       (n_16), .C0 (n_34), .C1 (n_47), .Y (n_143));
  AOI21X1 g11277__1617(.A0 (n_19), .A1 (n_106), .B0 (n_47), .Y (n_142));
  NAND3X1 g11278__2802(.A (n_44), .B (n_29), .C (n_118), .Y (n_141));
  OAI22X1 g11279__1705(.A0 (n_22), .A1 (n_113), .B0 (n_17), .B1 (n_33),
       .Y (n_140));
  AOI22X1 g11280__5122(.A0 (n_0), .A1 (n_110), .B0 (n_13), .B1 (n_33),
       .Y (n_139));
  AOI222X1 g11281__8246(.A0 (n_2), .A1 (n_79), .B0 (n_23), .B1 (n_13),
       .C0 (control_output[7]), .C1 (n_59), .Y (n_138));
  INVX1 g11284(.A (n_132), .Y (n_133));
  OAI211X1 g11285__6131(.A0 (n_66), .A1 (control_output[7]), .B0
       (n_27), .C0 (n_50), .Y (n_136));
  AND2X1 g11286__1881(.A (n_107), .B (n_30), .Y (n_131));
  NAND2X1 g11287__5115(.A (n_93), .B (n_107), .Y (n_134));
  NAND2X1 g11288__7482(.A (n_15), .B (n_120), .Y (n_132));
  AOI22X1 g11289__4733(.A0 (n_16), .A1 (n_97), .B0 (n_2), .B1 (n_88),
       .Y (n_129));
  AOI21X1 g11290__6161(.A0 (n_13), .A1 (n_94), .B0 (n_30), .Y (n_128));
  AOI21X1 g11291__9315(.A0 (n_6), .A1 (n_82), .B0
       (\counter_state[1]_1627 ), .Y (n_127));
  NAND3X1 g11292__9945(.A (n_98), .B (n_54), .C (n_85), .Y (n_130));
  CLKINVX1 g11293(.A (n_119), .Y (n_126));
  INVX1 g11294(.A (n_123), .Y (n_124));
  AOI21X1 g11295__2883(.A0 (n_62), .A1 (n_27), .B0 (n_69), .Y (n_119));
  AOI211X1 g11296__2346(.A0 (elevator_floor_selector[2]), .A1 (n_37),
       .B0 (n_42), .C0 (n_77), .Y (n_118));
  OR2X1 g11297__1666(.A (n_23), .B (n_97), .Y (n_117));
  NAND2X1 g11298__7410(.A (n_9), .B (n_82), .Y (n_116));
  AOI21X1 g11299__6417(.A0 (n_71), .A1 (n_2), .B0 (n_81), .Y (n_115));
  AOI21X1 g11300__5477(.A0 (n_31), .A1 (n_68), .B0 (emergency_stop), .Y
       (n_114));
  AOI21X1 g11301__2398(.A0 (n_73), .A1 (control_output[7]), .B0 (n_69),
       .Y (n_125));
  NAND2X1 g11302__5107(.A (n_61), .B (n_96), .Y (n_123));
  NOR2X1 g11303__6260(.A (n_72), .B (n_81), .Y (n_122));
  NAND4X1 g11304__4319(.A (direction_selector), .B (n_55), .C (n_20),
       .D (n_44), .Y (n_121));
  AOI21X1 g11305__8428(.A0 (control_output[7]), .A1 (n_68), .B0
       (emergency_stop), .Y (n_120));
  CLKINVX1 g11306(.A (n_101), .Y (n_113));
  INVX1 g11307(.A (n_100), .Y (n_112));
  INVX1 g11308(.A (n_110), .Y (n_111));
  CLKINVX2 g11309(.A (n_105), .Y (n_106));
  AOI21X1 g11310__5526(.A0 (n_61), .A1 (n_2), .B0 (n_13), .Y (n_104));
  OR2X1 g11311__6783(.A (n_24), .B (n_78), .Y (n_103));
  NAND3X1 g11312__3680(.A (n_60), .B (control_output[7]), .C (n_53), .Y
       (n_102));
  OAI21X1 g11313__1617(.A0 (n_66), .A1 (n_0), .B0 (n_31), .Y (n_101));
  AOI21X1 g11314__2802(.A0 (n_15), .A1 (n_70), .B0 (n_24), .Y (n_100));
  OAI21X1 g11315__1705(.A0 (control_output[7]), .A1 (n_14), .B0 (n_92),
       .Y (n_99));
  AOI22X1 g11316__5122(.A0 (control_output[7]), .A1 (n_67), .B0 (n_2),
       .B1 (n_70), .Y (n_110));
  NAND3X1 g11317__8246(.A (\counter_state[1]_1627 ), .B
       (\counter_state[2]_1628 ), .C (n_68), .Y (n_109));
  NAND3X1 g11318__7098(.A (n_73), .B (control_output[7]), .C (n_32), .Y
       (n_108));
  AOI21X1 g11319__6131(.A0 (n_2), .A1 (n_68), .B0 (emergency_stop), .Y
       (n_107));
  OAI22X1 g11320__1881(.A0 (elevator_floor_selector[0]), .A1 (n_64),
       .B0 (n_57), .B1 (n_2), .Y (n_105));
  INVX1 g11321(.A (n_97), .Y (n_96));
  INVX1 g11322(.A (n_95), .Y (n_94));
  CLKINVX2 g11323(.A (n_93), .Y (n_92));
  NOR2X1 g11324__5115(.A (n_73), .B (n_29), .Y (n_91));
  OR2X1 g11325__7482(.A (n_60), .B (n_64), .Y (n_90));
  NAND2X1 g11326__4733(.A (n_60), .B (control_output[7]), .Y (n_89));
  NOR2X1 g11327__6161(.A (\counter_state[2]_1628 ), .B (n_70), .Y
       (n_88));
  NOR2X1 g11328__9315(.A (n_18), .B (n_67), .Y (n_87));
  NAND2X1 g11329__9945(.A (n_72), .B (n_32), .Y (n_98));
  NOR2X1 g11330__2883(.A (n_74), .B (n_2), .Y (n_97));
  NOR2X1 g11331__2346(.A (n_60), .B (n_2), .Y (n_95));
  NAND2X1 g11332__1666(.A (n_6), .B (n_68), .Y (n_93));
  INVX1 g11333(.A (n_75), .Y (n_86));
  INVX1 g11334(.A (n_83), .Y (n_84));
  NOR2X1 g11335__7410(.A (n_21), .B (n_67), .Y (n_80));
  AND2X1 g11336__6417(.A (n_32), .B (n_63), .Y (n_79));
  NOR2X1 g11337__5477(.A (n_62), .B (n_43), .Y (n_78));
  OAI222X1 g11338__2398(.A0 (elevator_floor_selector[3]), .A1
       (elevator_floor_selector[2]), .B0 (n_39), .B1 (n_31), .C0
       (n_28), .C1 (control_output[7]), .Y (n_77));
  AND3X2 g11339__5107(.A (n_46), .B (n_16), .C (n_44), .Y (n_76));
  OAI22X1 g11340__6260(.A0 (n_34), .A1 (n_47), .B0 (n_58), .B1 (n_54),
       .Y (n_75));
  NAND2X1 g11341__4319(.A (n_48), .B (n_68), .Y (n_85));
  AOI221X1 g11342__8428(.A0 (control_output[7]), .A1 (n_12), .B0
       (elevator_floor_selector[2]), .B1 (n_0), .C0 (n_32), .Y (n_83));
  AOI22X1 g11343__5526(.A0 (n_52), .A1 (n_2), .B0 (n_56), .B1
       (control_output[7]), .Y (n_82));
  AOI21X1 g11344__6783(.A0 (elevator_floor_selector[0]), .A1 (n_55),
       .B0 (n_2), .Y (n_81));
  INVX2 g11345(.A (n_71), .Y (n_72));
  CLKINVX2 g11346(.A (n_68), .Y (n_67));
  NOR2X1 g11347__3680(.A (elevator_floor_selector[2]), .B (n_56), .Y
       (n_74));
  OR2X2 g11348__1617(.A (n_9), .B (n_56), .Y (n_73));
  NAND2X1 g11349__2802(.A (n_10), .B (n_58), .Y (n_71));
  NAND2X1 g11350__1705(.A (n_11), .B (n_45), .Y (n_70));
  AND2X2 g11351__5122(.A (n_10), .B (n_57), .Y (n_69));
  NOR2X1 g11352__8246(.A (emergency_stop), .B (n_45), .Y (n_68));
  AND3X2 g11353__7098(.A (n_10), .B (n_9), .C (n_41), .Y (n_66));
  NOR2X1 g11354__6131(.A (n_27), .B (n_45), .Y (n_65));
  NOR2X1 g11355__1881(.A (n_46), .B (control_output[7]), .Y (n_64));
  AND3X2 g11356__5115(.A (elevator_floor_selector[3]), .B (n_10), .C
       (n_39), .Y (n_63));
  NAND2X1 g11357__7482(.A (direction_selector), .B (n_57), .Y (n_62));
  NAND2X1 g11358__4733(.A (n_10), .B (n_55), .Y (n_61));
  AND2X2 g11359__6161(.A (elevator_floor_selector[0]), .B (n_46), .Y
       (n_60));
  OR2X1 g11360__9315(.A (elevator_floor_selector[0]), .B (n_37), .Y
       (n_52));
  NOR2X1 g11361__9945(.A (n_11), .B (n_31), .Y (n_59));
  AND2X2 g11362__2883(.A (elevator_floor_selector[2]), .B (n_41), .Y
       (n_58));
  NOR2X1 g11363__2346(.A (n_9), .B (n_37), .Y (n_57));
  NAND2X1 g11364__1666(.A (elevator_floor_selector[0]), .B (n_41), .Y
       (n_56));
  NOR2X1 g11365__7410(.A (elevator_floor_selector[2]), .B (n_37), .Y
       (n_55));
  NAND2X1 g11366__6417(.A (\counter_state[2]_1628 ), .B (n_18), .Y
       (n_54));
  AND2X1 g11367__5477(.A (n_13), .B (n_4), .Y (n_53));
  INVX1 g11368(.A (n_50), .Y (n_51));
  CLKINVX2 g11369(.A (n_43), .Y (n_44));
  AOI21X1 g11370__2398(.A0 (n_10), .A1 (\counter_state[2]_1628 ), .B0
       (n_38), .Y (n_42));
  OAI21X1 g11371__5107(.A0 (power_switch), .A1 (emergency_stop), .B0
       (control_output[7]), .Y (n_50));
  NAND2X1 g11372__6260(.A (n_30), .B (n_24), .Y (n_49));
  NOR2X1 g11373__4319(.A (control_output[7]), .B (n_29), .Y (n_48));
  NOR2X1 g11374__8428(.A (n_16), .B (n_13), .Y (n_47));
  NOR3X1 g11375__5526(.A (n_7), .B (elevator_floor_selector[1]), .C
       (elevator_floor_selector[2]), .Y (n_46));
  NAND3X1 g11376__6783(.A (power_switch), .B (n_237), .C
       (activate_elevator), .Y (n_45));
  OAI22X1 g11377__3680(.A0 (elevator_floor_selector[0]), .A1 (n_2), .B0
       (n_10), .B1 (control_output[7]), .Y (n_43));
  INVX1 g11378(.A (n_38), .Y (n_39));
  CLKINVX2 g11379(.A (n_36), .Y (n_35));
  CLKINVX2 g11380(.A (n_34), .Y (n_33));
  CLKINVX2 g11381(.A (n_32), .Y (n_31));
  CLKINVX2 g11382(.A (n_30), .Y (n_29));
  NAND2X1 g11383__1617(.A (elevator_floor_selector[1]), .B (n_6), .Y
       (n_28));
  NOR2X1 g11384__2802(.A (elevator_floor_selector[3]), .B
       (elevator_floor_selector[1]), .Y (n_41));
  NAND2X1 g11385__1705(.A (direction_selector), .B (emergency_stop), .Y
       (n_40));
  NAND2X1 g11386__5122(.A (elevator_floor_selector[1]), .B (n_9), .Y
       (n_38));
  NAND2X1 g11387__8246(.A (n_7), .B (elevator_floor_selector[1]), .Y
       (n_37));
  NAND2X1 g11388__7098(.A (\counter_state[3]_1629 ), .B
       (\counter_state[1]_1627 ), .Y (n_36));
  NAND2X1 g11389__6131(.A (n_11), .B (n_2), .Y (n_34));
  NOR2X1 g11390__1881(.A (n_6), .B (n_0), .Y (n_32));
  NOR2X1 g11391__5115(.A (direction_selector), .B
       (\counter_state[2]_1628 ), .Y (n_30));
  CLKINVX1 g11392(.A (n_26), .Y (n_25));
  CLKINVX1 g11393(.A (n_23), .Y (n_22));
  CLKINVX1 g11394(.A (n_21), .Y (n_20));
  CLKINVX2 g11395(.A (n_19), .Y (n_18));
  CLKINVX2 g11396(.A (n_17), .Y (n_16));
  CLKINVX2 g11397(.A (n_15), .Y (n_14));
  NOR2X1 g11398__7482(.A (elevator_floor_selector[2]), .B (n_0), .Y
       (n_12));
  NAND2X1 g11399__4733(.A (direction_selector), .B (n_2), .Y (n_27));
  NOR2X1 g11400__6161(.A (n_1), .B (\counter_state[1]_1627 ), .Y
       (n_26));
  NOR2X1 g11401__9315(.A (direction_selector), .B (n_11), .Y (n_24));
  NOR2X1 g11402__9945(.A (n_11), .B (control_output[7]), .Y (n_23));
  NAND2X1 g11403__2883(.A (n_4), .B (\counter_state[2]_1628 ), .Y
       (n_21));
  NAND2X1 g11404__2346(.A (direction_selector), .B (control_output[7]),
       .Y (n_19));
  NAND2X1 g11405__1666(.A (direction_selector), .B (n_0), .Y (n_17));
  NOR2X1 g11406__7410(.A (\counter_state[1]_1627 ), .B
       (\counter_state[2]_1628 ), .Y (n_15));
  NOR2X1 g11407__6417(.A (direction_selector), .B (n_0), .Y (n_13));
  CLKINVX2 g11409(.A (emergency_stop), .Y (n_11));
  CLKINVX2 g11410(.A (elevator_floor_selector[0]), .Y (n_10));
  CLKINVX2 g11411(.A (elevator_floor_selector[2]), .Y (n_9));
  INVX1 g11446(.A (elevator_floor_selector[3]), .Y (n_7));
  CLKINVX2 g11458(.A (direction_selector), .Y (n_6));
  MX2X1 g2(.A (n_134), .B (n_260), .S0 (\counter_state[2]_1628 ), .Y
       (n_261));
  OR2X2 g3(.A (n_24), .B (n_104), .Y (n_260));
endmodule

module button_debouncer_433(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED3, UNCONNECTED4, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED3));
  AND2X1 g73__5477(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED4));
  NOR2X1 g74__2398(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED5, UNCONNECTED6, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED5));
  AND2X1 g73__5107(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED6));
  NOR2X1 g74__6260(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer_456(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED7, UNCONNECTED8, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED7));
  AND2X1 g73__4319(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED8));
  NOR2X1 g74__8428(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer_455(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED9, UNCONNECTED10, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED9));
  AND2X1 g73__5526(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED10));
  NOR2X1 g74__6783(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer_454(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED11, UNCONNECTED12, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED11));
  AND2X1 g73__3680(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED12));
  NOR2X1 g74__1617(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer_453(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED13, UNCONNECTED14, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED13));
  AND2X1 g73__2802(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED14));
  NOR2X1 g74__1705(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer_452(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED15, UNCONNECTED16, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED15));
  AND2X1 g73__5122(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED16));
  NOR2X1 g74__8246(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer_451(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED17, UNCONNECTED18, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED17));
  AND2X1 g73__7098(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED18));
  NOR2X1 g74__6131(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer_450(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED19, UNCONNECTED20, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED19));
  AND2X1 g73__1881(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED20));
  NOR2X1 g74__5115(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer_449(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED21, UNCONNECTED22, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED21));
  AND2X1 g73__7482(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED22));
  NOR2X1 g74__4733(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer_448(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED23, UNCONNECTED24, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED23));
  AND2X1 g73__6161(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED24));
  NOR2X1 g74__9315(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer_447(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED25, UNCONNECTED26, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED25));
  AND2X1 g73__9945(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED26));
  NOR2X1 g74__2883(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module floor_logic_control_unit(clock, reset_n, floor_call_buttons,
     panel_buttons, door_open_btn, door_close_btn, emergency_btn,
     power_switch, current_floor_state, elevator_state,
     elevator_moving, elevator_direction, elevator_floor_selector,
     direction_selector, activate_elevator, call_button_lights,
     panel_button_lights, door_open_allowed, door_close_allowed);
  input clock, reset_n, door_open_btn, door_close_btn, emergency_btn,
       power_switch, elevator_moving, elevator_direction;
  input [10:0] floor_call_buttons, panel_buttons;
  input [3:0] current_floor_state;
  input [4:0] elevator_state;
  output [3:0] elevator_floor_selector;
  output direction_selector, activate_elevator, door_open_allowed,
       door_close_allowed;
  output [10:0] call_button_lights, panel_button_lights;
  wire clock, reset_n, door_open_btn, door_close_btn, emergency_btn,
       power_switch, elevator_moving, elevator_direction;
  wire [10:0] floor_call_buttons, panel_buttons;
  wire [3:0] current_floor_state;
  wire [4:0] elevator_state;
  wire [3:0] elevator_floor_selector;
  wire direction_selector, activate_elevator, door_open_allowed,
       door_close_allowed;
  wire [10:0] call_button_lights, panel_button_lights;
  wire UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30,
       UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34;
  wire UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38,
       UNCONNECTED39, UNCONNECTED40, UNCONNECTED41, UNCONNECTED42;
  wire UNCONNECTED43, UNCONNECTED44, UNCONNECTED45, UNCONNECTED46,
       UNCONNECTED47, UNCONNECTED48, UNCONNECTED49, n_0;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_90;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144, n_145, n_146, n_147, n_148;
  wire n_149, n_150, n_151, n_152, n_153, n_154, n_155, n_156;
  wire n_157, n_158, n_159, n_160, n_161, n_162, n_163, n_164;
  wire n_165, n_166, n_167, n_168, n_169, n_170, n_171, n_174;
  wire n_175, n_176, n_177, n_178, n_179, n_180, n_181, n_182;
  wire n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190;
  wire n_191, n_192, n_193, n_194, n_195, n_196, n_197, n_198;
  wire n_199, n_200, n_201, n_202, n_203, n_204, n_205, n_206;
  wire n_207, n_208, n_209, n_210, n_211, n_212, n_213, n_214;
  wire n_215, n_216, n_217, n_218, n_219, n_220, n_221, n_222;
  wire n_223, n_224, n_225, n_226, n_227, n_228, n_230, n_231;
  wire n_232, n_233, n_234, n_235, n_236, n_237, n_238, n_240;
  wire n_241, n_245, n_246, n_247, n_248, n_262, n_286, n_287;
  wire n_288, n_289, n_290, n_291;
  CLKAND2X2 g10928__2346(.A (reset_n), .B (n_240), .Y
       (activate_elevator));
  OAI21X1 g10929__1666(.A0 (elevator_moving), .A1 (n_262), .B0
       (reset_n), .Y (n_241));
  INVX1 g10930(.A (n_240), .Y (n_286));
  NOR3X1 g10931__7410(.A (emergency_btn), .B (n_245), .C (n_26), .Y
       (n_240));
  CLKINVX2 g10932(.A (n_262), .Y (n_26));
  NAND4X1 g10933__6417(.A (n_246), .B (n_248), .C (n_247), .D (n_238),
       .Y (n_262));
  AOI211X1 g10934__5477(.A0 (n_227), .A1 (current_floor_state[3]), .B0
       (n_233), .C0 (n_234), .Y (n_238));
  TLATX1 door_close_allowed_reg(.G (n_237), .D (n_236), .Q
       (door_close_allowed), .QN (UNCONNECTED27));
  TLATX1 door_open_allowed_reg(.G (n_237), .D (n_235), .Q
       (door_open_allowed), .QN (UNCONNECTED28));
  AND2X2 g10937__2398(.A (door_close_btn), .B (n_232), .Y (n_236));
  NAND2X1 g10938__5107(.A (reset_n), .B (n_245), .Y (n_237));
  AND2X2 g10939__6260(.A (door_open_btn), .B (n_232), .Y (n_235));
  CLKXOR2X1 g10940__4319(.A (elevator_floor_selector[2]), .B
       (current_floor_state[2]), .Y (n_234));
  CLKXOR2X1 g10941__8428(.A (elevator_floor_selector[0]), .B
       (current_floor_state[0]), .Y (n_233));
  NAND2X1 g10942__5526(.A (power_switch), .B (n_228), .Y (n_287));
  OR2X1 g10943__6783(.A (n_227), .B (current_floor_state[3]), .Y
       (n_248));
  INVX1 g10944(.A (n_245), .Y (n_232));
  NAND2X1 g10945__3680(.A (n_230), .B (current_floor_state[1]), .Y
       (n_246));
  NAND2X1 g10946__1617(.A (elevator_floor_selector[1]), .B (n_7), .Y
       (n_247));
  NAND2X1 g10947__2802(.A (power_switch), .B (n_231), .Y (n_245));
  INVX2 g10948(.A (elevator_moving), .Y (n_231));
  INVX2 g10950(.A (current_floor_state[1]), .Y (n_7));
  CLKINVX1 g10951(.A (emergency_btn), .Y (n_228));
  DFFRX1 \call_button_lights_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_141), .Q (call_button_lights[0]), .QN (n_1));
  DFFRX1 \call_button_lights_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_169), .Q (call_button_lights[1]), .QN (n_0));
  SDFFRX1 \call_button_lights_reg[2] (.RN (reset_n), .CK (clock), .D
       (n_77), .SI (call_button_lights[2]), .SE (n_170), .Q
       (call_button_lights[2]), .QN (UNCONNECTED29));
  DFFRX1 \call_button_lights_reg[3] (.RN (reset_n), .CK (clock), .D
       (n_183), .Q (call_button_lights[3]), .QN (UNCONNECTED30));
  SDFFRX1 \call_button_lights_reg[4] (.RN (reset_n), .CK (clock), .D
       (n_108), .SI (call_button_lights[4]), .SE (n_178), .Q
       (call_button_lights[4]), .QN (UNCONNECTED31));
  SDFFRX1 \call_button_lights_reg[5] (.RN (reset_n), .CK (clock), .D
       (call_button_lights[5]), .SI (n_75), .SE (n_192), .Q
       (call_button_lights[5]), .QN (UNCONNECTED32));
  SDFFRX1 \call_button_lights_reg[6] (.RN (reset_n), .CK (clock), .D
       (n_105), .SI (call_button_lights[6]), .SE (n_202), .Q
       (call_button_lights[6]), .QN (UNCONNECTED33));
  SDFFRX1 \call_button_lights_reg[7] (.RN (reset_n), .CK (clock), .D
       (n_73), .SI (call_button_lights[7]), .SE (n_197), .Q
       (call_button_lights[7]), .QN (UNCONNECTED34));
  SDFFRX1 \call_button_lights_reg[8] (.RN (reset_n), .CK (clock), .D
       (call_button_lights[8]), .SI (n_106), .SE (n_209), .Q
       (call_button_lights[8]), .QN (UNCONNECTED35));
  SDFFRX1 \call_button_lights_reg[9] (.RN (reset_n), .CK (clock), .D
       (call_button_lights[9]), .SI (n_82), .SE (n_208), .Q
       (call_button_lights[9]), .QN (UNCONNECTED36));
  SDFFRX1 \call_button_lights_reg[10] (.RN (reset_n), .CK (clock), .D
       (call_button_lights[10]), .SI (n_78), .SE (n_207), .Q
       (call_button_lights[10]), .QN (UNCONNECTED37));
  TLATX1 direction_selector_reg(.G (n_28), .D (n_144), .Q
       (direction_selector), .QN (UNCONNECTED38));
  TLATX1 \elevator_floor_selector_reg[0] (.G (n_241), .D (n_226), .Q
       (elevator_floor_selector[0]), .QN (UNCONNECTED39));
  TLATX1 \elevator_floor_selector_reg[1] (.G (n_241), .D (n_224), .Q
       (elevator_floor_selector[1]), .QN (n_230));
  TLATX1 \elevator_floor_selector_reg[2] (.G (n_241), .D (n_222), .Q
       (elevator_floor_selector[2]), .QN (UNCONNECTED40));
  TLATX1 \elevator_floor_selector_reg[3] (.G (n_241), .D (n_219), .Q
       (elevator_floor_selector[3]), .QN (n_227));
  DFFRX1 \panel_button_lights_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_140), .Q (panel_button_lights[0]), .QN (n_3));
  DFFRX1 \panel_button_lights_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_168), .Q (panel_button_lights[1]), .QN (n_2));
  SDFFRX1 \panel_button_lights_reg[2] (.RN (reset_n), .CK (clock), .D
       (n_77), .SI (panel_button_lights[2]), .SE (n_171), .Q
       (panel_button_lights[2]), .QN (UNCONNECTED41));
  DFFRX1 \panel_button_lights_reg[3] (.RN (reset_n), .CK (clock), .D
       (n_184), .Q (panel_button_lights[3]), .QN (UNCONNECTED42));
  SDFFRX1 \panel_button_lights_reg[4] (.RN (reset_n), .CK (clock), .D
       (n_108), .SI (panel_button_lights[4]), .SE (n_179), .Q
       (panel_button_lights[4]), .QN (UNCONNECTED43));
  SDFFRX1 \panel_button_lights_reg[5] (.RN (reset_n), .CK (clock), .D
       (panel_button_lights[5]), .SI (n_75), .SE (n_193), .Q
       (panel_button_lights[5]), .QN (UNCONNECTED44));
  SDFFRX1 \panel_button_lights_reg[6] (.RN (reset_n), .CK (clock), .D
       (n_105), .SI (panel_button_lights[6]), .SE (n_196), .Q
       (panel_button_lights[6]), .QN (UNCONNECTED45));
  SDFFRX1 \panel_button_lights_reg[7] (.RN (reset_n), .CK (clock), .D
       (n_73), .SI (panel_button_lights[7]), .SE (n_198), .Q
       (panel_button_lights[7]), .QN (UNCONNECTED46));
  SDFFRX1 \panel_button_lights_reg[8] (.RN (reset_n), .CK (clock), .D
       (panel_button_lights[8]), .SI (n_106), .SE (n_216), .Q
       (panel_button_lights[8]), .QN (UNCONNECTED47));
  SDFFRX1 \panel_button_lights_reg[9] (.RN (reset_n), .CK (clock), .D
       (panel_button_lights[9]), .SI (n_82), .SE (n_214), .Q
       (panel_button_lights[9]), .QN (UNCONNECTED48));
  SDFFRX1 \panel_button_lights_reg[10] (.RN (reset_n), .CK (clock), .D
       (panel_button_lights[10]), .SI (n_78), .SE (n_215), .Q
       (panel_button_lights[10]), .QN (UNCONNECTED49));
  INVX1 g13402(.A (n_225), .Y (n_226));
  AOI222X1 g13403__1705(.A0 (n_38), .A1 (n_221), .B0
       (current_floor_state[0]), .B1 (n_206), .C0 (n_190), .C1 (n_201),
       .Y (n_225));
  INVX1 g13404(.A (n_223), .Y (n_224));
  AOI222X1 g13405__5122(.A0 (n_56), .A1 (n_218), .B0
       (current_floor_state[1]), .B1 (n_206), .C0 (n_189), .C1 (n_201),
       .Y (n_223));
  INVX1 g13413(.A (n_220), .Y (n_222));
  AOI222X1 g13414__8246(.A0 (n_50), .A1 (n_56), .B0 (n_210), .B1
       (n_213), .C0 (n_104), .C1 (n_97), .Y (n_221));
  AOI222X1 g13415__7098(.A0 (n_97), .A1 (n_212), .B0
       (current_floor_state[2]), .B1 (n_206), .C0 (n_176), .C1 (n_201),
       .Y (n_220));
  INVX1 g13420(.A (n_217), .Y (n_219));
  AOI22X1 g13421__6131(.A0 (n_211), .A1 (n_213), .B0 (n_58), .B1
       (n_97), .Y (n_218));
  AOI222X1 g13422__1881(.A0 (n_116), .A1 (n_204), .B0 (n_161), .B1
       (n_201), .C0 (current_floor_state[3]), .C1 (n_206), .Y (n_217));
  AOI21X1 g13426__5115(.A0 (n_106), .A1 (n_203), .B0 (n_287), .Y
       (n_216));
  AOI21X1 g13427__7482(.A0 (n_78), .A1 (n_199), .B0 (n_121), .Y
       (n_215));
  AOI21X1 g13428__4733(.A0 (n_82), .A1 (n_200), .B0 (n_123), .Y
       (n_214));
  INVX1 g13429(.A (n_212), .Y (n_213));
  NAND2X1 g13430__6161(.A (n_57), .B (n_204), .Y (n_211));
  NOR2X1 g13431__9315(.A (n_116), .B (n_205), .Y (n_212));
  OR3X1 g13434__9945(.A (n_33), .B (n_57), .C (n_205), .Y (n_210));
  AOI21X1 g13435__2883(.A0 (n_106), .A1 (n_194), .B0 (n_287), .Y
       (n_209));
  AOI21X1 g13436__2346(.A0 (n_82), .A1 (n_188), .B0 (n_123), .Y
       (n_208));
  AOI21X1 g13437__1666(.A0 (n_78), .A1 (n_185), .B0 (n_121), .Y
       (n_207));
  CLKINVX2 g13438(.A (n_204), .Y (n_205));
  NAND2X1 g13439__7410(.A (n_117), .B (n_191), .Y (n_203));
  NAND2X1 g13440__6417(.A (n_16), .B (n_187), .Y (n_202));
  NOR2X1 g13441__5477(.A (n_156), .B (n_195), .Y (n_206));
  NOR2X1 g13442__2398(.A (n_157), .B (n_195), .Y (n_204));
  NAND3X1 g13445__5107(.A (panel_buttons[9]), .B (n_118), .C (n_191),
       .Y (n_200));
  NAND4X1 g13446__6260(.A (panel_buttons[10]), .B (n_94), .C (n_118),
       .D (n_191), .Y (n_199));
  OAI21X1 g13447__4319(.A0 (n_74), .A1 (n_182), .B0 (n_125), .Y
       (n_198));
  OAI21X1 g13448__8428(.A0 (n_74), .A1 (n_180), .B0 (n_125), .Y
       (n_197));
  NAND2X1 g13449__5526(.A (n_16), .B (n_186), .Y (n_196));
  AOI211X1 g13450__6783(.A0 (n_147), .A1 (n_174), .B0 (n_4), .C0
       (elevator_direction), .Y (n_201));
  NAND2X1 g13451__3680(.A (n_119), .B (n_181), .Y (n_194));
  AOI21X1 g13452__1617(.A0 (n_75), .A1 (n_175), .B0 (n_122), .Y
       (n_193));
  AOI21X1 g13453__2802(.A0 (n_75), .A1 (n_177), .B0 (n_122), .Y
       (n_192));
  OAI21X1 g13454__1705(.A0 (elevator_direction), .A1 (n_174), .B0
       (reset_n), .Y (n_195));
  AOI222X1 g13457__5122(.A0 (n_127), .A1 (n_161), .B0 (n_158), .B1
       (n_148), .C0 (n_87), .C1 (n_99), .Y (n_190));
  AOI221X1 g13458__8246(.A0 (n_138), .A1 (n_161), .B0 (n_128), .B1
       (n_148), .C0 (n_98), .Y (n_189));
  NAND3X1 g13459__7098(.A (floor_call_buttons[9]), .B (n_120), .C
       (n_181), .Y (n_188));
  OAI21X1 g13460__6131(.A0 (n_131), .A1 (n_289), .B0 (n_105), .Y
       (n_187));
  OAI21X1 g13461__1881(.A0 (n_114), .A1 (n_291), .B0 (n_105), .Y
       (n_186));
  NAND4X1 g13462__5115(.A (floor_call_buttons[10]), .B (n_93), .C
       (n_120), .D (n_181), .Y (n_185));
  AOI211X1 g13463__7482(.A0 (n_43), .A1 (n_73), .B0 (n_115), .C0
       (n_291), .Y (n_191));
  OAI21X1 g13464__4733(.A0 (n_287), .A1 (n_165), .B0 (n_102), .Y
       (n_184));
  OAI21X1 g13465__6161(.A0 (n_287), .A1 (n_166), .B0 (n_103), .Y
       (n_183));
  NOR3X1 g13466__9315(.A (n_13), .B (n_115), .C (n_291), .Y (n_182));
  NOR2X1 g13467__9945(.A (n_146), .B (n_289), .Y (n_180));
  OAI21X1 g13468__2883(.A0 (n_160), .A1 (n_107), .B0 (n_16), .Y
       (n_179));
  OAI21X1 g13469__2346(.A0 (n_159), .A1 (n_107), .B0 (n_16), .Y
       (n_178));
  AOI211X1 g13470__1666(.A0 (n_45), .A1 (n_73), .B0 (n_130), .C0
       (n_289), .Y (n_181));
  NAND2X1 g13471__7410(.A (floor_call_buttons[5]), .B (n_163), .Y
       (n_177));
  NOR2X1 g13472__6417(.A (n_149), .B (n_161), .Y (n_176));
  NAND2X1 g13473__5477(.A (panel_buttons[5]), .B (n_162), .Y (n_175));
  OAI21X1 g13476__2398(.A0 (n_76), .A1 (n_150), .B0 (n_126), .Y
       (n_171));
  NOR4X1 g13477__5107(.A (n_87), .B (n_84), .C (n_128), .D (n_143), .Y
       (n_174));
  OAI21X1 g13478__6260(.A0 (n_76), .A1 (n_151), .B0 (n_126), .Y
       (n_170));
  INVX1 g13481(.A (n_167), .Y (n_169));
  INVX1 g13482(.A (n_164), .Y (n_168));
  AOI22X1 g13483__5526(.A0 (n_16), .A1 (n_145), .B0
       (call_button_lights[1]), .B1 (n_124), .Y (n_167));
  NAND2X1 g13484__6783(.A (n_80), .B (n_154), .Y (n_166));
  NAND2X1 g13485__3680(.A (n_113), .B (n_152), .Y (n_165));
  AOI22X1 g13486__1617(.A0 (n_16), .A1 (n_142), .B0
       (panel_button_lights[1]), .B1 (n_124), .Y (n_164));
  NOR3X1 g13487__2802(.A (n_113), .B (n_133), .C (n_153), .Y (n_160));
  NOR3X1 g13488__1705(.A (n_80), .B (n_135), .C (n_155), .Y (n_159));
  NOR3X1 g13489__5122(.A (n_80), .B (n_136), .C (n_155), .Y (n_163));
  NOR3X1 g13490__8246(.A (n_113), .B (n_134), .C (n_153), .Y (n_162));
  NOR4X1 g13491__7098(.A (n_84), .B (n_101), .C (n_128), .D (n_149), .Y
       (n_161));
  OAI21X1 g13493__6131(.A0 (n_85), .A1 (n_128), .B0 (n_61), .Y (n_158));
  INVX1 g13496(.A (n_156), .Y (n_157));
  INVX1 g13497(.A (n_155), .Y (n_154));
  INVX1 g13498(.A (n_153), .Y (n_152));
  AND3X2 g13499__1881(.A (floor_call_buttons[2]), .B (n_129), .C
       (n_112), .Y (n_151));
  AND3X2 g13500__5115(.A (panel_buttons[2]), .B (n_132), .C (n_110), .Y
       (n_150));
  NAND3X1 g13501__7482(.A (n_34), .B (n_57), .C (n_116), .Y (n_156));
  OAI211X1 g13502__4733(.A0 (n_41), .A1 (n_76), .B0 (n_112), .C0
       (n_129), .Y (n_155));
  OAI211X1 g13503__6161(.A0 (n_44), .A1 (n_76), .B0 (n_110), .C0
       (n_132), .Y (n_153));
  CLKINVX2 g13504(.A (n_148), .Y (n_149));
  NOR2X1 g13505__9315(.A (n_101), .B (n_139), .Y (n_147));
  NAND2X1 g13506__9945(.A (floor_call_buttons[7]), .B (n_131), .Y
       (n_146));
  NOR2X1 g13507__2883(.A (n_111), .B (n_129), .Y (n_145));
  NOR2X1 g13508__2346(.A (n_87), .B (n_139), .Y (n_148));
  OAI21X1 g13509__1666(.A0 (n_96), .A1 (n_95), .B0 (reset_n), .Y
       (n_144));
  OAI21X1 g13510__7410(.A0 (n_34), .A1 (n_70), .B0 (n_137), .Y (n_143));
  NOR2X1 g13511__6417(.A (n_109), .B (n_132), .Y (n_142));
  OAI22X1 g13512__5477(.A0 (n_1), .A1 (n_89), .B0 (n_287), .B1 (n_112),
       .Y (n_141));
  OAI22X1 g13513__2398(.A0 (n_3), .A1 (n_89), .B0 (n_287), .B1 (n_110),
       .Y (n_140));
  INVX2 g13514(.A (n_137), .Y (n_138));
  CLKINVX2 g13515(.A (n_135), .Y (n_136));
  CLKINVX2 g13516(.A (n_133), .Y (n_134));
  CLKINVX2 g13517(.A (n_131), .Y (n_130));
  NAND2X1 g13518__5107(.A (n_67), .B (n_100), .Y (n_127));
  NAND2X1 g13519__6260(.A (n_71), .B (n_99), .Y (n_139));
  NOR2X1 g13520__4319(.A (n_68), .B (n_100), .Y (n_137));
  NAND3X1 g13521__8428(.A (floor_call_buttons[4]), .B (n_10), .C
       (n_86), .Y (n_135));
  NAND3X1 g13522__5526(.A (panel_buttons[4]), .B (n_18), .C (n_86), .Y
       (n_133));
  NAND3X1 g13523__6783(.A (panel_buttons[1]), .B (n_2), .C (n_88), .Y
       (n_132));
  NAND3X1 g13524__3680(.A (floor_call_buttons[6]), .B (n_19), .C
       (n_79), .Y (n_131));
  NAND3X1 g13525__1617(.A (floor_call_buttons[1]), .B (n_0), .C (n_88),
       .Y (n_129));
  OAI21X1 g13526__2802(.A0 (n_36), .A1 (n_72), .B0 (n_61), .Y (n_128));
  CLKINVX2 g13527(.A (n_119), .Y (n_120));
  CLKINVX2 g13528(.A (n_117), .Y (n_118));
  CLKINVX2 g13529(.A (n_114), .Y (n_115));
  AOI21X1 g13530__1705(.A0 (n_76), .A1 (n_286), .B0 (n_287), .Y
       (n_126));
  AOI21X1 g13531__5122(.A0 (n_74), .A1 (n_54), .B0 (n_287), .Y (n_125));
  NAND4X1 g13532__8246(.A (current_floor_state[0]), .B (n_5), .C
       (n_31), .D (n_55), .Y (n_124));
  OAI21X1 g13533__7098(.A0 (n_82), .A1 (n_55), .B0 (n_16), .Y (n_123));
  OAI21X1 g13534__6131(.A0 (n_75), .A1 (n_55), .B0 (n_16), .Y (n_122));
  OAI21X1 g13535__1881(.A0 (n_78), .A1 (n_55), .B0 (n_16), .Y (n_121));
  NOR3X1 g13536__5115(.A (n_24), .B (call_button_lights[8]), .C (n_83),
       .Y (n_119));
  NOR3X1 g13537__7482(.A (n_25), .B (panel_button_lights[8]), .C
       (n_83), .Y (n_117));
  AND4X2 g13538__4733(.A (n_37), .B (n_48), .C (n_59), .D (n_97), .Y
       (n_116));
  NAND3X1 g13539__6161(.A (panel_buttons[6]), .B (n_12), .C (n_79), .Y
       (n_114));
  INVX1 g13540(.A (n_112), .Y (n_111));
  INVX1 g13541(.A (n_110), .Y (n_109));
  INVX1 g13542(.A (n_107), .Y (n_108));
  OAI21X1 g13543__9315(.A0 (n_48), .A1 (n_58), .B0 (n_32), .Y (n_104));
  NAND2X1 g13544__9945(.A (call_button_lights[3]), .B (n_90), .Y
       (n_103));
  NAND2X1 g13545__2883(.A (panel_button_lights[3]), .B (n_90), .Y
       (n_102));
  NOR3X1 g13546__2346(.A (n_14), .B (panel_button_lights[3]), .C
       (n_64), .Y (n_113));
  NAND3X1 g13547__1666(.A (floor_call_buttons[0]), .B (n_1), .C (n_65),
       .Y (n_112));
  NAND3X1 g13548__7410(.A (panel_buttons[0]), .B (n_3), .C (n_65), .Y
       (n_110));
  NOR2X1 g13549__6417(.A (n_86), .B (n_54), .Y (n_107));
  NAND2X1 g13550__5477(.A (n_83), .B (n_55), .Y (n_106));
  OR2X1 g13551__2398(.A (n_79), .B (n_54), .Y (n_105));
  CLKINVX2 g13552(.A (n_98), .Y (n_99));
  AOI22X1 g13553__5107(.A0 (n_5), .A1 (n_63), .B0
       (elevator_floor_selector[3]), .B1 (n_52), .Y (n_96));
  AND4X2 g13554__6260(.A (n_42), .B (n_248), .C (n_247), .D (n_53), .Y
       (n_95));
  NAND3X1 g13555__4319(.A (panel_buttons[9]), .B (n_22), .C (n_82), .Y
       (n_94));
  NAND3X1 g13556__8428(.A (floor_call_buttons[9]), .B (n_20), .C
       (n_82), .Y (n_93));
  AOI21X1 g13559__3680(.A0 (n_47), .A1 (n_62), .B0 (n_37), .Y (n_101));
  NOR3X1 g13560__1617(.A (n_40), .B (n_70), .C (n_81), .Y (n_100));
  NOR3X1 g13561__2802(.A (current_floor_state[0]), .B (n_39), .C
       (n_66), .Y (n_98));
  AND3X2 g13562__1705(.A (n_27), .B (n_49), .C (n_56), .Y (n_97));
  CLKINVX2 g13563(.A (n_84), .Y (n_85));
  CLKINVX2 g13564(.A (n_81), .Y (n_82));
  NAND2X1 g13565__5122(.A (n_64), .B (n_55), .Y (n_90));
  NOR2X1 g13566__8246(.A (n_65), .B (n_54), .Y (n_89));
  OR2X1 g13567__7098(.A (n_17), .B (n_66), .Y (n_88));
  NOR2X1 g13568__6131(.A (n_49), .B (n_66), .Y (n_87));
  NAND2X1 g13569__1881(.A (current_floor_state[2]), .B (n_69), .Y
       (n_86));
  NOR2X1 g13570__5115(.A (n_48), .B (n_62), .Y (n_84));
  NOR2X1 g13571__7482(.A (current_floor_state[0]), .B (n_60), .Y
       (n_83));
  NOR2X1 g13572__4733(.A (n_17), .B (n_60), .Y (n_81));
  CLKINVX2 g13573(.A (n_77), .Y (n_76));
  CLKINVX2 g13574(.A (n_74), .Y (n_73));
  NOR2X1 g13575__6161(.A (n_30), .B (n_69), .Y (n_72));
  OAI211X1 g13576__9315(.A0 (call_button_lights[3]), .A1
       (panel_button_lights[3]), .B0 (n_30), .C0 (n_51), .Y (n_71));
  NOR3X1 g13577__9945(.A (n_15), .B (call_button_lights[3]), .C (n_64),
       .Y (n_80));
  NAND3X1 g13578__2883(.A (current_floor_state[2]), .B
       (current_floor_state[1]), .C (n_46), .Y (n_79));
  NAND4X1 g13579__2346(.A (n_17), .B (n_6), .C
       (current_floor_state[3]), .D (current_floor_state[1]), .Y
       (n_78));
  NAND3X1 g13580__1666(.A (n_17), .B (current_floor_state[1]), .C
       (n_30), .Y (n_77));
  NAND3X1 g13581__7410(.A (current_floor_state[0]), .B
       (current_floor_state[2]), .C (n_35), .Y (n_75));
  NOR3X1 g13582__6417(.A (n_6), .B (current_floor_state[3]), .C (n_51),
       .Y (n_74));
  INVX1 g13583(.A (n_67), .Y (n_68));
  OR2X1 g13584__5477(.A (elevator_floor_selector[3]), .B (n_52), .Y
       (n_63));
  NOR2X1 g13585__2398(.A (n_5), .B (n_31), .Y (n_70));
  NOR2X1 g13586__5107(.A (current_floor_state[1]), .B (n_47), .Y
       (n_69));
  NAND2X1 g13587__6260(.A (n_33), .B (n_5), .Y (n_67));
  NAND2X1 g13588__4319(.A (n_7), .B (n_30), .Y (n_66));
  NAND2X1 g13589__8428(.A (n_46), .B (n_31), .Y (n_65));
  NOR2X1 g13590__5526(.A (n_29), .B (n_51), .Y (n_64));
  INVX1 g13591(.A (n_58), .Y (n_59));
  CLKINVX2 g13592(.A (n_55), .Y (n_54));
  NAND3X1 g13593__6783(.A (elevator_floor_selector[0]), .B (n_17), .C
       (n_246), .Y (n_53));
  NOR2X1 g13594__3680(.A (n_30), .B (n_35), .Y (n_62));
  OR2X2 g13595__1617(.A (n_32), .B (n_29), .Y (n_61));
  NAND2X1 g13596__2802(.A (current_floor_state[3]), .B (n_31), .Y
       (n_60));
  NAND2X1 g13597__1705(.A (n_36), .B (n_32), .Y (n_58));
  NOR3X1 g13598__5122(.A (panel_button_lights[9]), .B
       (call_button_lights[9]), .C (n_33), .Y (n_57));
  AND2X2 g13599__8246(.A (n_38), .B (n_39), .Y (n_56));
  NOR3X1 g13600__7098(.A (emergency_btn), .B (n_245), .C (n_26), .Y
       (n_55));
  CLKINVX2 g13601(.A (n_49), .Y (n_50));
  INVX2 g13602(.A (n_47), .Y (n_46));
  NOR2X1 g13603__6131(.A (n_23), .B (call_button_lights[7]), .Y (n_45));
  NAND2X1 g13604__1881(.A (panel_buttons[2]), .B (n_21), .Y (n_44));
  NOR2X1 g13605__5115(.A (n_13), .B (panel_button_lights[7]), .Y
       (n_43));
  NAND2X1 g13606__7482(.A (elevator_floor_selector[2]), .B (n_6), .Y
       (n_42));
  NAND2X1 g13607__4733(.A (floor_call_buttons[2]), .B (n_11), .Y
       (n_41));
  OR2X2 g13608__6161(.A (elevator_floor_selector[2]), .B (n_6), .Y
       (n_52));
  NOR2X1 g13609__9315(.A (call_button_lights[9]), .B
       (panel_button_lights[9]), .Y (n_40));
  NAND2X1 g13610__9945(.A (current_floor_state[0]), .B
       (current_floor_state[1]), .Y (n_51));
  NOR2X1 g13611__2883(.A (call_button_lights[2]), .B
       (panel_button_lights[2]), .Y (n_49));
  NOR2X1 g13612__2346(.A (call_button_lights[6]), .B
       (panel_button_lights[6]), .Y (n_48));
  NAND2X1 g13613__1666(.A (n_17), .B (n_5), .Y (n_47));
  INVX1 g13614(.A (n_30), .Y (n_29));
  NAND2X1 g13615__7410(.A (reset_n), .B (n_286), .Y (n_28));
  NOR2X1 g13616__6417(.A (call_button_lights[1]), .B
       (panel_button_lights[1]), .Y (n_39));
  NOR2X1 g13617__5477(.A (call_button_lights[0]), .B
       (panel_button_lights[0]), .Y (n_38));
  NOR2X1 g13618__2398(.A (call_button_lights[3]), .B
       (panel_button_lights[3]), .Y (n_27));
  NOR2X1 g13619__5107(.A (call_button_lights[7]), .B
       (panel_button_lights[7]), .Y (n_37));
  NOR2X1 g13620__6260(.A (call_button_lights[5]), .B
       (panel_button_lights[5]), .Y (n_36));
  NOR2X1 g13621__4319(.A (current_floor_state[3]), .B
       (current_floor_state[1]), .Y (n_35));
  NOR2X1 g13622__8428(.A (call_button_lights[10]), .B
       (panel_button_lights[10]), .Y (n_34));
  OR2X2 g13623__5526(.A (panel_button_lights[8]), .B
       (call_button_lights[8]), .Y (n_33));
  NOR2X1 g13624__6783(.A (call_button_lights[4]), .B
       (panel_button_lights[4]), .Y (n_32));
  NOR2X1 g13625__3680(.A (current_floor_state[2]), .B
       (current_floor_state[1]), .Y (n_31));
  NOR2X1 g13626__1617(.A (current_floor_state[2]), .B
       (current_floor_state[3]), .Y (n_30));
  INVX1 g13628(.A (panel_buttons[8]), .Y (n_25));
  INVX1 g13629(.A (floor_call_buttons[8]), .Y (n_24));
  INVX2 g13630(.A (floor_call_buttons[7]), .Y (n_23));
  INVX1 g13631(.A (panel_button_lights[9]), .Y (n_22));
  INVX1 g13632(.A (panel_button_lights[2]), .Y (n_21));
  INVX1 g13634(.A (call_button_lights[9]), .Y (n_20));
  INVX1 g13635(.A (call_button_lights[6]), .Y (n_19));
  INVX1 g13636(.A (panel_button_lights[4]), .Y (n_18));
  CLKINVX2 g13638(.A (current_floor_state[0]), .Y (n_17));
  CLKINVX2 g13639(.A (n_287), .Y (n_16));
  CLKINVX1 g13640(.A (floor_call_buttons[3]), .Y (n_15));
  CLKINVX1 g13641(.A (panel_buttons[3]), .Y (n_14));
  INVX2 g13642(.A (panel_buttons[7]), .Y (n_13));
  INVX1 g13643(.A (panel_button_lights[6]), .Y (n_12));
  INVX1 g13645(.A (call_button_lights[2]), .Y (n_11));
  INVX1 g13646(.A (call_button_lights[4]), .Y (n_10));
  CLKINVX2 g13651(.A (current_floor_state[2]), .Y (n_6));
  CLKINVX2 g13652(.A (current_floor_state[3]), .Y (n_5));
  CLKINVX2 g13653(.A (reset_n), .Y (n_4));
  OAI21X1 g2(.A0 (n_288), .A1 (call_button_lights[5]), .B0 (n_163), .Y
       (n_289));
  NAND2X1 g3(.A (n_75), .B (floor_call_buttons[5]), .Y (n_288));
  OAI21X1 g13654(.A0 (n_290), .A1 (panel_button_lights[5]), .B0
       (n_162), .Y (n_291));
  NAND2X1 g13655(.A (n_75), .B (panel_buttons[5]), .Y (n_290));
endmodule

module button_debouncer_446(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED50, UNCONNECTED51, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED50));
  AND2X1 g73__2802(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED51));
  NOR2X1 g74__1705(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer_445(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED52, UNCONNECTED53, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED52));
  AND2X1 g73__5122(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED53));
  NOR2X1 g74__8246(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer_444(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED54, UNCONNECTED55, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED54));
  AND2X1 g73__7098(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED55));
  NOR2X1 g74__6131(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer_443(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED56, UNCONNECTED57, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED56));
  AND2X1 g73__1881(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED57));
  NOR2X1 g74__5115(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer_442(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED58, UNCONNECTED59, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED58));
  AND2X1 g73__7482(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED59));
  NOR2X1 g74__4733(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer_441(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED60, UNCONNECTED61, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED60));
  AND2X1 g73__6161(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED61));
  NOR2X1 g74__9315(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer_440(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED62, UNCONNECTED63, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED62));
  AND2X1 g73__9945(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED63));
  NOR2X1 g74__2883(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer_439(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED64, UNCONNECTED65, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED64));
  AND2X1 g73__2346(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED65));
  NOR2X1 g74__1666(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer_438(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED66, UNCONNECTED67, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED66));
  AND2X1 g73__7410(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED67));
  NOR2X1 g74__6417(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer_437(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED68, UNCONNECTED69, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED68));
  AND2X1 g73__5477(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED69));
  NOR2X1 g74__2398(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module button_debouncer_436(clock, reset_n, key_in, enable_out);
  input clock, reset_n, key_in;
  output enable_out;
  wire clock, reset_n, key_in;
  wire enable_out;
  wire [1:0] key_current_state;
  wire UNCONNECTED70, UNCONNECTED71, n_0, n_1;
  DFFRX1 \key_current_state_reg[1] (.RN (reset_n), .CK (clock), .D
       (n_1), .Q (enable_out), .QN (UNCONNECTED70));
  AND2X1 g73__5107(.A (key_current_state[0]), .B (key_in), .Y (n_1));
  DFFRX1 \key_current_state_reg[0] (.RN (reset_n), .CK (clock), .D
       (n_0), .Q (key_current_state[0]), .QN (UNCONNECTED71));
  NOR2X1 g74__6260(.A (key_in), .B (enable_out), .Y (n_0));
endmodule

module elevator_top(clock, reset_n, raw_floor_call_buttons,
     raw_panel_buttons, raw_door_open_btn, raw_door_close_btn,
     raw_emergency_btn, raw_power_switch, weight_sensor,
     call_button_lights, panel_button_lights, door_open,
     elevator_control_output, safety_interlock, floor_indicator_lamps,
     elevator_upward_indicator_lamp, elevator_downward_indicator_lamp,
     alarm, weight_overload_lamp);
  input clock, reset_n, raw_door_open_btn, raw_door_close_btn,
       raw_emergency_btn, raw_power_switch, weight_sensor;
  input [10:0] raw_floor_call_buttons, raw_panel_buttons;
  output [10:0] call_button_lights, panel_button_lights,
       elevator_control_output;
  output door_open, safety_interlock, elevator_upward_indicator_lamp,
       elevator_downward_indicator_lamp, alarm, weight_overload_lamp;
  output [3:0] floor_indicator_lamps;
  wire clock, reset_n, raw_door_open_btn, raw_door_close_btn,
       raw_emergency_btn, raw_power_switch, weight_sensor;
  wire [10:0] raw_floor_call_buttons, raw_panel_buttons;
  wire [10:0] call_button_lights, panel_button_lights,
       elevator_control_output;
  wire door_open, safety_interlock, elevator_upward_indicator_lamp,
       elevator_downward_indicator_lamp, alarm, weight_overload_lamp;
  wire [3:0] floor_indicator_lamps;
  wire [3:0] elevator_floor_selector;
  wire [4:0] elevator_state;
  wire [10:0] floor_call_buttons;
  wire [10:0] panel_buttons;
  wire UNCONNECTED72, UNCONNECTED73, UNCONNECTED74, UNCONNECTED_HIER_Z,
       UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z2,
       UNCONNECTED_HIER_Z3;
  wire activate_elevator, direction_selector, door_close_btn,
       door_close_logic_check, door_open_btn, door_open_logic_check,
       emergency_btn, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_82;
  assign weight_overload_lamp = weight_sensor;
  assign alarm = elevator_control_output[6];
  assign elevator_downward_indicator_lamp = elevator_control_output[3];
  assign elevator_upward_indicator_lamp = elevator_control_output[2];
  assign floor_indicator_lamps[0] = elevator_control_output[7];
  assign floor_indicator_lamps[1] = elevator_control_output[8];
  assign floor_indicator_lamps[2] = elevator_control_output[9];
  assign floor_indicator_lamps[3] = elevator_control_output[10];
  assign safety_interlock = elevator_control_output[4];
  assign elevator_control_output[0] = elevator_control_output[4];
  assign elevator_control_output[1] = elevator_control_output[5];
  button_debouncer_434 door_close_debouncer(clock, reset_n, n_13,
       door_close_btn);
  button_debouncer_435 door_open_debouncer(clock, reset_n, n_6,
       door_open_btn);
  elevator_fsm elevator_fsm_inst(clock, reset_n,
       elevator_floor_selector, emergency_btn, activate_elevator,
       weight_sensor, raw_power_switch, direction_selector,
       elevator_state, {elevator_control_output[10:6], UNCONNECTED74,
       elevator_control_output[4:2], UNCONNECTED73, UNCONNECTED72});
  button_debouncer_433 emergency_debouncer(clock, reset_n, n_82,
       emergency_btn);
  button_debouncer floor_call_debouncer0(clock, reset_n, n_8,
       floor_call_buttons[0]);
  button_debouncer_456 floor_call_debouncer1(clock, reset_n, n_19,
       floor_call_buttons[1]);
  button_debouncer_455 floor_call_debouncer2(clock, reset_n, n_17,
       floor_call_buttons[2]);
  button_debouncer_454 floor_call_debouncer3(clock, reset_n, n_9,
       floor_call_buttons[3]);
  button_debouncer_453 floor_call_debouncer4(clock, reset_n, n_24,
       floor_call_buttons[4]);
  button_debouncer_452 floor_call_debouncer5(clock, reset_n, n_7,
       floor_call_buttons[5]);
  button_debouncer_451 floor_call_debouncer6(clock, reset_n, n_3,
       floor_call_buttons[6]);
  button_debouncer_450 floor_call_debouncer7(clock, reset_n, n_16,
       floor_call_buttons[7]);
  button_debouncer_449 floor_call_debouncer8(clock, reset_n, n_18,
       floor_call_buttons[8]);
  button_debouncer_448 floor_call_debouncer9(clock, reset_n, n_2,
       floor_call_buttons[9]);
  button_debouncer_447 floor_call_debouncer10(clock, reset_n, n_14,
       floor_call_buttons[10]);
  floor_logic_control_unit floor_logic_inst(clock, reset_n,
       floor_call_buttons, panel_buttons, door_open_btn,
       door_close_btn, emergency_btn, raw_power_switch,
       elevator_control_output[10:7], {UNCONNECTED_HIER_Z3,
       UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z0,
       UNCONNECTED_HIER_Z}, elevator_control_output[5],
       elevator_control_output[2], elevator_floor_selector,
       direction_selector, activate_elevator, call_button_lights,
       panel_button_lights, door_open_logic_check,
       door_close_logic_check);
  button_debouncer_446 panel_debouncer0(clock, reset_n, n_10,
       panel_buttons[0]);
  button_debouncer_445 panel_debouncer1(clock, reset_n, n_11,
       panel_buttons[1]);
  button_debouncer_444 panel_debouncer2(clock, reset_n, n_22,
       panel_buttons[2]);
  button_debouncer_443 panel_debouncer3(clock, reset_n, n_4,
       panel_buttons[3]);
  button_debouncer_442 panel_debouncer4(clock, reset_n, n_15,
       panel_buttons[4]);
  button_debouncer_441 panel_debouncer5(clock, reset_n, n_20,
       panel_buttons[5]);
  button_debouncer_440 panel_debouncer6(clock, reset_n, n_21,
       panel_buttons[6]);
  button_debouncer_439 panel_debouncer7(clock, reset_n, n_23,
       panel_buttons[7]);
  button_debouncer_438 panel_debouncer8(clock, reset_n, n_12,
       panel_buttons[8]);
  button_debouncer_437 panel_debouncer9(clock, reset_n, n_5,
       panel_buttons[9]);
  button_debouncer_436 panel_debouncer10(clock, reset_n, n_1,
       panel_buttons[10]);
  INVX1 g325(.A (door_open_logic_check), .Y (n_25));
  CLKINVX1 g330(.A (raw_floor_call_buttons[4]), .Y (n_24));
  CLKINVX1 g334(.A (raw_panel_buttons[7]), .Y (n_23));
  CLKINVX1 g329(.A (raw_panel_buttons[2]), .Y (n_22));
  CLKINVX1 g332(.A (raw_panel_buttons[6]), .Y (n_21));
  CLKINVX1 g331(.A (raw_panel_buttons[5]), .Y (n_20));
  CLKINVX1 g344(.A (raw_floor_call_buttons[1]), .Y (n_19));
  CLKINVX1 g348(.A (raw_floor_call_buttons[8]), .Y (n_18));
  CLKINVX1 g326(.A (raw_floor_call_buttons[2]), .Y (n_17));
  CLKINVX1 g349(.A (raw_floor_call_buttons[7]), .Y (n_16));
  CLKINVX1 g346(.A (raw_panel_buttons[4]), .Y (n_15));
  CLKINVX1 g345(.A (raw_emergency_btn), .Y (n_82));
  CLKINVX1 g342(.A (raw_floor_call_buttons[10]), .Y (n_14));
  CLKINVX1 g333(.A (raw_door_close_btn), .Y (n_13));
  CLKINVX1 g340(.A (raw_panel_buttons[8]), .Y (n_12));
  CLKINVX1 g328(.A (raw_panel_buttons[1]), .Y (n_11));
  CLKINVX1 g327(.A (raw_panel_buttons[0]), .Y (n_10));
  CLKINVX1 g347(.A (raw_floor_call_buttons[3]), .Y (n_9));
  CLKINVX1 g339(.A (raw_floor_call_buttons[0]), .Y (n_8));
  CLKINVX1 g338(.A (raw_floor_call_buttons[5]), .Y (n_7));
  CLKINVX1 g337(.A (raw_door_open_btn), .Y (n_6));
  CLKINVX1 g335(.A (raw_panel_buttons[9]), .Y (n_5));
  CLKINVX1 g341(.A (raw_panel_buttons[3]), .Y (n_4));
  CLKINVX1 g343(.A (raw_floor_call_buttons[6]), .Y (n_3));
  CLKINVX1 g350(.A (raw_floor_call_buttons[9]), .Y (n_2));
  CLKINVX1 g336(.A (raw_panel_buttons[10]), .Y (n_1));
  CLKINVX2 g300(.A (elevator_control_output[4]), .Y
       (elevator_control_output[5]));
  OAI21X1 g315__4319(.A0 (door_close_logic_check), .A1
       (elevator_control_output[5]), .B0 (n_25), .Y (door_open));
endmodule

